### ISSUE TITLE
Splunk Operator: helm install ignores custom values files. 

### ISSUE THREAD

**Issue by iaroslav-nakonechnikov** [splunk/splunk-operator#1007]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
`splunk-operator` don't use custom values for images in `values.yml` on `helm install` command.

**Expected behavior**
All expected as it is described in documentation: https://github.com/splunk/splunk-operator/blob/main/docs/Helm.md

**Splunk setup on K8S**
K8S 1.24 running on EKS.

**Reproduction/Testing steps**
splunk-operator.values.yml:
```
image:
  repository: proxy.host/docker/splunk/splunk
kubeRbacProxy:
  image:
    repository: proxy.host/gcr.io-docker-proxy/kubebuilder/kube-rbac-proxy
    pullPolicy: IfNotPresent
    tag: "v0.11.0"
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi
splunkOperator:
  image:
    repository: proxy.host/docker/splunk/splunk-operator:latest
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  clusterWideAccess: true
  watchNamespaces: ""
  annotations: {}
  podAnnotations: {}
  containerSecurityContext:
    allowPrivilegeEscalation: false
  securityContext:
    runAsUser: 1001
    fsGroup: 1001
    runAsNonRoot: true
  hostNetwork: false
  hostPID: false
  hostIPC: false
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8081
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8081
    initialDelaySeconds: 5
    periodSeconds: 10
  service:
    type: ClusterIP
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 1000m
      memory: 2000Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  terminationGracePeriodSeconds: 10
  volumes:
  - name: app-staging
    persistentVolumeClaim:
      claimName: splunk-operator-app-download
  volumeMounts:
  - mountPath: /opt/splunk/appframework/
    name: app-staging
```

then run:
```
helm install -f splunk-operator.values.yml splunk-operator https://proxy.host/artifactory/splunk-github-io-splunk-operator-helm-proxy/splunk-enterprise-1.0.0.tgz -n splunk-operator
```

it will print: 
```
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
NAME: splunk-operator
LAST DEPLOYED: Wed Dec 14 12:50:39 2022
NAMESPACE: splunk-operator
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

and then check definition of deployemnt `kubectl describe deployment.apps/splunk-operator-controller-manager -n splunk-operator`
```
...
manager:
    Image:      docker.io/splunk/splunk-operator:latest
...
    Environment:
      WATCH_NAMESPACE:
      POD_NAME:                          (v1:metadata.name)
      OPERATOR_NAME:                    splunk-operator
      RELATED_IMAGE_SPLUNK_ENTERPRISE:  docker.io/splunk/splunk:edge
...
```

**K8s environment**
EKS with K8s 1.24
helm 3.9
splunk-operator chart - 1.0.0

**Comment by vivekr-splunk** [comment]
hello @iaroslav-nakonechnikov am looking at this issue now, will get back to you with my findings.

**Comment by vivekr-splunk** [comment]
Hello @iaroslav-nakonechnikov i tested the changes on my system and it is working as documented here https://github.com/splunk/splunk-operator/blob/main/docs/Helm.md

- I created new values yaml file 
- `image:
  repository: docker.io/splunk/splunk:9.0.2

splunkOperator:
  image:
    repository: docker.io/vivekr/splunk:splunk-operator:2.1.0`
- installed splunk operator 
- `helm install -f values.yaml splunk-operator splunk/splunk-operator  -n test2 --create-namespace`
- the image for both splunk and splunk operator are updated as mentioned in values.yaml file
- ` ``     - name: WATCH_NAMESPACE
      - name: POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: OPERATOR_NAME
        value: splunk-operator
      - name: RELATED_IMAGE_SPLUNK_ENTERPRISE
        value: docker.io/splunk/splunk:9.0.2
      image: docker.io/vivekrsplunk/splunk-operator:2.1.0
      imagePullPolicy: IfNotPresent
      livenessProbe:```

**Comment by iaroslav-nakonechnikov** [comment]
this is very strange.

i tried your example, but it looks like invalid yaml. 
i tried next ones:
```
image:
  repository: host/docker/splunk/splunk:9.0.2
kubeRbacProxy:
  image:
    repository: host/gcr.io-docker-proxy/kubebuilder/kube-rbac-proxy:v0.13.0
splunkOperator:
  image:
    repository: host/docker/splunk/splunk-operator:2.1.1
```
and 
```
image.repository: host/docker/splunk/splunk:9.0.2
kubeRbacProxy.image.repository: host/gcr.io-docker-proxy/kubebuilder/kube-rbac-proxy:v0.13.0
splunkOperator.image.repository: host/docker/splunk/splunk-operator:2.1.1
```

same result everywhere. 

helm version: version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}
