### ISSUE TITLE
Custom LicenseManager StorageConfig ignored with helm

### ISSUE THREAD

**Issue by markusspitzli** [splunk/splunk-operator#1012]
### Please select the type of request

Bug

### Tell us more

I tried to configure a clustered environment (sva.c3) with a licenseManager. 
 
The resources and Volume Storage Config are restricted. That seems to work for every CR expect of the licenseMaster. 
I configured:
```
licenseManager:
  enabled: true
  name: lm
  etcVolumeStorageConfig:
    storageCapacity: 5Gi
  varVolumeStorageConfig:
    storageCapacity: 20Gi
 ```

But in the end the setting were not taken. The default setting were applied. According to the Helm Chart (enterprise_v4_licensemanager.yaml) these settings aren’t parsed, why the default settings are taken.

**Comment by vivekr-splunk** [comment]
this this new changes with the below helm values it worked fine in 2.2.1
```
splunk-operator:
  enabled: true
  splunkOperator:
    clusterWideAccess: false

sva:
  c3:
    enabled: true
    indexerClusters:
       - name: idx1
       - name: idx2

    searchHeadClusters:
       - name: shc1
       - name: shc2


indexerCluster:
  replicas: 3

searchHeadCluster:
  replicas: 3


licenseManager:
  enabled: true
  name: lm
  etcVolumeStorageConfig:
    storageCapacity: 5Gi
  varVolumeStorageConfig:
    storageCapacity: 20Gi
```
