### ISSUE TITLE
Splunk Operator: Standalone instance image not available anymore

### ISSUE THREAD

**Issue by ajaykanse** [splunk/splunk-operator#1016]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
- Upgrade operator to use correct sha of the splunk/splunk image from Dockerhub
- The standalone splunk instance currently using splunk/splunk@sha256:c952e7fc25815bec35282a829f50c9fd52ac9c43f5586163f1cad834d1c779d4. This image ( sha ) doesn't seem to be available in dockerhub anymore. 
- See below command when used directly to pull image -
podman pull splunk/splunk@sha256:c952e7fc25815bec35282a829f50c9fd52ac9c43f5586163f1cad834d1c779d4
Resolved "splunk/splunk" as an alias (/home/lab-user/.cache/containers/short-name-aliases.conf)
Trying to pull docker.io/splunk/splunk@sha256:c952e7fc25815bec35282a829f50c9fd52ac9c43f5586163f1cad834d1c779d4...
Error: Error initializing source docker://splunk/splunk@sha256:c952e7fc25815bec35282a829f50c9fd52ac9c43f5586163f1cad834d1c779d4: Error reading manifest sha256:c952e7fc25815bec35282a829f50c9fd52ac9c43f5586163f1cad834d1c779d4 in docker.io/splunk/splunk: manifest unknown: manifest unknown

**Expected behavior**
- Correct sha for the splunk/splunk image should be used in operator

**Splunk setup on K8S**
- Testing this on OpenShift but Kubernetes would have same issue

**Reproduction/Testing steps**
- Install splunk operator ( Operator installation would be successful )
- Create standalone splunk instance 
- Look at the events and pod will fail with imagepullbackoff error

**K8s environment**
- Useful information about the K8S environment being used. Eg. version of K8s, kind of K8s cluster etc..

**Proposed changes(optional)**
- Proposed change, if any.

**K8s collector data(optional)**
- Please provide data collected from the [K8s collectors](https://github.com/splunk/splunk-operator/blob/develop/docs/K8SCollectors.md), if any.

**Additional context(optional)**
- Add any other context about the problem here.

**Comment by Joel-hanson** [comment]
Hi I am also having this similar issue.

**Comment by vivekr-splunk** [comment]
@Joel-hanson thanks for your reply, have you used operator bundle to install splunk-operator from openshift portal ?

**Comment by Joel-hanson** [comment]
Yes I have tired both from the openshit operatorhub as well as using the splunk-operator-cluster.yaml from the official website ie. https://splunk.github.io/splunk-operator.

**Comment by putz612** [comment]
Legacy issues here, if it does not like or know your filesystem it fails. 
https://docs.splunk.com/Documentation/Splunk/9.0.3/Troubleshooting/FSLockingIssues
To fix it you need to add an extraVar to each section. For example 

```yaml
    searchHeadCluster:
      enabled: true
      extraEnv:
        - name: OPTIMISTIC_ABOUT_FILE_LOCKING
          value: "1"

    indexerCluster:
      enabled: true
      extraEnv:
        - name: OPTIMISTIC_ABOUT_FILE_LOCKING
          value: "1"
  
    clusterMaster:
      enabled: true
      extraEnv:
        - name: OPTIMISTIC_ABOUT_FILE_LOCKING
          value: "1"
```
Splunk just *might* want to add this as a flag to the chart.
