### ISSUE TITLE
Splunk Operator: helm chart can't be installed if there is not pvc being created

### ISSUE THREAD

**Issue by iaroslav-nakonechnikov** [splunk/splunk-operator#1024]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
I've noticed, that helm chart failing with installation, when it was requested to use ephemeral volumes. 

**Expected behavior**
splunk-operator chart works as expected by documenation. 

**Splunk setup on K8S**
eks 1.22
splunk-operator 2.1.1

**Reproduction/Testing steps**
install splunk-operator with:
```
volumes:
  - name: app-staging
    hostPath:
      path: /some/host/path
      type: DirectoryOrCreate
volumeMounts:
  - mountPath: /opt/splunk/appframework/
    name: app-staging
```
or
```
volumes:
  - name: app-staging
    emptyDir:
      sizeLimit: 10Gi
volumeMounts:
  - mountPath: /opt/splunk/appframework/
    name: app-staging
```

**Additional context(optional)**
why it is needed?

1. for testing/development purposes - it starts for 15sec. 
2. for making it independent from node az. By default pvc is connected to az, so need add configs to make it works. 
with letting to use hostPath - it becoming independent.
3. i see no reason to stick to permanent storage. Maybe best scenario will be to use s3 bucket for that volume.

**Comment by iaroslav-nakonechnikov** [comment]
```Error: rendered manifests contain a resource that already exists. Unable to continue with install: PersistentVolumeClaim "splunk-operator-app-download" in namespace "splunk-operator" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "splunk-operator"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "splunk-operator"```

looks like something hardcoded in chart.

**Comment by vivekr-splunk** [comment]
please use 2 step process now to install operator and install splunk instance, we are working on fixing few issues in splunk operator helm chart. here is the example 
```
 helm install splunk-operator splunk/splunk-operator --create-namespace -n splunk-operator --set splunkOperator.clusterWideAccess=false
NAME: splunk-operator
LAST DEPLOYED: Mon Jan  9 09:51:20 2023
NAMESPACE: splunk-operator
STATUS: deployed
REVISION: 1
TEST SUITE: None


 helm install --set sva.s1.enabled=true --set splunk-operator.enabled=false splunk-s1 splunk/splunk-enterprise -n splunk-operator --create-namespace 
NAME: splunk-s1
LAST DEPLOYED: Mon Jan  9 09:51:46 2023
NAMESPACE: splunk-operator
STATUS: deployed
REVISION: 1
TEST SUITE: None

 kubectl get pods -n splunk-operator  -w
NAME                                                  READY   STATUS    RESTARTS   AGE
splunk-operator-controller-manager-7578cd4c87-87mvj   2/2     Running   0          108s
splunk-stdln-standalone-0                             1/1     Running   0          86s
```

if you want to use ephemeral volume for operator also you can change them in values.yaml file. 

```
  # Specify volumes for Splunk Operator pod, append additional volumes to list
  # reference: https://kubernetes.io/docs/concepts/storage/volumes/
  volumes:
  - name: app-staging
    persistentVolumeClaim:
      claimName: splunk-operator-app-download
# - name:
#   persistentVolumeClaim:
#     claimName:

  # Specify volume mounts for the manager container, append additional volume mounts to list
  # reference: https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/
  volumeMounts:
  - mountPath: /opt/splunk/appframework/
    name: app-staging
# - mountPath:
#   name:
```
