### ISSUE TITLE
Splunk Operator does not apply changed settings

### ISSUE THREAD

**Issue by markusspitzli** [splunk/splunk-operator#1027]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
We use the provided helm charts in version 2.1.1 in which we apply configurations within the values file. When changing the resources or indexes the changes are applied via the crds to k8s, but the splunk operator does not apply the changes to the environment. changes in resources does not result in a restart of the changed containers or indexes aren't deployed in the clustermanager nor distributed to the indexer peers. 

**Expected behavior**
changes with the helm values files has to result in actual changes in the splunk environments and containers. 

**Splunk setup on K8S**
We are using a 5node K8s cluster based on v.1.22.12

**Reproduction/Testing steps**
1. install splunk operator
2. install splunk enterprise with smartstore and a sva.c3 environment
3. add a new index to the value file and upgrade the splunk enterprise chart
4. verify the in the clustermanager -> kubectl k describe clustermanagers.enterprise.splunk.com cm (change is applied)
5. verify the indexes.conf on the cm pod -> kubectl exec -it splunk-cm-cluster-manager-0 -- cat etc/manager-apps/splunk-operator/local/indexes.conf

**Comment by vivekr-splunk** [comment]
Hello Markus, I am looking into this issue now, will get back to you soon with my analysis. thank you

**Comment by vivekr-splunk** [comment]
Hello Markus, I investigated the issue , here is what I have tried 

- created splunk operator using helm chart 
```
helm install splunk-operator ./helm-chart/splunk-operator  --set splunkOperator.clusterWideAccess=true --create-namespace --namespace splunk-operator
```
- installed splunk enterprise with appframework and sva.c3 environment
```
> cat new_c3_values.yaml
cat new_c3_values.yaml                            
splunk-operator:
  enabled: false

sva:
  c3:
    enabled: true
    indexerClusters:
       - name: idx1
       - name: idx2

    searchHeadClusters:
       - name: shc1
       - name: shc2


indexerCluster:
  replicas: 3

searchHeadCluster:
  replicas: 3

clusterManager:
  appRepo:
    appsRepoPollIntervalSeconds: 60
    defaults:
      volumeName: volume_app_repo_3
      scope: cluster
    appSources:
      - name: appsFromPerf
        location: cspl_1250_apps/
        scope: cluster
        volumeName: volume_app_repo_3
      - name: appsFromIndexes
        location: c3appfw-idxc-o127/
        scope: cluster
        volumeName: volume_app_repo_2
    volumes:
      - name: volume_app_repo_2
        storageType: s3
        provider: aws
        path: akondur-appframework-test/
        endpoint: https://s3-us-west-2.amazonaws.com
        secretRef: s3-secret
>  helm install splunk-c3 -f new_c3_values.yaml helm-chart/splunk-enterprise -n splunk-operator
```
- if you check above steps, I am using appframework to install new apps
- I created new apps following splunk documentation to create new indexes
- create new `helloworld` apps 
```
 @vivekr  find .             
.
./helloworld
./helloworld/bin
./helloworld/default
./helloworld/default/app.conf
./helloworld/local
./helloworld/local/indexes.conf
./helloworld/metadata
./helloworld.spl
  @vivekr  cat helloworld/local/indexes.conf 
[test]
homePath   = $SPLUNK_DB/test/db
coldPath   = $SPLUNK_DB/test/colddb
thawedPath = $SPLUNK_DB/test/thaweddb
 @vivekr  cat helloworld/default/app.conf  
[install]
is_configured = 1

[ui]
is_visible = 0
label = Test App

[launcher]
author = Vivek
description = testing this app for the first time, hope it works!
version = 1.0.0
```
- created spl file out of this 
```
 @vivekr  gtar -cvzf helloworld.spl helloworld/
```
- uploaded this to my s3 bucket 
- added s3 bucket and path of the app in my values.yaml file
```
  @vivekr  cat new_c3_values.yaml                            
splunk-operator:
  enabled: false

sva:
  c3:
    enabled: true
    indexerClusters:
       - name: idx1
       - name: idx2

    searchHeadClusters:
       - name: shc1
       - name: shc2


indexerCluster:
  replicas: 3

searchHeadCluster:
  replicas: 3

clusterManager:
  appRepo:
    appsRepoPollIntervalSeconds: 60
    defaults:
      volumeName: volume_app_repo_2
      scope: cluster
    appSources:
      - name: appsFromPerf
        location: cspl_1250_apps/
        scope: cluster
        volumeName: volume_app_repo_2
      - name: appsFromIndexes
        location: c3appfw-idxc-o127/
        scope: cluster
        volumeName: volume_app_repo_3
    volumes:
      - name: volume_app_repo_2
        storageType: s3
        provider: aws
        path: akondur-appframework-test/
        endpoint: https://s3-us-west-2.amazonaws.com
        secretRef: s3-secret
      - name: volume_app_repo_3
        storageType: s3
        provider: aws
        path: vivek-app-test-bucket/
        endpoint: https://s3-us-west-2.amazonaws.com
        secretRef: s3-secret
```
- updated helm chart with new changes to values.yaml file
```
> helm upgrade splunk-c3 -f new_c3_values.yaml helm-chart/splunk-enterprise -n splunk-operator
```
- I can see the new index configurations are copied to cluster manager and indexer cluster
```
 @vivekr  kubectl exec -it -n splunk-operator splunk-cm-cluster-manager-0 -- cat /opt/splunk/etc/manager-apps/helloworld/local/indexes.conf
[test]
homePath   = $SPLUNK_DB/test/db
coldPath   = $SPLUNK_DB/test/colddb
thawedPath = $SPLUNK_DB/test/thaweddb
 @vivekr  kubectl exec -it -n splunk-operator splunk-idx1-indexer-0 -- cat /opt/splunk/etc/peer-apps/helloworld/local/indexes.conf

[test]
homePath   = $SPLUNK_DB/test/db
coldPath   = $SPLUNK_DB/test/colddb
thawedPath = $SPLUNK_DB/test/thaweddb
```
- I checked indexer to see if new index `test` is created with following command 
```
sh-4.4$ ./splunk search '| eventcount summarize=false index=test index=test | dedup index | fields index' 
WARNING: Server Certificate Hostname Validation is disabled. Please see server.conf/[sslConfig]/cliVerifyServerName for details.
Your session is invalid.  Please login.
Splunk username: admin
Password: 
index
-----
test
```
so it all works fine with new `appframework` . 
- I added new entry to existing values.yaml file for smartstore 
```
 @vivekr  cat new_c3_values.yaml         
splunk-operator:
  enabled: false

sva:
  c3:
    enabled: true
    indexerClusters:
       - name: idx1
       - name: idx2

    searchHeadClusters:
       - name: shc1
       - name: shc2


indexerCluster:
  replicas: 3

searchHeadCluster:
  replicas: 3

clusterManager:
  smartstore:
    defaults:
        volumeName: vivek-cluster-bucket
    indexes:
      - name: main
        remotePath: $_index_name
        volumeName: vivek-cluster-bucket
      - name: cloudwatch
        remotePath: $_index_name
        volumeName: vivek-cluster-bucket
    volumes:
      - name: vivek-cluster-bucket
        path: vivek-cluster-bucket/smartstore
        endpoint: https://s3-us-west-2.amazonaws.com
        secretRef: s3-secret
  appRepo:
    appsRepoPollIntervalSeconds: 60
    defaults:
      volumeName: volume_app_repo_2
      scope: cluster
    appSources:
      - name: appsFromPerf
        location: cspl_1250_apps/
        scope: cluster
        volumeName: volume_app_repo_2
      - name: appsFromIndexes
        location: c3appfw-idxc-o127/
        scope: cluster
        volumeName: volume_app_repo_3
    volumes:
      - name: volume_app_repo_2
        storageType: s3
        provider: aws
        path: akondur-appframework-test/
        endpoint: https://s3-us-west-2.amazonaws.com
        secretRef: s3-secret
      - name: volume_app_repo_3
        storageType: s3
        provider: aws
        path: vivek-app-test-bucket/
        endpoint: https://s3-us-west-2.amazonaws.com
        secretRef: s3-secret
```
- updated the c3 instance with new values
```
@vivekr  helm upgrade splunk-c3 -f new_c3_values.yaml helm-chart/splunk-enterprise -n splunk-operator
```
- I could see the new smart store entries created on s3 bucket, I also checked cluster manager custom resource and the new spec changes are passed to the resource. 
- I check cluster manager and i can see the new indexes configuration created 
```
kubectl exec -it -n splunk-operator splunk-cm-cluster-manager-0 -- cat /opt/splunk/etc/manager-apps/splunk-operator/local/indexes.conf
[default]
repFactor = auto
maxDataSize = auto
homePath = $SPLUNK_DB/$_index_name/db
coldPath = $SPLUNK_DB/$_index_name/colddb
thawedPath = $SPLUNK_DB/$_index_name/thaweddb
remotePath = volume:xxxxx-xxxxxxx/$_index_name
 
[volume:xxxxx-xxxxxxx]
storageType = remote
path = s3://xxxxx-xxxxxxx/smartstore
remote.s3.access_key = xxxxxxx
remote.s3.secret_key = xxxxxxx
remote.s3.endpoint = https://s3-us-west-2.amazonaws.com
 
[main]
remotePath = volume:xxxxx-xxxxxxx/$_index_name

[cloudwatch]
remotePath = volume:xxxxx-xxxxxxx/$_index_name
```

**Comment by markusspitzli** [comment]
Hi @vivekr-splunk 

Thanks for your description. 
I set up a new instance and tried everything from scratch, but I wasnt able to reproduce why your configuration works. 
Well, we have a different setup because we have to use the namespaced operator. 

Let's see what I have setup. Maybe you are able to reproduce it on your side. 

First I create a namespace. lets assume its demo
`kubectl create ns demo`

Aftewards I install my own helm chart. which basically creates configuration specific to our enviroment. And it als creates S3 Instances on our enviroment. 

The next part is installing the splunk operator in the namespace: (we have to use our own artifactory which is more or less a proxy for accessing the official helm repo)
` helm install splunk-operator splunk-operator/splunk-operator  -f values.splunk-operator.namespace.yaml  `

The values.splunk-operator.namespace.yaml contains:
```
image:
  repository: remote-docker.artifactory.mycompany.com/splunk/splunk:9.0.2

kubeRbacProxy:
  # Specify kube-rbac-proxy image
  image: 
    repository: gcr-remote.artifactory.mycompany.com/kubebuilder/kube-rbac-proxy

# Splunk Operator configurations
splunkOperator: 

  # Splunk operator image and pull policy
  # reference: https://github.com/splunk/splunk-operator
  image:
    repository: remote-docker.artifactory.mycompany.com/splunk/splunk-operator:2.1.1
 
  # Give operator cluster-wide access, otherwise access is limited to operator namespace
  clusterWideAccess: false
```

Now I'm installing the Splunk Enterprise environment:
`helm install splunk-enterprise splunk-operator/splunk-enterprise -f values.cluster-instance.yaml  `

The value file (values.cluster-instance.yaml) contains:

```
splunk-operator:
  enabled: false

existingLicenseManager: 
  name: lm 
  namespace: shared

sva:
  c3:
    enabled: true
    indexerClusters:
    - name: idx1
    searchHeadClusters:
    - name: shc1

clusterManager:
  appRepo:
    appsRepoPollIntervalSeconds: 600
    defaults:
      volumeName: volume_app_repo
      scope: cluster
    appSources:
      - name: cluster
        location: demo/ClusterMaster/cluster/
      - name: local
        location: demo/ClusterMaster/local/
        scope: local
    volumes:
      - name: volume_app_repo
        storageType: s3
        provider: minio
        path: apps/
        endpoint: https://endpoint.mycompany.com
        secretRef: s3-secret-apps
  smartstore:
    defaults:
      volumeName: s2s3_vol
    indexes:
      - name: mytest
        remotePath: $_index_name
        volumeName: s2s3_vol
    volumes:
      - name: s2s3_vol
        path: data/
        endpoint: https://endpoint.mycompany.com
        secretRef: s3-secret-data
    cacheManager:
      hotlistBloomFilterRecencyHours: 360 # 15 days - splunk defaults - (can be lowered to 5 days)
      hotlistRecencySecs: 86400           # 24 hours - splunk defaults
      evictionPadding: 1024               # 1Gi
      evictionPolicy: lru                 # splunk defaults
      maxCacheSize: 0                     # Eviction will be based on the sum of 'minFreeSpace (5Gi)' and 'eviction_padding'
      maxConcurrentDownloads: 8           # splunk defaults
      maxConcurrentUploads: 8             # splunk defaults

searchHeadCluster:
  appRepo:
    appsRepoPollIntervalSeconds: 600
    defaults:
      volumeName: volume_app_repo
      scope: cluster
    appSources:
      - name: cluster
        location: demo/SearchHeadCluster/cluster/
      - name: local
        location: demo/SearchHeadCluster/local/
        scope: local
    volumes:
      - name: volume_app_repo
        storageType: s3
        provider: minio
        path: apps/
        endpoint: https://endpoint.mycompany.com
        secretRef: s3-secret-apps


```
