### ISSUE TITLE
Splunk Operator: PersistentVolumeClaim splunk-operator-app-download cannot be bound with volumeMode: Filesystem

### ISSUE THREAD

**Issue by vitalyrychkov** [splunk/splunk-operator#1052]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
When I deploy the splunk-operator Helm chart in our bare-metal K8s cluster, the PersistentVolumeClaim splunk-operator-app-download cannot be bound with volumeMode: Filesystem and stays in the "Pending" state. 
Could you please add an option to use a storageClass instead?
If possible, also allow for defining the volume size.

**Expected behavior**
Splunk Operator pod to start successfully.

**Splunk setup on K8S**
Fresh install

**Reproduction/Testing steps**
kubectl create ns splunk-operator
 helm install -f values-operator.yaml splunk-operator splunk/splunk-operator -n splunk-operator

**K8s environment**
Bare-metal K8S v1.24.5

**Proposed changes(optional)**
Could you please add an option in the values file to use a storageClass instead of "volumeMode: Filesystem" in the https://github.com/splunk/splunk-operator/blob/main/helm-chart/splunk-operator/templates/app_download.yaml template?
If possible, also allow for defining the volume size.

Rendered spec example would be:
```
  volumes:
  - name: app-staging
    persistentVolumeClaim:
      claimName: splunk-operator-app-download
  resources:
    requests:
      storage: 5Gi
  storageClassName: sc-nfs
```

**K8s collector data(optional)**
N/A

**Additional context(optional)**
