### ISSUE TITLE
Wrong smartstore settings in helm charts for standalone

### ISSUE THREAD

**Issue by markusspitzli** [splunk/splunk-operator#1063]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
I tried to create a Standalone instance with Smartstore support by using helm chart. I received an error that wrong settings were used for smartstore. 

**Expected behavior**
no issues when using helm charts 

**Splunk setup on K8S**
The helm chart values I used for splunk-enterprise:

```
sva:
    s1:
      enabled: true

  standalone:
    enabled: true  
    volumes:
      - name: splunk-defaults-indexers
        configMap:
          name: splunk-defaults-indexers
      - name: splunk-defaults-searchheads
        configMap:
          name: splunk-defaults-searchheads
      - name: licenses
        configMap:
          name: splunk-licenses
    defaultsUrl: "/mnt/splunk-defaults-indexers/splunk-defaults-indexers.yaml,/mnt/splunk-defaults-searchheads/splunk-defaults-searchheads.yaml"
    licenseUrl: /mnt/licenses/licenses.lic
    appRepo:
      appsRepoPollIntervalSeconds: 600
      defaults:
        volumeName: volume_app_repo
        scope: local
      appSources:
        - name: local
          location: arch-test/Standalone/local/
          scope: local
      volumes:
        - name: volume_app_repo
          storageType: s3
          provider: minio
          path: apps/
          endpoint: https://endpoint.mycompany.com
          secretRef: mysecrete
    smartstore:
      defaults:
        volumeName: s3_vol
      # ==> define indexes if needed <==
      indexes:
        - name: mytestdata
          remotePath: $_index_name
          volumeName: s3_vol
      volumes:
        - name: s3_vol
          path: data/
          endpoint: https://endpoint.mycompany.com
          secretRef: s3-secret-data
```
**Reproduction/Testing steps**
see above 

**suggestion**
I saw that the [Clustermanager smartstore config](https://github.com/splunk/splunk-operator/blob/main/helm-chart/splunk-enterprise/templates/enterprise_v4_clustermanager.yaml#L16-L19) differs from[ the standalone configs](https://github.com/splunk/splunk-operator/blob/main/helm-chart/splunk-enterprise/templates/enterprise_v4_standalone.yaml#L21-L24). 

I just copied the CM configs into the Standalone configs and it worked.
