### ISSUE TITLE
Monitoring Console: Keep restarting 

### ISSUE THREAD

**Issue by Sinamcp** [splunk/splunk-operator#1080]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
- Ansible for  monitoring console failed at dmc_asset_build_full - POST task

**Splunk setup on K8S**
- openshift 4.10

I deployed monitoring console with the following manifest(like doc)

```yaml
apiVersion: enterprise.splunk.com/v4
kind: MonitoringConsole
metadata:
  name: mc-test
  namespace: default
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterManagerRef:
    name: cm-test
  etcVolumeStorageConfig:
    storageCapacity: 2Gi
  varVolumeStorageConfig:
    storageCapacity: 5Gi
```
after applying the manifest, monitoring console pod start ansible, but it fails with the below error

```yaml
TASK [splunk_monitor : dmc_asset_build_full - POST] ****************************
fatal: [localhost]: FAILED! => {
    "cache_control": "no-store, no-cache, must-revalidate, max-age=0",
    "changed": false,
    "connection": "Close",
    "content_length": "360",
    "content_type": "text/xml; charset=UTF-8",
    "date": "Sat, 18 Feb 2023 12:26:24 GMT",
    "elapsed": 0,
    "expires": "Thu, 26 Oct 1978 00:00:00 GMT",
    "redirected": false,
    "server": "Splunkd",
    "status": 503,
    "url": "https://127.0.0.1:8089/servicesNS/nobody/splunk_monitoring_console/saved/searches/DMC%20Asset%20-%20Build%20Full/dispatch",
    "vary": "Cookie, Authorization",
    "x_content_type_options": "nosniff",
    "x_frame_options": "SAMEORIGIN"
}

MSG:

Status code was 503 and not [200, 201, 409]: HTTP Error 503: Service Unavailable

```
