### ISSUE TITLE
Secret Management: Pod logs are logging sensitive information like passwords.

### ISSUE THREAD

**Issue by saikalyan551** [splunk/splunk-operator#1082]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
- I have deployed Splunk Enterprise using Helm Charts and for LDAP authentication, I used secrets to deploy it and mount it to pod, but when I checked the logs for Standalone, it appears that Ansible is logging senstive information like bind password, which is not desired.

Example log from the pod:
```
TASK [splunk_common : Set options in ldapstrategy] *****************************
ok: [localhost] => (item={'key': 'SSLEnabled', 'value': 0})
ok: [localhost] => (item={'key': 'bindDN', 'value': 'ldapuser@test.io'})
changed: [localhost] => (item={'key': 'bindDNpassword', 'value': '<sensitive info>'})
ok: [localhost] => (item={'key': 'groupBaseDN', 'value': 'cn=developer_dt1,ou=aaddc users,dc=aadds,dc=test,dc=io'})
ok: [localhost] => (item={'key': 'groupMappingAttribute', 'value': 'dn'})
```

**Expected behavior**
- Any change which make sure sensitive info is redacted or not shown in logs.

**Reproduction/Testing steps**

```
splunk:
   conf:
   - key: authentication
     value:
        directory: /opt/splunk/etc/system/local
        content:
          authentication:
            authSettings: ldapstrategy
            authType: LDAP
          ldapstrategy:
            SSLEnabled: 0
            bindDN: ldapuser@test.io
            bindDNpassword: <password>
            groupBaseDN: cn=operator_dt1,ou=aaddc users,dc=aadds,dc=test,dc=io
            groupMappingAttribute: dn
```
Then create a secret out of this file
`kubectl create secret generic splunk-ldap-secret --from-file=default.yml=value.txt`

Then I started up a single instance Splunk pointing to this secret

```
cat <<EOF | kubectl apply -f -
apiVersion: enterprise.splunk.com/v2
kind: Standalone
metadata:
  name: s1
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  volumes:
    - name: default
      secret:
        secretName: splunk-ldap-secret
  defaultsUrl: /mnt/default/default.yml
EOF
```

logs

```
SDL-C02DV54YMD6M:splunk svytla$ kubectl logs splunk-s1-standalone-0 -n splunk-operator
WARNING: No password ENV var.  Stack may fail to provision if splunk.password is not set in ENV or a default.yml
[DEPRECATION WARNING]: ALLOW_WORLD_READABLE_TMPFILES option, moved to a per 
plugin approach that is more flexible, use mostly the same config will work, 
but now controlled from the plugin itself and not using the general constant. 
instead. This feature will be removed from ansible-base in version 2.14. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.

PLAY [Run default Splunk provisioning] *****************************************
Wednesday 22 February 2023  04:29:05 +0000 (0:00:00.126)       0:00:00.126 **** 

TASK [Gathering Facts] *********************************************************
ok: [localhost]
Wednesday 22 February 2023  04:29:06 +0000 (0:00:00.927)       0:00:01.053 **** 
Wednesday 22 February 2023  04:29:06 +0000 (0:00:00.041)       0:00:01.094 **** 
Wednesday 22 February 2023  04:29:06 +0000 (0:00:00.109)       0:00:01.204 **** 
included: /opt/ansible/roles/splunk_common/tasks/get_facts.yml for localhost

```
