### ISSUE TITLE
SHC Member container failed startup probe, will be restarted 

### ISSUE THREAD

**Issue by markusspitzli** [splunk/splunk-operator#1083]
### Please select the type of request

Enhancement

### Tell us more

**Describe the request**
We are facing the issue that the startup probe kills the SHC member because it takes to long to startup. 

The message we get on kubernetes:
```
Container splunk failed startup probe, will be restarted
```

In the values file of splunk enterprise, setting the startup probe is not supported:
https://github.com/splunk/splunk-operator/blob/main/helm-chart/splunk-enterprise/values.yaml#L330-L332

Usually the startup takes very long for a SHC Member, why the startup probe easily triggers the restart of the pod:
```
===============================================================================
splunk_common : Restart the splunkd service - Via CLI ----------------- 155.07s
splunk_common : Restart the splunkd service - Via CLI ----------------- 151.12s
splunk_common : Start Splunk via CLI ----------------------------------- 21.81s
splunk_common : Get Splunk status --------------------------------------- 7.48s
splunk_search_head : Boostrap SHC captain ------------------------------- 3.38s
splunk_common : Set node as license slave ------------------------------- 1.58s
splunk_search_head : Initialize SHC cluster config ---------------------- 1.47s
Gathering Facts --------------------------------------------------------- 1.44s
splunk_search_head : Peer cluster master -------------------------------- 1.41s
splunk_common : Test basic https endpoint ------------------------------- 1.13s
splunk_common : Setup indexer discovery for index-clustering ------------ 1.13s
splunk_search_head : Set desired preferred captaincy -------------------- 1.03s
splunk_common : Set options in saml ------------------------------------- 1.03s
splunk_common : Cleanup Splunk runtime files ---------------------------- 1.02s
splunk_common : Setup default tcpout group for index-clustering --------- 1.00s
splunk_search_head : Check Splunk instance is running ------------------- 0.96s
splunk_common : Check Splunk instance is running ------------------------ 0.94s
splunk_common : Apply admin password ------------------------------------ 0.94s
splunk_search_head : Check Splunk instance is running ------------------- 0.91s
Check for required restarts --------------------------------------------- 0.88s
Stopping splunkd...
Shutting down.  Please wait, as this may take a few minutes.

```

**Expected behavior**
it should be possible to customize the startup probe 

**Splunk setup on K8S**
As for the splunk operator we used 2.1.1 and 2.2.0

When setting up the Clustered Environment, we used the following value file for the splunk-enterprise helm chart:
```

splunk-enterprise:
  splunk-operator:
    enabled: false

  sva:
    c3:
    enabled: true
    indexerClusters:
    - name: idx1
    searchHeadClusters:
    - name: shc1

  licenseManager:
    enabled: true
    volumes:
      - name: licenses
        configMap:
          name: splunk-licenses
    licenseUrl: /mnt/licenses/licenses.lic

  clusterManager:
    appRepo:
      appsRepoPollIntervalSeconds: 600
      defaults:
        volumeName: volume_app_repo
        scope: cluster
      appSources:
        # ==> replace NAMESPACE <==
        - name: cluster
          location: myinstance/ClusterMaster/cluster/
        - name: local
          location: myinstance/ClusterMaster/local/
          scope: local
      volumes:
        - name: volume_app_repo
          storageType: s3
          provider: minio
          path: apps/
          endpoint: https://endpoints3.mycompany.com
          secretRef: s3-secret-apps
    smartstore:
      defaults:
        volumeName: s2s3_vol
      # ==> define indexes if needed <==
      # indexes:
        # - name: mytest
        #   remotePath: $_index_name
        #   volumeName: s2s3_vol
      volumes:
        - name: s2s3_vol
          path: data/
          endpoint: https://endpoints3.mycompany.com
          secretRef: s3-secret-data
      cacheManager:
        hotlistBloomFilterRecencyHours: 360 # 15 days - splunk defaults - (can be lowered to 5 days)
        hotlistRecencySecs: 86400           # 24 hours - splunk defaults
        evictionPadding: 1024               # 1Gi
        evictionPolicy: lru                 # splunk defaults
        maxCacheSize: 0                     # Eviction will be based on the sum of 'minFreeSpace (5Gi)' and 'eviction_padding'
        maxConcurrentDownloads: 8           # splunk defaults
        maxConcurrentUploads: 8             # splunk defaults

  searchHeadCluster:
    appRepo:
      appsRepoPollIntervalSeconds: 600
      defaults:
        volumeName: volume_app_repo
        scope: cluster
      appSources:
        # ==> replace NAMESPACE <==
        - name: cluster
          location: myinstance/SearchHeadCluster/cluster/
        - name: local
          location: myinstance/SearchHeadCluster/local/
          scope: local
      volumes:
        - name: volume_app_repo
          storageType: s3
          provider: minio
          path: apps/
          endpoint: https://endpoints3.mycompany.com
          secretRef: s3-secret-apps
    volumes:
      - name: splunk-defaults-searchheads
        configMap:
          name: splunk-defaults-searchheads
    defaultsUrl: "/mnt/splunk-defaults-searchheads/splunk-defaults-searchheads.yaml"

  indexerCluster:
    volumes:
    - name: splunk-defaults-indexers
      configMap:
        name: splunk-defaults-indexers
    defaultsUrl: "/mnt/splunk-defaults-indexers/splunk-defaults-indexers.yaml"
``` 

- Details of the Splunk setup on the K8s cluster.
