### ISSUE TITLE
Cluster Master needs separate storage class than Indexers

### ISSUE THREAD

**Issue by crawdaddy18** [splunk/splunk-operator#110]
I need to be able to overwrite or otherwise assign a different storage class to the Cluster Master.  Currently, the CM inherits the settings used for the Indexers.

In my install, I am using OpenEBS for the indexers to take advantage of local storage, however, I need to persist data for the CM and OpenEBS is not the right choice for that if the node where CM is running fails.

Please LMK if this setting can be overwritten in a manifest or if a change can be made to the SOK and the operator recompiled.

#A380

**Comment by gaurav-splunk** [comment]
Hi @crawdaddy18, this is definitely possible. We recently merged a [PR](https://github.com/splunk/splunk-operator/pull/99), where you can have a separate CR for CM other than indexers. In CR for CM, you have to specify `replicas:0` and in the CR for indexers, you have to refer to CM using section `indexerClusterRef` which points to the name you give in the CR for CM. This way you can have a configuration/storage class for CM which is different from indexers.
A simple example would look something like this - 
CR for ClusterMaster -
```apiVersion: enterprise.splunk.com/v1alpha3
kind: IndexerCluster
metadata:
  name: cm
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  replicas: 0
```
And a CR for indexers would look something like this - 
```apiVersion: enterprise.splunk.com/v1alpha3
kind: IndexerCluster
metadata:
  name: idxc
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  replicas: 2
  indexerClusterRef:
    name: cm
```

That being said, we are working on a story where we will have a separate CRD for ClusterMaster to make it more explicit and then we don't have to use `replicas:0` as method to denote spec for CM.

**Comment by crawdaddy18** [comment]
Thank you @gaurav-splunk is this the output you'd expect? (the second container is an ISTIO sidecar)
```
splunk-cm-cluster-master-0        2/2     Running   0          2m33s
splunk-cm-indexer-0               2/2     Running   0          2m33s
splunk-idxc-cluster-master-0      2/2     Running   0          2m22s
splunk-idxc-indexer-0             2/2     Running   0          2m22s
splunk-idxc-indexer-1             2/2     Running   0          2m12s
```
manifest:
```
apiVersion: enterprise.splunk.com/v1alpha2
kind: IndexerCluster
metadata:
  name: cm
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  replicas: 0
  spec:
  storageClassName: "mapr-nfscsi"
---
apiVersion: enterprise.splunk.com/v1alpha2
kind: IndexerCluster
metadata:
  name: idxc
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
spec:
  storageClassName: "openebs-hostpath"
  replicas: 2
  indexerClusterRef:
    name: cm
```

How does Splunk know to use the CM using "mapr-nfscsi" but the indexers for "openebs-hostpath"?
