### ISSUE TITLE
Splunk Operator: helm chart splunk/splunk-enterprise - indexercluster - clusterManagerRef does not work

### ISSUE THREAD

**Issue by gjanders** [splunk/splunk-operator#1102]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
In the helm chart for an indexerCluster I have a clusterManagerRef:
```
indexerCluster:
  enabled: true
<cut>
  clusterManagerRef:
    name: mobiles-cm
```

However this does not become part of the indexercluster CRD when the helm chart is installed and therefore the indexer cluster of a multisite indexer cluster refuses to start

**Expected behavior**
If I now run:
kubectl edit indexercluster <clustername>

Under spec I expect:
```
  clusterManagerRef:
    name: mobiles-cm

```

However this does not appear and therefore the indexer cluster stays in "pending" status

**Splunk setup on K8S**
Multi-site indexer cluster using helm charts, I'm attempting to configure 1 site of the indexer cluster (either site fails)

**Reproduction/Testing steps**
As per details

**K8s environment**
Tested on k8s 1.2.21, Splunk operator 2.2.0 and the current Helm chart as of 6th March 2023

**Proposed changes(optional)**
Allow clusterManagerRef, otherwise I have to complete a manual edit *after* the helm install runs to get the indexer cluster to run!

**K8s collector data(optional)**
Let me know if you need this...

**Additional context(optional)**
Happy for questions...or a discussion on slack

**Comment by vivekr-splunk** [comment]
@gjanders thanks for raising this issue. I am looking into this issue now. will update you once I am done with my investigation.

**Comment by vivekr-splunk** [comment]
@gjanders can you give provide the chart values you setup for multisite ? are you using`sva` `m4` ?

**Comment by gjanders** [comment]
```
splunk-operator:
  enabled: false

indexerCluster:
  enabled: true
  name: mobiles-idxc-site2
  #replicaCount: 20
  replicaCount: 2
  etcVolumeStorageConfig:
    ephemeralStorage: false
    storageCapacity: 5Gi
  # storageClassName: gp2

  varVolumeStorageConfig:
    ephemeralStorage: false
    storageCapacity: 1000Gi
  # storageClassName: gp2
  resources:
     requests:
       memory: "40Gi"
       cpu: "20"
     limits:
       memory: "62Gi"
       cpu: "32"
  clusterManagerRef:
    name: mobiles-cm
  defaults:
    splunk:
      multisite_master: splunk-mobiles-cm-cluster-manager-service
      site: site2
  affinity:
    ## Example: schedule Splunk instance pod on a node in zone-1a
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: mobile-iot-site
            operator: In
            values:
            - "2"

```

**Comment by rlieberman-splunk** [comment]
@gjanders Our splunk/splunk-enterprise helm chart includes a field called existingClusterManager, where you can set the name and namespace https://github.com/splunk/splunk-operator/blob/main/helm-chart/splunk-enterprise/values.yaml#L63. In your helm chart, please try
```
splunk-operator:
  enabled: false

existingClusterManager:
  name: mobiles-cm

indexerCluster:
  enabled: true
  ...
```

This should set `clusterManagerRef` in the chart to the value of `existingClusterManager.name`. Please let us know if this works and we can close this issue.

**Comment by gjanders** [comment]
I have not tried existingClusterManager, I'll try to test that tomorrow.

**Comment by gjanders** [comment]
I've run a quick test but it hasn't worked yet...I suspect this is because the dev environment has an issue. 
I'll re-test once it comes online...

**Comment by gjanders** [comment]
No change in my testing, on operator 2.8.0, the "PHASE" remains blank until I manually add a clusterManagerRef

Example snippet from helm file:
```
indexerCluster:
  enabled: true
  name: test-idxc-site1
  namespace: splunk-test-cluster
  replicaCount: 2
  etcVolumeStorageConfig:
    ephemeralStorage: false
    storageCapacity: 5Gi
    storageClassName: local-storage-etc
  # storageClassName: gp2

  varVolumeStorageConfig:
    ephemeralStorage: false
    storageCapacity: 5000Gi
    storageClassName: local-storage-var
  # storageClassName: gp2
  resources:
     requests:
       memory: "10Gi"
       cpu: "2"
     limits:
       memory: "10Gi"
       cpu: "4"
  startupProbe:
    timeoutSeconds: 30
    periodSeconds: 30
    failureThreshold: 40
    # default 12
  livenessProbe:
    failureThreshold: 30
  existingClusterManager:
     name: test-cm
  #clusterManagerRef:
  #   name: test-cm
```
