### ISSUE TITLE
App Framework: Add support for adding additional labels to the Splunk-operator Helm chart

### ISSUE THREAD

**Issue by saikalyan551** [splunk/splunk-operator#1116]
### Please select the type of request

Enhancement

### Tell us more

**Describe the request**

I am currently conducting a POC using the Splunk Operator Helm Chart to deploy a Splunk app using managed identity from Azure Blob Storage to a standalone application and I see a small issue.

In our current step, we use the [AAD Pod-managed Identity](https://learn.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity) approach to create Azure Identity and Azure Identity bind in order to provide access to Azure resources to our pods. So, to use this approach, we need to assign [aadpodidbinding label](https://learn.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity#run-a-sample-application) to a pod, but [splunk-operator helm chart](https://github.com/splunk/splunk-operator/tree/main/helm-chart/splunk-operator) does not allow us to pass external labels but instead use [pre-defined labels](https://github.com/splunk/splunk-operator/blob/7bbc4647348bd16ef23a544b25c1ef43ecfbd538/helm-chart/splunk-operator/templates/deployment.yaml#L26).

So, if we can tweak splunk operator helm chart to support additional labels similar to [splunk-enterprise](https://github.com/splunk/splunk-operator/blob/7bbc4647348bd16ef23a544b25c1ef43ecfbd538/helm-chart/splunk-enterprise/values.yaml#L93) helm chart, then I can use aad pod binding approach. I know there is another way to access the blob using managed identity, as described in this [document](https://github.com/splunk/splunk-operator/blob/main/docs/AppFramework.md#setup-azure-bob-access-with-managed-indentity) but this simplifies things even further for us and also give us a chance to give more granular access (i.e only splunk-operator pod have the access). Let me know if there are any concerns.

As a test, I edited the splunk-operator-controller-manager pod and added the label, and splunk-operator was able to access the Azure storage account and deploy the Splunk app.

```
apiVersion: v1
kind: Pod
metadata:
  name: splunk-operator-controller-manager-5f97bdd6bd-lwnrv
  generateName: splunk-operator-controller-manager-5f97bdd6bd-
  namespace: splunk-operator
  labels:
    aadpodidbinding: axonsplunk-dt1
    app.kubernetes.io/instance: splunk-operator
    app.kubernetes.io/name: splunk-operator
    control-plane: controller-manager
    pod-template-hash: 5f97bdd6bd
```
label: **aadpodidbinding: axonsplunk-dt1**

Standalone:
```
apiVersion: enterprise.splunk.com/v4
kind: Standalone
metadata:
  name: stdln
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  replicas: 1
  appRepo:
    appsRepoPollIntervalSeconds: 600
    defaults:
      volumeName: volume_app_repo_us
      scope: local
    appSources:
      - name: networkApps
        location: splunk-dt1/
    volumes:
      - name: volume_app_repo_us
        storageType: blob
        provider: azure
        path: splunk-app/splunk-app-framework/
        endpoint: ***********************
```

**Expected behavior**
- [Splunk-operator](https://github.com/splunk/splunk-operator/tree/main/helm-chart/splunk-operator) helm chart has support to add additional labels.

**Splunk setup on K8S**
- AKS Cluster

**Comment by vivekr-splunk** [comment]
@saikalyan551 thanks you for raising this issue. you are right we should do add this. I will work on this and let you know.

**Comment by gburton1** [comment]
@vivekr-splunk any update on this?

**Comment by vivekr-splunk** [comment]
Hi @saikalyan551 have you tried using `labels` and `annotations` fields.   I see the operator has those fields 

```
  labels:
{{- include "splunk-operator.labels" . | nindent 4 }}
{{- if .Values.splunkOperator.annotations }}
  annotations:
{{ toYaml .Values.splunkOperator.annotations | nindent 4 }}
{{- end }}
```

**Comment by vivekr-splunk** [comment]
Hi @saikalyan551 I have added labels to splunk-operator and tested it . it works fine now. annotations are already supported. this should be in next upcoming release. 
here is the example values.yaml file
```
>helm install splunk-c3 splunk/splunk-enterprise -f c3_config.yaml --set splunk-operator.splunkOperator.image.repository=docker.io/splunk/splunk-operator:2.3.0 --set splunk-operator.image.repository=docker.io/splunk/splunk:9.0.5 --namespace test
```

```
splunk-operator:
  enabled: true
  splunkOperator:
    clusterWideAccess: false
    annotations:
      annotation: "true"
    labels:
      testing: "true"

sva:
    c3:
      enabled: true

      clusterManager:
        name: cm

      indexerClusters:
        - name: idxc

      searchHeadClusters:
        - name: shc


indexerCluster:
  enabled: true

  additionalLabels:
    label: "true"

  additionalAnnotations:
    annotation: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"

  serviceTemplate:
    spec:
      type: LoadBalancer

clusterManager:
  enabled: true

  additionalLabels:
    label: "true"

  additionalAnnotations:
    annotation: "true"

searchHeadCluster:
  enabled: true

  additionalLabels:
    label: "true"

  additionalAnnotations:
    annotation: "true"

```
