### ISSUE TITLE
Splunk Operator: Helm Install 2.2.1 fails at <.zone>: can't evaluate field zone in type int

### ISSUE THREAD

**Issue by sweinbrenner** [splunk/splunk-operator#1129]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
Install of Splunk Enterprise via helm chart to AWS EKS. Following guide: https://splunk.github.io/splunk-operator/Helm.html

Splunk operator is able to install with defaults. Installing splunk-enterprise yields the following bug:

```
helm install -f nv.yaml splunk-enterprise-test1 splunk/splunk-enterprise -n splunk-operator
Error: INSTALLATION FAILED: template: splunk-enterprise/templates/enterprise_v4_searchheadcluster.yaml:157:42: executing "splunk-enterprise/templates/enterprise_v4_searchheadcluster.yaml" at <.zone>: can't evaluate field zone in type int
```

nv.yaml contents:
```
splunk-operator:
  enabled: false

clusterMaster:
  enabled: true
  name: cm-test

indexerCluster:
  enabled: true
  name: idxc-test

searchHeadCluster:
  enabled: true
  name: shc-test
```

**Expected behavior**
splunk-enterprise should install the desired enteprise feature set with cluster master indexer and search head

**Splunk setup on K8S**
operator+enterprise

**Reproduction/Testing steps**
helm install with default values including clustermaster, indexer, searchhead

**K8s environment**
- Useful information about the K8S environment being used. Eg. version of K8s, kind of K8s cluster etc..

**Proposed changes(optional)**
- possible bug introduced in 2.2.1 for <.zone> type int
