### ISSUE TITLE
Splunk Operator: uninstalling splunk/splunk-enterprise via helm leaves the k8s statefulset

### ISSUE THREAD

**Issue by gjanders** [splunk/splunk-operator#1130]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
- When I run the helm uninstall ... -n mobiles I see that the pods remain running, and even though the "clustermanager" no longer exists, the statefulset creating the cluster manager pods exist.
So I have to manually remove the statefulset to remove the pods, rather than let the clustermanager CRD do this for me

**Expected behavior**
- When I helm uninstall the cluster manager I expect the k8s statefulset to also be deleted

**Splunk setup on K8S**
helm overrides:
```
splunk-operator:
  enabled: false

clusterManager:
  enabled: true
  name: mobiles-cm
  # Splunk Enterprise App repository
  # Specifies remote App location and scope for Splunk App management
  # reference: https://github.com/splunk/splunk-operator/blob/develop/docs/AppFramework.md
  appRepo:
     appsRepoPollIntervalSeconds: 900
     defaults:
       volumeName: volume_app_repo_us
       scope: cluster
     appSources:
       - name: clusterApps
         location: clusterApps/
       - name: adminApps
         location: adminApps/
         scope: local
     volumes:
       - name: volume_app_repo_us
         storageType: s3
         provider: minio
         path: k8s_mobile-iot-idx-config/
         endpoint: https://localhost
         region: us-west-2
         secretRef: mobile-iot-s3-secret

  # Full path or URL for a Splunk Enterprise license file
  # Ignore if deploying a license manager instance

  # Specify Splunk default.yaml to override intial environment config
  defaults:
    ## Example: Deploy a multi-site cluster manager
    splunk:
      site: site1
      multisite_master: localhost
      all_sites: site1,site2
      multisite_replication_factor_origin: 2
      multisite_replication_factor_total: 3
      multisite_search_factor_origin: 2
      multisite_search_factor_total: 3
      pass4SymmKey: changeit
      idxc:
        label: mobiles_k8s_idx_cluster
        search_factor: 3
        replication_factor: 3

  serviceTemplate:
    spec:
      ports:
      - name: https-web2
        port: 8001
        protocol: TCP
        targetPort: 8001

  # Set resource requests and limits for Splunk instance pod containers
  # reference: https://github.com/splunk/splunk-operator/blob/develop/docs/CustomResources.md#examples-of-guaranteed-and-burstable-qos
  # Define affinity scheduling rules
  # reference: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#affinity-v1-core
  affinity:
    ## Example: schedule Splunk instance pod on a node in zone-1a
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: mobile-iot
            operator: Exists
```

**Reproduction/Testing steps**
- Install clustermanager via helm install command, wait for everything to create
- Uninstall clustermanager via helm uninstall command
- kubectl get statefulset -n mobiles
- kubectl get pods -n mobiles

Will show that the pods and statefulset remain for the cluster manager
Note I did have indexer clusters as well, unsure if that influences the removal of the statefulset of the clustermanager

**K8s environment**
On-prem, 1.23.1
