### ISSUE TITLE
Splunk Operator: ServiceAccountName not used

### ISSUE THREAD

**Issue by nathan-bowman** [splunk/splunk-operator#1134]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
I can't seem to get the `splunk-operator` to pick up my serviceaccount.

**Expected behavior**
I expect the serviceaccount to be used when values.yaml is:
```yaml
splunk-operator:
  enabled: true
  operator:
    serviceAccountName: "splunk-enterprise-serviceaccount-staging"

splunk-enterprise:
  sva:
    c3:
      enabled: true
...
```

Unless I'm mistaken, the `splunk-operator` should apply my serviceaccount here: https://github.com/splunk/splunk-operator/blob/7b9e4cc7e4ca3cfe2c54134621446d6b9687a856/helm-chart/splunk-operator/templates/serviceaccount.yaml#L4 

`splunk-enterprise` Chart.yaml:
```yaml
---
apiVersion: v2
name: splunk-enterprise
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: splunk-enterprise
  version: 2.2.1
  repository: https://splunk.github.io/splunk-operator/
```

I'm on ArgoCD, so I'm not sure if that is causing an issue with the Helm chart.
