### ISSUE TITLE
Default.yml for searchHeadClusters affects Searchhead Deployer Defaults

### ISSUE THREAD

**Issue by markusspitzli** [splunk/splunk-operator#1138]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
Setting searchHeadClusters defaults with the helm parameter [`defaultsUrl`](https://github.com/splunk/splunk-operator/blob/main/helm-chart/splunk-enterprise/values.yaml#L393) shouldn't affect the defaults of the Searchhead Deployer. 

**Expected behavior**
It should be possible to define separated defaults.yml for Searchhead Cluster members and the Searchhead deployer

**Splunk setup on K8S**
Setting up a standard C3 clustered environment with helm.

searchHeadCluster from helm values
```
searchHeadCluster:
    volumes:
      - name: splunk-defaults-searchheads
        configMap:
          name: splunk-defaults-searchheads
    defaultsUrl: "/mnt/splunk-defaults-searchheads/splunk-defaults-searchheads.yaml"
```
splunk-defaults-searchheads.yml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: splunk-defaults-searchheads
  namespace: mynamespace
data:
  splunk-defaults-searchheads.yaml: |
    splunk:
      http_enableSSL: true
      http_enableSSL_cert: /opt/splunk/etc/shcluster/apps/myapp/auth/cert.pem
      http_enableSSL_privKey: /opt/splunk/etc/shcluster/apps/myapp/auth/cert.key
```

**Reproduction/Testing steps**
The above configuration (splunk-defaults-searchheads) will break the Web from the Searchhead deployer, because the apps are differently deployed on the deployer than the searchheadcluster members.  The DP installs the app in  /opt/splunk/etc/apps whereas the SHC members use the shcluster path configured as above. 

**Proposed changes(optional)**
Distinguish between SHCluster Members and SH Deployer.
