### ISSUE TITLE
Splunk Operator: ansible script getting stuck at task [splunk_common : Check if /sbin/updateetc.sh exists]

### ISSUE THREAD

**Issue by OsamaKhan220** [splunk/splunk-operator#1149]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
- operator is installed on Openshift 4.12.x, when creating standalone instance ansible script is getting stuck at task: `check if update-etc exsists`
```
TASK [splunk_common : Check if /sbin/updateetc.sh exists] **********************
[0;32mok: [localhost][0m
Tuesday 25 April 2023  12:38:15 +0000 (0:00:01.844)       0:00:31.256 ********* 
```

**Reproduction/Testing steps**
- installed splunk operator with 
```
kubectl apply -f https://github.com/splunk/splunk-operator/releases/download/2.2.1/splunk-operator-cluster.yaml
```

- creating standalone instance with this snapshot
```
cat <<EOF | kubectl apply -n splunk-operator -f -
apiVersion: enterprise.splunk.com/v4
kind: Standalone
metadata:
  name: s1
  finalizers:
  - enterprise.splunk.com/delete-pvc
EOF
```
**K8s environment**
- K8s version v1.25.x, Splunk operator 2.2.0 and Openshift version 4.12.x
