### ISSUE TITLE
Monitoring Console: Password must be set in order to use defaults field in CR 

### ISSUE THREAD

**Issue by m5lapp** [splunk/splunk-operator#1156]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
We have been trying to deploy a Monitoring Console using the Splunk Operator v2.2.1 and found that when we specify values in the .spec.defaults field, then it fails to start up unless we also specify the .splunk.password value in the defaults field with the password set to the same value as in the splunk-[NAMESPACE]-secret Secret.

When the password is not specified manually in the field, the Pod gets stuck at the following stage:

```
TASK [splunk_monitor : Fetch server info] **************************************
ok: [localhost]
Wednesday 03 May 2023  09:38:20 +0000 (0:00:00.616)       0:01:20.171 ********* 
FAILED - RETRYING: Fetch distributed peers (60 retries left).
FAILED - RETRYING: Fetch distributed peers (59 retries left).
FAILED - RETRYING: Fetch distributed peers (58 retries left).
FAILED - RETRYING: Fetch distributed peers (57 retries left).
FAILED - RETRYING: Fetch distributed peers (56 retries left).
...
```

**Expected behavior**
We would expect to not have to manually duplicate the password from the splunk-[NAMESPACE]-secret Secret in the defaults field for the Monitoring Console.

**Splunk setup on K8S**
We are deploying a Monitoring Console with the following defaults configuration:

```
apiVersion:  enterprise.splunk.com/v4
kind: MonitoringConsole
metadata:
  name: test
  namespace: ops
  labels:
    app: splunk-monitoring-console
spec:
  defaults: |-
    splunk:
      conf:
      - key: splunk_monitoring_console_assets
        value:
          directory: /opt/splunk/etc/apps/splunk_monitoring_console/local
          content:
            settings:
              mc_auto_config: enabled
              disabled: 0
              configuredPeers: 'server1:8089,server2:8089'
      - key: distsearch
        value:
          directory: /opt/splunk/etc/apps/ukiss_splunk_peers/local
          content:
            distributedSearch:
              servers: 'https://server1:8089,https://server2:8089'
            distributedSearch:dmc_group_indexer:
              default: true
              servers: server1:8089,server2:8089
            distributedSearch:dmc_group_license_master:
              servers: splunk-lm-license-manager-service.ops.svc.cluster.local:8089
```

**Reproduction/Testing steps**
Deploy a Monitoring Console with the above configuration, the deployment will get stuck at the Fetch distributed peers stage. If you then get the password from the splunk-[NAMESPACE]-secret Secret and add it in to the defaults field under splunk.password and redeploy, then it will work.

**K8s environment**
Kubernetes version v1.21.13
