### ISSUE TITLE
Splunk Operator: Unable to add Resource Requests or storageClassName to Volume

### ISSUE THREAD

**Issue by Astroknut** [splunk/splunk-operator#1161]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
- When adding resource request and/or storageClassName to https://github.com/splunk/splunk-operator/blob/2.2.1/helm-chart/splunk-operator/templates/app_download.yaml, apply fail due to volume value reference in the Deployment: https://github.com/splunk/splunk-operator/blob/2.2.1/helm-chart/splunk-operator/templates/deployment.yaml#L111-L113 with the following error:
`error calculating structured merge diff: error building typed value from config resource: .spec.template.spec.volumes[name="app-staging"].storageClassName: field not declared in schema`

**Expected behavior**
- Ability to add both resource requests and storageClassName for volumes. 

**Splunk setup on K8S**
- Values:
```          
volumes:
  - name: app-staging
    storageClassName: azure-disk-csi
    persistentVolumeClaim:
      claimName: splunk-operator-app-download-csi
      resources:
        requests:
          storage: 32Gi
```                    

**Reproduction/Testing steps**
- Add either resource requests for storage or a storageClassName value

**K8s environment**
- v1.24 on AKS

**Proposed changes(optional)**
- Proposed change, if any.

**K8s collector data(optional)**
- Please provide data collected from the [K8s collectors](https://github.com/splunk/splunk-operator/blob/develop/docs/K8SCollectors.md), if any.

**Additional context(optional)**
- Add any other context about the problem here.
