### ISSUE TITLE
Splunk Operator: examples hwf.yaml and hwf_azure_blob.yaml have incorrect indentation for replicas parameter

### ISSUE THREAD

**Issue by firebus** [splunk/splunk-operator#1221]
### Please select the type of request

Bug

### Tell us more

In hwf.yaml for example:

```
spec:
  clusterManagerRef:
    name: cm-example
  licenseManagerRef:
    name: lm-example
    replicas: 1
  appRepo:
```

However replicas is a child of spec, not a child of licenseManagerRef, so it is indented one level too deep.
