### ISSUE TITLE
App Framework: 

### ISSUE THREAD

**Issue by mvleandro** [splunk/splunk-operator#1255]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
- AppFramework can't authenticate in aws.

**Expected behavior**
- After configuring AppFramework, I'm getting this log message: 
```
splunk-operator-controller-manager-57c8db67c8-b8j2r manager 2023-11-30T11:37:56.6363531Z	ERROR	GetAppListFromRemoteBucket	Unable to get apps list	{"controller": "searchheadcluster", "controllerGroup": "enterprise.splunk.com", "controllerKind": "SearchHeadCluster", "SearchHeadCluster": {"name":"shc1","namespace":"splunk"}, "namespace": "splunk", "name": "shc1", "reconcileID": "12522428-7a4d-44fc-a182-65a7869dff03", "name": "shc1", "namespace": "splunk", "appSource": "adminApps", "error": "RequestError: send request failed\ncaused by: Get \"https://my-splunk-apps.s3-us-east-1.amazonaws.com/?delimiter=%2F&list-type=2&max-keys=4000&prefix=adminAppsLoc%2F&start-after=adminAppsLoc%2F\": net/http: invalid header field value for \"Authorization\""}
```
I already checked that I have enough privileges and tested it.
Bellow you can see the SearchHeadCluster configuration regarding AppFramework
```yaml
    appRepo:
      appsRepoPollIntervalSeconds: 900
      defaults:
        volumeName: volume_app_repo
        scope: cluster
      appSources:
        - name: searchApps
          location: searchAppsLoc/
        - name: adminApps
          location: adminAppsLoc/
          scope: local
      volumes:
        - name: volume_app_repo
          region: us-east-1
          storageType: s3
          provider: aws
          path: my-splunk-apps/
          endpoint: https://s3-us-east-1.amazonaws.com
          secretRef: aws-s3-secret  
```

**Splunk setup on K8S**
- I'm using Splunk Operator 2.3.1

**Reproduction/Testing steps**
- After applying the changes on SearchHeadCluster CRD I'm restarting the splunk-operator pod.

**K8s environment**
- It's a K8S v1.21.14 on-premisse cluster.
