### ISSUE TITLE
Splunk Operator: indexers don't start with 9.1.2

### ISSUE THREAD

**Issue by yaroslav-nakonechnikov** [splunk/splunk-operator#1260]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
All nodes starting as expected, but only indexers can't 

**Expected behavior**
all works as it was

**Splunk setup on K8S**
eks 

**Reproduction/Testing steps**
* start cluster with 9.1.1
and then replace splunk image with 9.1.2
* or just try to start cluster with 9.1.2

**K8s environment**
1.28

**Additional context(optional)**
* reported to [docker-splunk]
](https://github.com/splunk/docker-splunk/issues/633)
* reported to splunk directly in case: 3366553

**Comment by yaroslav-nakonechnikov** [comment]
so, after several tests i can give what breaks.

in cluster manager definition we had that:
```
 smartstore:
    defaults:
      maxGlobalDataSizeMB: 0
      maxGlobalRawDataSizeMB: 0
      volumeName: smartstore
    indexes:
    - hotlistBloomFilterRecencyHours: 1
      hotlistRecencySecs: 3600
      name: tf-test
      remotePath: tf-test/
      volumeName: smartstore
    volumes:
    - endpoint: https://s3-eu-central-1.amazonaws.com
      name: smartstore
      path: bucket-for-smart-store
      provider: aws
      region: eu-central-1
      storageType: s3
```

and when we removed that block and recreated cm and indexers - all started to work.
