### ISSUE TITLE
Splunk Operator: add scale subresource

### ISSUE THREAD

**Issue by yaroslav-nakonechnikov** [splunk/splunk-operator#1272]
### Please select the type of request

Feature Request

### Tell us more

**Describe the request**
In order to start using keda (https://keda.sh/docs/2.11/concepts/scaling-deployments/#scaling-of-custom-resources), which will help a lot for testing/development stack, need to add support for https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource 

**Expected behavior**
scale subresource added and it is possible to use keda natively

**Comment by akondur** [comment]
Hey @yaroslav-nakonechnikov , we are able to scale custom resources using replicas as mentioned [here](https://github.com/splunk/splunk-operator/blob/main/docs/Examples.md#scaling-cluster-peers-using-replicas). Can you try using the same?

**Comment by yaroslav-nakonechnikov** [comment]
@akondur  it is different thing. if you open https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource, you will see explanation about advanced usage of replicas. 

simple `replicas` can be used, but with workarounds and writing custom scripts.

**Comment by akondur** [comment]
Hey @yaroslav-nakonechnikov , the operator CRDs have the scale subresource already embedded in. Couple of code references:

[Standalone](https://github.com/splunk/splunk-operator/blob/main/api/v4/standalone_types.go#L83)
[SHC](https://github.com/splunk/splunk-operator/blob/main/api/v4/searchheadcluster_types.go#L128)

From the CRD spec deployed on an EKS cluster:

```
bash% k get crds/standalones.enterprise.splunk.com -o yaml | grep -i scale: -A 3
      scale:
        labelSelectorPath: .status.selector
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
--
      scale:
        labelSelectorPath: .status.selector
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
```

I tried autoscaling using Keda using the following steps:

1. Install keda using instructions from [here](https://keda.sh/docs/2.13/deploy/).
2. Use the scaledobject spec below to target a standalone resource

```
bash% cat ~/keda_scaler.yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-sa
  namespace: splunk-operator
spec:
  scaleTargetRef:
    apiVersion: enterprise.splunk.com/v4
    kind: Standalone
    name: example
  pollingInterval:  5                                      # Optional. Default: 30 seconds
  cooldownPeriod:   10                                     # Optional. Default: 300 seconds
  idleReplicaCount: 0                                       # Optional. Default: ignored, must be less than minReplicaCount
  minReplicaCount:  1                                       # Optional. Default: 0
  maxReplicaCount:  100                                     # Optional. Default: 100
  advanced:                                                 # Optional. Section to specify advanced options
  triggers:
  - type: cpu
    #metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
    metadata:
      type: Utilization # Deprecated in favor of trigger.metricType; allowed types are 'Utilization' or 'AverageValue'
      value: "5"
```

Once deployed:

```
bash% kubectl describe scaledobject  Creation Timestamp:  2024-02-27T01:17:32Z
  Finalizers:
    finalizer.keda.sh
  Generation:        1
  Resource Version:  13949
  UID:               63fae67f-e2df-4379-8e1a-7661ec5b0179
Spec:
  Cooldown Period:     10
  Idle Replica Count:  0
  Max Replica Count:   100
  Min Replica Count:   1
  Polling Interval:    5
  Scale Target Ref:
    API Version:  enterprise.splunk.com/v4
    Kind:         Standalone
    Name:         example
  Triggers:
    Metadata:
      Type:   Utilization
      Value:  5
    Type:     cpu
Status:
  Conditions:
    Message:               ScaledObject is defined correctly and is ready for scaling
    Reason:                ScaledObjectReady
    Status:                True
    Type:                  Ready
    Message:               Scaling is performed because triggers are active
    Reason:                ScalerActive
    Status:                True
    Type:                  Active
    Status:                Unknown
    Type:                  Fallback
    Status:                Unknown
    Type:                  Paused
  Hpa Name:                keda-hpa-keda-sa
  Last Active Time:        2024-02-27T01:43:57Z
  Original Replica Count:  1
  Resource Metric Names:
    cpu
  Scale Target GVKR:
    Group:            enterprise.splunk.com
    Kind:             Standalone
    Resource:         standalones
    Version:          v4
  Scale Target Kind:  enterprise.splunk.com/v4.Standalone
Events:
  Type    Reason              Age   From           Message
  ----    ------              ----  ----           -------
  Normal  KEDAScalersStarted  26m   keda-operator  Scaler cpu is built.
  Normal  KEDAScalersStarted  26m   keda-operator  Started scalers watch
  Normal  ScaledObjectReady   26m   keda-operator  ScaledObject is ready for scaling
```

Corresponding HPA where its able to find the scale subresource and hook onto it:

```
bash % k describe hpa
Name:                                                  keda-hpa-keda-sa
Namespace:                                             splunk-operator
Labels:                                                app.kubernetes.io/managed-by=keda-operator
                                                       app.kubernetes.io/name=keda-hpa-keda-sa
                                                       app.kubernetes.io/part-of=keda-sa
                                                       app.kubernetes.io/version=2.13.0
                                                       scaledobject.keda.sh/name=keda-sa
Annotations:                                           <none>
CreationTimestamp:                                     Mon, 26 Feb 2024 19:17:32 -0600
Reference:                                             Standalone/example
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 5%
Min replicas:                                          1
Max replicas:                                          100
Standalone pods:                                       1 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
```

From the results above looks like the scale subresource is working. Is there an error you are seeing when deploying with keda? Does deploying a hpa like below work for you?

```
kind: HorizontalPodAutoscaler
metadata:
  name: sa-hpa
  namespace: splunk-operator
spec:
  scaleTargetRef:
    apiVersion: enterprise.splunk.com/v4
    kind: Standalone
    name: example
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 1
```
