### ISSUE TITLE
Splunk Operator: controller doesn't detect if statefulset deleted for standalone type

### ISSUE THREAD

**Issue by yaroslav-nakonechnikov** [splunk/splunk-operator#1284]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
if there are some changes done in stateful set for standalone instance - controlled doesn't recreate it as it is done for other types

**Expected behavior**
controller creates statefulset from crd

**Comment by yaroslav-nakonechnikov** [comment]
```
$ kubectl get standalone
NAME     PHASE   DESIRED   READY   AGE
c-prod                             23m
```

in description there was warning:
 Warning  validateStandaloneSpec  20m    splunk-standalone-controller  validate standalone spec failed invalid Volume Name for App Source: custom. volume: csh, doesn't exist
 
 but, it shouldn't be the case, as before deleting statefulset it was working

**Comment by vivekr-splunk** [comment]
can you add CR spec here, we will retry on our end and let you know

**Comment by yaroslav-nakonechnikov** [comment]
broken example, which creates warning and blocking creating resources:
```
 appRepo:
    appInstallPeriodSeconds: 90
    appSources:
    - location: custom/
      name: custom
      scope: local
      volumeName: csh
    - location: base/
      name: base
      scope: local
      volumeName: csh
    appsRepoPollIntervalSeconds: 120
    installMaxRetries: 3
    volumes:
    - endpoint: https://s3-eu-central-1.amazonaws.com
      name: splunkapps
      path: bucketname/splunk-apps/csh
      provider: aws
      region: eu-central-1
      storageType: s3
```

correct example:
```
 appRepo:
    appInstallPeriodSeconds: 90
    appSources:
    - location: custom/
      name: custom
      scope: local
      volumeName: splunkapps
    - location: base/
      name: base
      scope: local
      volumeName: splunkapps
    appsRepoPollIntervalSeconds: 120
    installMaxRetries: 3
    volumes:
    - endpoint: https://s3-eu-central-1.amazonaws.com
      name: splunkapps
      path: bucketname/splunk-apps/csh
      provider: aws
      region: eu-central-1
      storageType: s3
```

so, all in all, expectation that `warning` doesn't block anything, but feature just not working. 
or, it should be `error` - and in that case it will be expected.
