### ISSUE TITLE
Add ability to specify mount points

### ISSUE THREAD

**Issue by k4r1** [splunk/splunk-operator#1314]
### Please select the type of request

Enhancement

### Tell us more

**Describe the request**
At the moment, we can specify Volumes for each Custom Resource using the [volumes](https://splunk.github.io/splunk-operator/CustomResources.html#:~:text=described%20in%20StorageClass-,volumes,-Volume) property and they will be mounted at `/mnt/<volume-name>`.

This is useful - however, it is not possible to override the mount points.

Edit: Removed example, turns out there's a workaround. I still think it's a useful enhancement though so keeping the issue open.

**Proposed changes**
Add a `volumeMounts` property to each CRD and have the operator use the value to determine the mounts for the stateful set.

**Comment by yaroslav-nakonechnikov** [comment]
nope, it mustn't.

we using defaults.yml with next section:
```
splunk:
  conf:
    - key: authentication
      value:
        directory: /opt/splunk/etc/system/local
        content:
          authentication:
            authSettings: saml
            authType: SAML
          saml:
            entityId: splunkACSEntityId
            fqdn: https://sp.company.com
            idpSSOUrl: https://idp.company.com/idp/SSO.saml2
            inboundDigestMethod: SHA1;SHA256;SHA384;SHA512
            inboundSignatureAlgorithm: RSA-SHA1;RSA-SHA256;RSA-SHA384;RSA-SHA512
            issuerId: idp:company.com:saml2
            lockRoleToFullDN: true
            redirectAfterLogoutToUrl: https://www.splunk.com
            redirectPort: 443
            replicateCertificates: true
            signAuthnRequest: true
            signatureAlgorithm: RSA-SHA1
            signedAssertion: true
            sloBinding: HTTP-POST
            ssoBinding: HTTP-POST
            clientCert: /mnt/certs/saml_sig.pem
            idpCertPath: /mnt/certs/
          roleMap_SAML:
            admin: grp-admin;
```
