### ISSUE TITLE
Splunk Operator: Support defining Metrics Indexes

### ISSUE THREAD

**Issue by PrymalInstynct** [splunk/splunk-operator#1423]
### Please select the type of request

Feature

### Tell us more

**Describe the request**
Add support for defining a Metrics index via the Cluster Manager resource

**Expected behavior**
Parameters exist that allow a user to define an index as being for Metric type data

**Splunk setup on K8S**
N/A

**Reproduction/Testing steps**
N/A

**K8s environment**
N/A

**Proposed changes(optional)**
See Example below

```
spec:
  smartstore:
    defaults:
        volumeName: msos_s2s3_vol
    indexes:
      - name: linux_logs
        remotePath: $_index_name
        volumeName: msos_s2s3_vol
      - name: linux_metrics
        metrics: true
        remotePath: $_index_name
        volumeName: msos_s2s3_vol
    volumes:
      - name: msos_s2s3_vol
        path: <remote path>
        endpoint: <remote endpoint>
        secretRef: s3-secret
```
**K8s collector data(optional)**
N/A

**Additional context(optional)**
N/A
