### ISSUE TITLE
Wrong ImagePullPolicy value

### ISSUE THREAD

**Issue by yoann-ls** [splunk/splunk-operator#1475]
With helm deployment of a c3 cluster, the default imaPullPolicy is empty for the licensemanager:

```
 kubectl get events --sort-by='.lastTimestamp' -n splunk-operator
```
```
41s         Warning   changeClusterManagerAnnotations   licensemanager/lm                          Could not update annotations. Reason ClusterManager.enterprise.splunk.com "cm" is invalid: spec.imagePullPolicy: Unsupported value: "": supported values: "Always", "IfNotPresent"
41s         Warning   changeClusterManagerAnnotations   licensemanager/lm                          Could not update annotations. Reason ClusterManager.enterprise.splunk.com "cm" is invalid: spec.imagePullPolicy: Unsupported value: "": supported values: "Always", "IfNotPresent"
41s         Warning   changeClusterManagerAnnotations   licensemanager/lm                          Could not update annotations. Reason ClusterManager.enterprise.splunk.com "cm" is invalid: spec.imagePullPolicy: Unsupported value: "": supported values: "Always", "IfNotPresent"
41s         Warning   changeClusterManagerAnnotations   licensemanager/lm                          Could not update annotations. Reason ClusterManager.enterprise.splunk.com "cm" is invalid: spec.imagePullPolicy: Unsupported value: "": supported values: "Always", "IfNotPresent"
41s         Warning   changeClusterManagerAnnotations   licensemanager/lm                          Could not update annotations. Reason ClusterManager.enterprise.splunk.com "cm" is invalid: spec.imagePullPolicy: Unsupported value: "": supported values: "Always", "IfNotPresent"
41s         Warning   changeClusterManagerAnnotations   licensemanager/lm                          Could not update annotations. Reason ClusterManager.enterprise.splunk.com "cm" is invalid: spec.imagePullPolicy: Unsupported value: "": supported values: "Always", "IfNotPresent"
40s         Warning   changeClusterManagerAnnotations   licensemanager/lm                          Could not update annotations. Reason ClusterManager.enterprise.splunk.com "cm" is invalid: spec.imagePullPolicy: Unsupported value: "": supported values: "Always", "IfNotPresent"
40s         Warning   changeClusterManagerAnnotations   licensemanager/lm                          Could not update annotations. Reason ClusterManager.enterprise.splunk.com "cm" is invalid: spec.imagePullPolicy: Unsupported value: "": supported values: "Always", "IfNotPresent"
39s         Warning   changeClusterManagerAnnotations   licensemanager/lm                          Could not update annotations. Reason ClusterManager.enterprise.splunk.com "cm" is invalid: spec.imagePullPolicy: Unsupported value: "": supported values: "Always", "IfNotPresent"
38s         Warning   changeClusterManagerAnnotations   licensemanager/lm                          Could not update annotations. Reason ClusterManager.enterprise.splunk.com "cm" is invalid: spec.imagePullPolicy: Unsupported value: "": supported values: "Always", "IfNotPresent"
36s         Warning   changeClusterManagerAnnotations   licensemanager/lm                          Could not update annotations. Reason ClusterManager.enterprise.splunk.com "cm" is invalid: spec.imagePullPolicy: Unsupported value: "": supported values: "Always", "IfNotPresent"
30s         Warning   changeClusterManagerAnnotations   licensemanager/lm                          Could not update annotations. Reason ClusterManager.enterprise.splunk.com "cm" is invalid: spec.imagePullPolicy: Unsupported value: "": supported values: "Always", "IfNotPresent"
20s         Warning   changeClusterManagerAnnotations   licensemanager/lm                          Could not update annotations. Reason ClusterManager.enterprise.splunk.com "cm" is invalid: spec.imagePullPolicy: Unsupported value: "": supported values: "Always", "IfNotPresent"

```

The imagePullPolicy should have either "Always" or "IfNotPresent"

**Comment by iancward** [comment]
I've deployed the operator via the manifest, and have have created resources directly, and the controller is throwing a lot of errors that imagePullPolicy is empty for both License Manager and Cluster Manager.

**Comment by rlieberman-splunk** [comment]
Hi @iancward , I have tried to reproduce this issue with manifest files and I was unable to. The `imagePullPolicy` correctly gets set to `IfNotPresent` if it is not added in the manifest file directly for both license managers and cluster managers. Here is the simple manifest file I used to deploy a c3 instance. 

```
---
apiVersion: enterprise.splunk.com/v4
kind: ClusterManager
metadata:
  name: cm
  namespace: splunk-operator
  finalizers:
    - "enterprise.splunk.com/delete-pvc"
---
apiVersion: enterprise.splunk.com/v4
kind: IndexerCluster
metadata:
  name: idxc
  namespace: splunk-operator
  finalizers:
    - "enterprise.splunk.com/delete-pvc"
spec:
  clusterManagerRef:
    name: cm
  licenseManagerRef:
    name: lm
  replicas: 3
---
apiVersion: enterprise.splunk.com/v4
kind: SearchHeadCluster
metadata:
  name: shc
  namespace: splunk-operator
  finalizers:
    - "enterprise.splunk.com/delete-pvc"
spec:
  clusterManagerRef:
    name: cm
  licenseManagerRef:
    name: lm
  replicas: 3
---
apiVersion: enterprise.splunk.com/v4
kind: LicenseManager
metadata:
  name: lm
  namespace: splunk-operator
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  volumes:
    - name: licenses
      configMap:
        name: splunk-licenses
  licenseUrl: /mnt/licenses/enterprise.lic
```


I'm glad it is working for you by manually setting it, but if you would like to us to look further into the issue, can you please share more about your environment? Including your cloud service provider, versions of splunk operator and splunk enterprise, and the manifest files you are using?
