### ISSUE TITLE
License not added to License Manager when passed in configMap

### ISSUE THREAD

**Issue by yoann-ls** [splunk/splunk-operator#1476]
**Issue**

When creating a configMap for the license
```
 kubectl create configmap splunk-licenses --from-file=/mnt/license/Splunk_Enterprise.xml -n splunk-operator
```

Then configuring the helm chart with:
```
  clusterManagerRef:
    name: cm
  volumes:
    - name: licenses
      configMap:
        name: splunk-licenses

  licenseUrl: "/mnt/license/Splunk_Enterprise.xml"
```

Then the license is passed to the License Manager Pod as expected in /mnt/license/Splunk_Enterprise.xml.
But once the pod is runnig, the license has not been added.

We must then have to manually:
- get the passwd:
``` kubectl get secret splunk-lm-license-manager-secret-v1 -n splunk-operator -o jsonpath='{.data.password}' | base64 --decode```

- add it in the pod with the admin/passwd that we need to get from 
```
 kubectl exec -it --namespace=splunk-operator splunk-lm-license-manager-0  -- bash
/opt/splunk/bin/splunk add license /mnt/licenses/Splunk_Enterprise.xml
/opt/splunk/bin/splunk restart
```

**Expected behavior**
When the license is passed via a configMap, it has to be applied automatically without further admin operation.
