### ISSUE TITLE
Splunk Operator: can't use serviceTemplate for metadata values

### ISSUE THREAD

**Issue by L30Bola** [splunk/splunk-operator#1515]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
When trying to use the `spec.serviceTemplate.metadata` field of the CRDs, I receive the error

```
strict decoding error: unknown field "spec.serviceTemplate.metadata.annotations"
```

**Expected behavior**
I expected to be able to pass labels and/or annotations to the `spec.serviceTemplate.metadata` field (as the `metadata` field exists and it appears that it's supported by the controller, but not the "child" fields) and they would be propagated to the generated Service for the given Splunk Component. 

**Splunk setup on K8S**
I deploying everything from scratch and I was able to successfully link the moving pieces (LicenseManager, ClusterManager, IndexerCluster, SearchHeadCluster, MonitoringConsole), but really wanted to be able to customize the generated service without the need of an external tool

**Reproduction/Testing steps**
Trying to apply a new Splunk CR instance with the `spec.serviceTemplate.metadata.annotations` field set, it errors with the similar error from above:

```
Error from server (BadRequest): error when creating "file.yaml": LicenseManager in version "v4" cannot be handled as a LicenseManager: strict decoding error: unknown field "spec.serviceTemplate.metadata.annotations"
```

<details>

<summary>file.yaml contents</summary>

```yaml
apiVersion: enterprise.splunk.com/v4
kind: LicenseManager
metadata:
  name: lm-wc-prod-hq
  namespace: splunk
spec:
  imagePullPolicy: IfNotPresent
  livenessInitialDelaySeconds: 300
  livenessProbe:
    failureThreshold: 3
  readinessInitialDelaySeconds: 10
  readinessProbe:
    failureThreshold: 48
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  serviceTemplate:
    metadata:
      annotations:
        io.cilium/global-service: 'true'
  startupProbe:
    failureThreshold: 48
```

</details>

**K8s environment**
Kind generated cluster, version 1.32.2 (local test that mirror my production's setup)
Tested with Splunk Operator 2.7.1 and 2.8.0
