### ISSUE TITLE
Cannot increase the disk size of /opt/splunk/var 

### ISSUE THREAD

**Issue by s-marchenko** [splunk/splunk-operator#216]
Hi there,

I wonder if there is a way to increase the disk size of /opt/splunk/var

I tried to edit CRD to delete all the pods to be able to edit the PVC.

```
  spec:
  defaultsUrl: /mnt/splunk-inputs/inputs.yml
  replicas: 0
  varStorage: 160Gi
  volumes:
  - name: foo
    secret:
      secretName: tst-index-secret
  - configMap:
      name: splunk-inputs
    name: splunk-inputs
```

It didn't scale down, but it works like a champ if I set the number of replicas to more than 1 (2-3).

Also, I tried to edit the number of replicas in the stateful set. It didn't work as well.

So please advise how to increase the disk space correctly.

Thanks,
