### ISSUE TITLE
NodeSelector functionality

### ISSUE THREAD

**Issue by akantak** [splunk/splunk-operator#231]
Hey, is there a plan to add NodeSelector Kubernetes functionality (https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/)?
IMO, there should be an option to pass the nodeSelector setting to CRD definitions so it would be passed from CRD to statefulsets and from statefulsets to pod to select the schedulable node

**Comment by pogdin** [comment]
I believe this should work with the CRDs at present.  You label the nodes you want certain pods scheduled on.  For example, if you had nvme nodes you wanted to have the Splunk indexers land on:

`kubectl label nodes <node-name> disktype=nvme`

Then put the nodeSelector in the spec stanza of the CRD

```
apiVersion: enterprise.splunk.com/v1beta1
kind: IndexerCluster
metadata:
  name: example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
    nodeSelector:
      disktype: nvme
```

Does this not meet your requirements?  Thanks.

**Comment by akantak** [comment]
@pogdin 
I tried that. I am using splunk operator 0.2.1. My cluster master definition:
```
apiVersion: enterprise.splunk.com/v1beta1
kind: ClusterMaster
metadata:
  name: example-cm
  namespace: default
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  nodeSelector:
    disktype: nvme
```
I labeled only node5:
```
[root@node1 k8s_definitions]# kubectl label nodes node5 disktype=nvme
node/node5 labeled
```
I check where the pod was scheduled:
```
[root@node1 k8s_definitions]# kubectl get pods splunk-example-cm-cluster-master-0 -o wide
NAME                                 READY   STATUS    RESTARTS   AGE     IP            NODE    NOMINATED NODE   READINESS GATES
splunk-example-cm-cluster-master-0   1/1     Running   0          5m23s   10.233.92.8   node3   <none>           <none>
[root@node1 k8s_definitions]#
```
Kubectl describe (no node selector entries there):
```
[root@node1 k8s_definitions]# kubectl describe pod splunk-example-cm-cluster-master-0 | grep -i selector
Node-Selectors:  <none>
```
Statefulset could be manually patched, but finally, it could be overwritten by the operator so it is not an option here:
```
[root@node1 k8s_definitions]# cat nodeselector_patch.yaml
spec:
  template:
    spec:
      nodeSelector:
        disktype: nvme

[root@node1 k8s_definitions]# kubectl patch statefulset splunk-example-cm-cluster-master --patch "$(cat ./nodeselector_patch.yaml)"
statefulset.apps/splunk-example-cm-cluster-master patched
[root@node1 k8s_definitions]# kubectl describe pod splunk-example-cm-cluster-master-0 | grep -i selector
Node-Selectors:  disktype=nvme
```

So, to set the nodeSelector I would have to work against the operator, as it is not supported so far.

**Comment by pogdin** [comment]
I'm also getting `Node-Selectors:  <none>` .  Will file as Enhancement.  Thanks.

**Comment by akantak** [comment]
Checked documentation. It is true that NodeSelector is not pushed from CRD to sts and then to pods, but there is a similar mechanism that works correctly and is already implemented. Simply use:
```
apiVersion: enterprise.splunk.com/v1beta1
kind: ClusterMaster
metadata:
  name: example-cm
  namespace: default
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - nvme
```
