### ISSUE TITLE
Review the readinessProbe

### ISSUE THREAD

**Issue by romain-bellanger** [splunk/splunk-operator#234]
The purpose of a [readinessProbe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes) is to exclude a pod temporarily unable to serve traffic from load balancing.

The splunk-operator configures the readinessProbe on Splunk pods to run the following command:
```yaml
    readinessProbe:
      exec:
        command:
        - /bin/grep
        - started
        - /opt/container_artifact/splunk-container.state
```

The file ```/opt/container_artifact/splunk-container.state``` is a simple flag set to ```started``` by the entry point script of the Docker image (```/sbin/entrypoint.sh```) if the ansible startup playbook completes successfully. This does not indicate if a pod is able to serve traffic, and doesn't seem to limit the data loss for instance on rolling restart for cluster-bundle deployment on indexer cluster, or while pods are going offline and reassign their buckets for various reasons (spec change, upgrade, scaling).
