### ISSUE TITLE
Indexer Cluster wont scale - Couldn't Retrieve idxc_secret from secret data Couldn't find pod

### ISSUE THREAD

**Issue by Kiran01bm** [splunk/splunk-operator#249]
I have been trying out the splunk-operator in our Test bed and have run into an issue related to scaling of Indexer Cluster.

1. Splunk Operator Version - `docker.io/splunk/splunk-operator:0.2.0`
2. Splunk Version - `docker.io/splunk/splunk:8.1.0`

### Sequence:
1. Deploy Splunk Operator
2. Deploy CM
3. Deploy Indexer Cluster - 1 replica
4. Patch Indexer cluster to scale out to 3 replicas

### Error Message from Operator logs:
```
{"level":"error","ts":1612847772.6755786,"logger":"splunk.reconcile.Reconcile","msg":"Reconciliation requeued","Group":"enterprise.splunk.com","Version":"v1beta1","Kind":"IndexerCluster","Namespace":"default","Name":"example","RequeueAfter":5,"error":"Couldn't Retrieve idxc_secret from secret data Couldn't find pod","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgo/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/splunk/splunk-operator/pkg/splunk/controller.splunkReconciler.Reconcile\n\tsplunk-operator/pkg/splunk/controller/controller.go:125\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
```

### Status from Indexer Cluster:
```
ζ k get idc                                                                                                                                                                                                                       
NAME      PHASE     MASTER   DESIRED   READY   AGE
example   Pending   Ready    3         1       3d12h
```
```
status:
  clusterMasterPhase: Ready
  indexer_secret_changed_flag: []
  indexing_ready_flag: false
  initialized_flag: false
  maintenance_mode: false
  namespace_scoped_secret_resource_version: "193491"
  peers:
  - active_bundle_id: 1A47E5DD411C558A54D8390246AD8E67
    bucket_count: 2
    guid: BED4EC84-0386-4814-82CB-426551462225
    is_searchable: true
    name: splunk-example-indexer-0
    status: Up
  phase: Pending
  readyReplicas: 1
  replicas: 3
  selector: app.kubernetes.io/instance=splunk-example-indexer
  service_ready_flag: false
```

### No events on Splunk-Operator Pod
```
ζ k describe pod splunk-operator-78c78b985f-8zjhg                                                                                                                                                
Name:         splunk-operator-78c78b985f-8zjhg
Namespace:    default
Priority:     0
Node:         <<MASKED>>
Start Time:   Thu, 04 Feb 2021 16:07:39 +1100
Labels:       name=splunk-operator
              pod-template-hash=78c78b985f
Annotations:  kubernetes.io/psp: eks.privileged
Status:       Running
IP:           10.0.2.89
IPs:
  IP:           10.0.2.89
Controlled By:  ReplicaSet/splunk-operator-78c78b985f
Containers:
  splunk-operator:
    Container ID:   docker://c9f9be74d1d8dc3c0d679cce807d8820f46019805b9c4986cf4c208f354a14db
    Image:          docker.io/splunk/splunk-operator:0.2.0
    Image ID:       docker-pullable://splunk/splunk-operator@sha256:2ffd9038d9815023901021e7a93f61d95ccae67cf6ce1bf990013eca57f0f519
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 04 Feb 2021 16:07:50 +1100
    Ready:          True
    Restart Count:  0
    Environment:
      WATCH_NAMESPACE:                  default (v1:metadata.namespace)
      POD_NAME:                         splunk-operator-78c78b985f-8zjhg (v1:metadata.name)
      OPERATOR_NAME:                    splunk-operator
      RELATED_IMAGE_SPLUNK_ENTERPRISE:  docker.io/splunk/splunk:8.1.0
      RELATED_IMAGE_SPLUNK_SPARK:       docker.io/splunk/spark:0.0.2
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from splunk-operator-token-v8p2f (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  splunk-operator-token-v8p2f:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  splunk-operator-token-v8p2f
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>
```
