### ISSUE TITLE
Using SmartStore with EKS OIDC

### ISSUE THREAD

**Issue by camStryk3r** [splunk/splunk-operator#307]
We're having an issue using OIDC for authentication with SmartStore. We are using an EKS service account, which creates a token that can be read at `/var/run/secrets/eks.amazonaws.com/serviceaccount/token`. Even though the cluster master pod appears to have the proper environment variables injected, the operator logs say that it still requires a secretRef for SmartStore to be configured, which is something we're trying to avoid using since we're using OIDC.

Are there some examples or another way we should be configuring SmartStore so that we can use OIDC vs a generic access key and secret in a secretRef?

**Comment by pogdin** [comment]
Hi, are you creating the SmartStore indexes in the Cluster Manager YAML or defining them in an App?

**Comment by camStryk3r** [comment]
Currently trying to do it in the Cluster Manager YAML, here's an example of what our Cluster Manager YAML looks like. `iam-test` refers to our EKS service account.

```
apiVersion: enterprise.splunk.com/v1beta1
kind: ClusterMaster
metadata:
  name: cm-example
spec:
  licenseMasterRef:
    name: lm-example
  serviceAccount: iam-test
  smartstore:
    defaults:
        remotePath: $_index_name
        volumeName: our-s3-volume
    volumes:
      - name: our-s3-volume
        path: our-s3-volume/test
        endpoint: https://s3.us-east-1.amazonaws.com
        #secretRef: splunk-iam-test
```
