### ISSUE TITLE
Readiness probe fails when splunkd SSL is off

### ISSUE THREAD

**Issue by jfusterm** [splunk/splunk-operator#317]
I want to start the `web`, `api` and `hec` services with the SSL off so I can put a load balancer in front on them doing the offloading.

I'm using the version `1.0.0` of the `splunk-operator` and this configuration.

```yaml
apiVersion: enterprise.splunk.com/v1
kind: Standalone
metadata:
  name: dev
  namespace: splunk
  labels:
    app: splunk
    environment: development
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  image: splunk/splunk:8.1.3
  imagePullPolicy: Always
  resources:
    requests:
      memory: 1Gi
      cpu: "1"
    limits:
      memory: 4Gi
      cpu: "2"
  defaults: |-
    splunk:
      home: /opt/splunk
      http_enableSSL: 0
      http_enableSSL_cert: null
      http_enableSSL_privKey: null
      http_enableSSL_privKey_password: null
      http_port: 8000
      svc_port: 8089
      ssl:
        enable: False
      hec:
        enable: True
        ssl: False
        port: 8088
```

Once deployed the monitoring console does not start due to the readiness probe and in Splunk it fails too.

```sh
❯ kubectl get pods -n splunk  
NAME                                             READY   STATUS    RESTARTS   AGE
splunk-operator-69b979774b-jrp4s                 1/1     Running   0          3m34s
splunk-dev-standalone-0                          1/1     Running   0          58s
splunk-splunk-monitoring-console-0               0/1     Running   0          22s
```

```sh
❯ kubectl describe pod -n splunk splunk-splunk-monitoring-console-0
...
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  57s               default-scheduler  Successfully assigned splunk/splunk-splunk-monitoring-console-0 to k3d-infrastructure-1
  Normal   Pulling    57s               kubelet            Pulling image "splunk/splunk:8.1.3"
  Normal   Pulled     55s               kubelet            Successfully pulled image "splunk/splunk:8.1.3" in 2.709859833s
  Normal   Created    54s               kubelet            Created container splunk
  Normal   Started    54s               kubelet            Started container splunk
  Warning  Unhealthy  1s (x9 over 41s)  kubelet            Readiness probe failed:
```

```sh
❯ kubectl describe pod -n splunk splunk-dev-standalone-0
...
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m41s                  default-scheduler  Successfully assigned splunk/splunk-dev-standalone-0 to k3d-infrastructure-0
  Normal   Pulling    4m41s                  kubelet            Pulling image "splunk/splunk:8.1.3"
  Normal   Pulled     4m38s                  kubelet            Successfully pulled image "splunk/splunk:8.1.3" in 2.778060706s
  Normal   Created    4m38s                  kubelet            Created container splunk
  Normal   Started    4m38s                  kubelet            Started container splunk
  Warning  Unhealthy  4m17s (x3 over 4m27s)  kubelet            Readiness probe failed:
```

When `ssl.enable = True` all works as expected.

Is there any way of starting those services without SSL and make the readiness probe work?
