### ISSUE TITLE
Index Cluster CR in error phase and related pods not started

### ISSUE THREAD

**Issue by prakashmirji** [splunk/splunk-operator#320]
Env:
Splunk operator 1.0.0
k8s version: 1.20.2

After deploying ClusterMaster CR, tried to deploy IndexerCluster, the CR shows up in error phase and there are no indexer pods started. See the command output below

>>kubectl get IndexerCluster morgan -n splunk
NAME     PHASE   MASTER   DESIRED   READY   AGE
morgan   Error   Ready    3         0       33m

Below command show all objects in the splunk namespace. You don't see any pods or statefulset with indexer. 
===========
>>kubectl get all -n splunk
NAME                                     READY   STATUS    RESTARTS   AGE
pod/kiali-ff7d644db-wvwrt                2/2     Running   0          28h
pod/splunk-cm-cluster-master-0           2/2     Running   0          3h9m
pod/splunk-morgan-deployer-0             2/2     Running   0          172m
pod/splunk-morgan-search-head-0          2/2     Running   0          172m
pod/splunk-morgan-search-head-1          2/2     Running   0          172m
pod/splunk-morgan-search-head-2          2/2     Running   0          172m
pod/splunk-operator-545989889b-j9zgh     2/2     Running   2          3h42m
pod/splunk-splunk-monitoring-console-0   2/2     Running   0          168m

NAME                                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                               AGE
service/istio-ingress-import-t8zst                  NodePort    10.99.242.181    <none>        80:30921/TCP,443:30114/TCP            28h
service/kiali                                       NodePort    10.108.222.176   <none>        20001:32189/TCP,9090:30361/TCP        28h
service/splunk-cm-cluster-master-service            ClusterIP   10.99.127.190    <none>        8000/TCP,8089/TCP                     3h9m
service/splunk-cm-indexer-service                   ClusterIP   10.103.178.105   <none>        8000/TCP,8088/TCP,8089/TCP,9997/TCP   83m
service/splunk-cm-indexer-service-headless          ClusterIP   None             <none>        8000/TCP,8088/TCP,8089/TCP,9997/TCP   53m
service/splunk-morgan-deployer-service              ClusterIP   10.108.135.51    <none>        8000/TCP,8089/TCP                     172m
service/splunk-morgan-search-head-headless          ClusterIP   None             <none>        8000/TCP,8089/TCP                     172m
service/splunk-morgan-search-head-service           ClusterIP   10.110.26.84     <none>        8000/TCP,8089/TCP                     172m
service/splunk-operator-metrics                     ClusterIP   10.110.109.43    <none>        8383/TCP,8686/TCP                     3h41m
service/splunk-splunk-monitoring-console-headless   ClusterIP   None             <none>        8000/TCP,8088/TCP,8089/TCP,9997/TCP   3h8m
service/splunk-splunk-monitoring-console-service    ClusterIP   10.104.241.207   <none>        8000/TCP,8088/TCP,8089/TCP,9997/TCP   3h8m

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/kiali             1/1     1            1           28h
deployment.apps/splunk-operator   1/1     1            1           3h42m

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/kiali-ff7d644db              1         1         1       28h
replicaset.apps/splunk-operator-545989889b   1         1         1       3h42m

NAME                                                READY   AGE
statefulset.apps/splunk-cm-cluster-master           1/1     3h9m
statefulset.apps/splunk-morgan-deployer             1/1     172m
statefulset.apps/splunk-morgan-search-head          3/3     172m
statefulset.apps/splunk-splunk-monitoring-console   1/1     168m

================
Here is the error messages from the operator

>kubectl logs -f -n splunk pod/splunk-operator-545989889b-j9zgh -c splunk
{"level":"info","ts":1619171706.0637205,"logger":"splunk.reconcile.Reconcile","msg":"Reconciling custom resource","Group":"enterprise.splunk.com","Version":"v1","Kind":"IndexerCluster","Namespace":"splunk","Name":"morgan"}
{"level":"error","ts":1619171706.0964763,"logger":"splunk.reconcile.Reconcile","msg":"Reconciliation requeued","Group":"enterprise.splunk.com","Version":"v1","Kind":"IndexerCluster","Namespace":"splunk","Name":"morgan","RequeueAfter":5,"error":"Could not get cluster info from cluster master","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgo/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/splunk/splunk-operator/pkg/splunk/controller.splunkReconciler.Reconcile\n\tsplunk-operator/pkg/splunk/controller/controller.go:125\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1619171709.9640195,"logger":"splunk.reconcile.Reconcile","msg":"Reconciling custom resource","Group":"enterprise.splunk.com","Version":"v1","Kind":"ClusterMaster","Namespace":"splunk","Name":"cm"}
{"level":"info","ts":1619171709.9779418,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-cm-indexer-service","namespace":"splunk"}
{"level":"info","ts":1619171709.980233,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-cm-cluster-master-service","namespace":"splunk"}
{"level":"info","ts":1619171709.9993775,"logger":"splunk.reconcile.UpdateStatefulSetPods","msg":"All pods are ready","name":"splunk-cm-cluster-master","namespace":"splunk"}
{"level":"info","ts":1619171710.009225,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-splunk-monitoring-console-service","namespace":"splunk"}
{"level":"info","ts":1619171710.0120397,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-splunk-monitoring-console-headless","namespace":"splunk"}
{"level":"error","ts":1619171710.0288768,"logger":"splunk.reconcile.Reconcile","msg":"Reconciliation requeued","Group":"enterprise.splunk.com","Version":"v1","Kind":"ClusterMaster","Namespace":"splunk","Name":"cm","RequeueAfter":5,"error":"Get https://splunk-cm-cluster-master-service.splunk.svc.cluster.local:8089/services/cluster/config?count=0&output_mode=json: read tcp 10.192.2.15:37032->10.99.127.190:8089: read: connection reset by peer","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgo/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/splunk/splunk-operator/pkg/splunk/controller.splunkReconciler.Reconcile\n\tsplunk-operator/pkg/splunk/controller/controller.go:125\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}

Any pointers to troubleshoot this?
@gaurav-splunk

**Comment by prakashmirji** [comment]
I tried to use the CLUSTER_DOMAIN variable for the operator to use custom domain set to k8s cluster. I still same error. see below

{"level":"info","ts":1619174786.0406065,"logger":"splunk.reconcile.Reconcile","msg":"Reconciling custom resource","Group":"enterprise.splunk.com","Version":"v1","Kind":"ClusterMaster","Namespace":"splunk","Name":"cm"}
{"level":"info","ts":1619174786.0528188,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-cm-indexer-service","namespace":"splunk"}
{"level":"info","ts":1619174786.0552425,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-cm-cluster-master-service","namespace":"splunk"}
{"level":"info","ts":1619174786.0741851,"logger":"splunk.reconcile.UpdateStatefulSetPods","msg":"All pods are ready","name":"splunk-cm-cluster-master","namespace":"splunk"}
{"level":"info","ts":1619174786.0832176,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-splunk-monitoring-console-service","namespace":"splunk"}
{"level":"info","ts":1619174786.085766,"logger":"splunk.reconcile.ApplyService","msg":"No update to existing Service","name":"splunk-splunk-monitoring-console-headless","namespace":"splunk"}
{"level":"error","ts":1619174786.0977724,"logger":"splunk.reconcile.Reconcile","msg":"Reconciliation requeued","Group":"enterprise.splunk.com","Version":"v1","Kind":"ClusterMaster","Namespace":"splunk","Name":"cm","RequeueAfter":5,"error":"Get https://splunk-cm-cluster-master-service.splunk.svc.atlpss.hp.net:8089/services/cluster/config?count=0&output_mode=json: dial tcp: lookup splunk-cm-cluster-master-service.splunk.svc.atlpss.hp.net on 10.96.0.10:53: no such host","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgo/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/splunk/splunk-operator/pkg/splunk/controller.splunkReconciler.Reconcile\n\tsplunk-operator/pkg/splunk/controller/controller.go:125\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}

**Comment by pogdin** [comment]
Hi, can you share the yaml you are using to create the Splunk deployment?

**Comment by prakashmirji** [comment]
we are using https://github.com/splunk/splunk-operator/releases/download/1.0.0/splunk-operator-install.yaml. Just modified the docker image path and added CLUSTER_DOMAIN ENV. Attached is the file for FYI
[splunk-operator-install.zip](https://github.com/splunk/splunk-operator/files/6366621/splunk-operator-install.zip)

**Comment by pogdin** [comment]
Thanks.  What I'm asking for is the definition of the cluster in yaml.  Like:

```
apiVersion: enterprise.splunk.com/v1
kind: ClusterMaster
metadata:
  name: cm-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  licenseMasterRef:
    name: lm-example
---
apiVersion: enterprise.splunk.com/v1
kind: IndexerCluster
metadata:
  name: idxc-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  replicas: 3
  clusterMasterRef:
    name: cm-example
  licenseMasterRef:
    name: lm-example
```

**Comment by prakashmirji** [comment]
```
---
apiVersion: enterprise.splunk.com/v1
kind: ClusterMaster
metadata:
  name: cm
  namespace: splunk
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  etcVolumeStorageConfig:
    storageClassName: openebs-hostpath
    #storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageClassName: openebs-hostpath
    #storageCapacity: 25Gi
---
apiVersion: enterprise.splunk.com/v1
kind: IndexerCluster
metadata:
  name: morgan
  namespace: splunk
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterMasterRef:
    name: cm
  replicas: 3
  etcVolumeStorageConfig:
    storageClassName: openebs-hostpath
    storageCapacity: 10Gi
  varVolumeStorageConfig:
    storageClassName: openebs-hostpath
    storageCapacity: 100Gi
---
apiVersion: enterprise.splunk.com/v1
kind: SearchHeadCluster
metadata:
  name: morgan
  namespace: splunk
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterMasterRef:
    name: cm
  replicas: 3
  etcVolumeStorageConfig:
    storageClassName: openebs-hostpath
    #storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageClassName: openebs-hostpath

**Comment by pogdin** [comment]
Thanks.  Did you do a cluster scope install by chance? https://github.com/splunk/splunk-operator/blob/1.0.0/docs/Install.md#admin-installation-for-all-namespaces

**Comment by prakashmirji** [comment]
It looks something like below.

kubectl get RoleBinding -n splunk
NAME                                ROLE                                     AGE
hpecp-tenant-11-admin-bhgqm         Role/hpecp-tenant-11-admin-vjz87         36h
hpecp-tenant-11-member-qsn2z        Role/hpecp-tenant-11-member-fjlgz        36h
hpecp-tenant-11-sa-24bf9            Role/hpecp-tenant-11-sa-bgz7b            36h
kiali                               Role/kiali                               36h
splunk:operator:namespace-manager   Role/splunk:operator:namespace-manager   7h18m

kubectl get RoleBinding -n splunk splunk:operator:namespace-manager -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"name":"splunk:operator:namespace-manager","namespace":"splunk"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"splunk:operator:namespace-manager"},"subjects":[{"kind":"ServiceAccount","name":"splunk-operator"}]}
  creationTimestamp: "2021-04-23T10:40:45Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:roleRef:
        f:apiGroup: {}
        f:kind: {}
        f:name: {}
      f:subjects: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-04-23T10:40:45Z"
  name: splunk:operator:namespace-manager
  namespace: splunk
  resourceVersion: "438388"
  uid: 8688bedf-7212-4036-aa80-b93312b702f3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: splunk:operator:namespace-manager
subjects:
- kind: ServiceAccount
  name: splunk-operator

**Comment by pogdin** [comment]
We've added the following in the link above "Note: The Admin Installation for all Namespaces is not functioning as intended with this release. We're tracking the issue here. Check the status of the issue before attempting to use these instructions."

Otherwise, your cluster setup looks fine.  Try again without cluster scoped install.

**Comment by prakashmirji** [comment]
okay. Just to be on same page, I should remove below resource and reinstall the operator? Otherwise can share the flow?
```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: splunk:operator:namespace-manager
subjects:
- kind: ServiceAccount
  name: splunk-operator
  namespace: splunk-operator
roleRef:
  kind: ClusterRole
  name: splunk:operator:namespace-manager
  apiGroup: rbac.authorization.k8s.io
```

**Comment by pogdin** [comment]
Yes, please try again with a per namespace or default namespace install.

**Comment by prakashmirji** [comment]
Okay. Bit confused. we have installed everything in single namespace called 'splunk'. We are using this operator https://github.com/splunk/splunk-operator/releases/download/1.0.0/splunk-operator-install.yaml and other objects are also in the same namespace. Can you mention what to change to avoid cluster scope install?

**Comment by gaurav-splunk** [comment]
@prakashmirji 
Can you please also share the yaml file/definition for Role and Service Account you are using?

**Comment by prakashmirji** [comment]
we are not using separate yaml/definition file for Role and Service Account creation. Whatever is present in the operator yaml, we are just applying it using kubectl. But operator yaml file has RoleBinding definition at line no 12066 in splunk-operator-install.yaml

**Comment by gaurav-splunk** [comment]
Hi @prakashmirji 
I created a namespace `splunk` in my env. and then changed the splunk-operator-install.yaml in following way and then deployed CM and Idxc, and it worked fine for me. I have marked the changes I made with `<<<< Added this <<<<<<` line.
I am just pasting the relevant content from the yaml file I have - 
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: splunk-operator
  namespace: splunk <<<< Added this <<<<<<
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: splunk:operator:namespace-manager
  namespace: splunk <<<< Added this <<<<<<
.....
.....
- apiGroups:
  - enterprise.splunk.com
  resources:
  - '*'
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: splunk:operator:namespace-manager
  namespace: splunk  <<<< Added this <<<<<<
subjects:
- kind: ServiceAccount
  name: splunk-operator
  namespace: splunk  <<<< Added this <<<<<<
roleRef:
  kind: Role
  name: splunk:operator:namespace-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-operator
  namespace: splunk  <<<< Added this <<<<<<
spec:
  replicas: 1
  selector:
    matchLabels:
      name: splunk-operator
  template:
    metadata:
      labels:
        name: splunk-operator
    spec:
      serviceAccountName: splunk-operator
      containers:
      - name: splunk-operator
        image: docker.io/splunk/splunk-operator:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "splunk-operator"
        - name: RELATED_IMAGE_SPLUNK_ENTERPRISE
          value: "docker.io/splunk/splunk:8.1.3"
```
Let me know if you find this relevant and if it works for you.

**Comment by rajeshvijayarajan** [comment]
Thanks @gaurav-splunk ! 
We made these edits to the splunk-operator-install.yml, but it didn't seem to help. Inspecting the logs of the splunk-operator, we still see this issue:
`{"level":"error","ts":1619241360.8012228,"logger":"splunk.reconcile.Reconcile","msg":"Reconciliation requeued","Group":"enterprise.splunk.com","Version":"v1","Kind":"ClusterMaster","Namespace":"splunk","Name":"cm","RequeueAfter":5,"error":"Get https://splunk-cm-cluster-master-service.splunk.svc.cluster.local:8089/services/cluster/config?count=0&output_mode=json: read tcp 10.192.3.45:40264->10.104.192.150:8089: read: connection reset by peer","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgo/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/splunk/splunk-operator/pkg/splunk/controller.splunkReconciler.Reconcile\n\tsplunk-operator/pkg/splunk/controller/controller.go:125\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tgo/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
`
The other thing I see is interesting error messages and warnings in the splunkd.log of the Cluster Master. I've attached them here for your perusal.
[splunkd.log](https://github.com/splunk/splunk-operator/files/6369040/splunkd.log)

**Comment by pogdin** [comment]
The other alternative here is to not modify the splunk-operator-install.yaml at all just:

` kubectl create ns splunk`
`kubectl config set-context --current --namespace=splunk`
`kubectl apply -f https://github.com/splunk/splunk-operator/releases/download/1.0.0/splunk-operator-install.yaml`

I used a modified version of your Splunk cluster definition
````
apiVersion: enterprise.splunk.com/v1
kind: ClusterMaster
metadata:
  name: cm
  #namespace: splunk
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  etcVolumeStorageConfig:
    #storageClassName: openebs-hostpath
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    #storageClassName: openebs-hostpath
    storageCapacity: 25Gi
---
apiVersion: enterprise.splunk.com/v1
kind: IndexerCluster
metadata:
  name: morgan
  #namespace: splunk
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterMasterRef:
    name: cm
  replicas: 3
  etcVolumeStorageConfig:
    #storageClassName: openebs-hostpath
    storageCapacity: 10Gi
  varVolumeStorageConfig:
    #storageClassName: openebs-hostpath
    storageCapacity: 100Gi
````
And everything seems to come up fine in the Splunk namespace

````
bash-3.2$ kubectl describe pod splunk-morgan-indexer-0
Name:         splunk-morgan-indexer-0
Namespace:    splunk
Priority:     0
````
