### ISSUE TITLE
ClusterMaster doesn't downgrade itself to a slave, when using a LicenseMaster

### ISSUE THREAD

**Issue by rajeshvijayarajan** [splunk/splunk-operator#321]
Hello,

I configured a LicenseMaster in my cluster with a ConfigMap built using the Dev/Test license file (50 GB/day). 
Here's the definition:

```
apiVersion: enterprise.splunk.com/v1
kind: LicenseMaster
metadata:
  name: morgan-license
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  etcVolumeStorageConfig:
    storageClassName: openebs-hostpath
  varVolumeStorageConfig:
    storageClassName: openebs-hostpath
  volumes:
    - name: licenses
      configMap:
        name: splunk-licenses
  licenseUrl: /mnt/licenses/enterprise.lic
  clusterMasterRef:
    name: cm
```

My understanding is that the ClusterMater is the only place I need to configure the license, so here's the latest ClusterMaster definition:

```
apiVersion: enterprise.splunk.com/v1
kind: ClusterMaster
metadata:
  name: cm
  #namespace: splunk
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  etcVolumeStorageConfig:
    storageClassName: openebs-hostpath
    #storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageClassName: openebs-hostpath
    #storageCapacity: 25Gi
  licenseMasterRef:
    name: morgan-license
```

I cleaned up the namespace and started afresh with these new definitions. Is there a particular sequence to creating these objects? 

The LicenseMaster comes up fine, however the ClusterMaster keeps restarting with the following messages:

```
TASK [splunk_common : Check Splunk instance is running] ************************
[0;32mok: [localhost][0m
Tuesday 27 April 2021  04:21:08 +0000 (0:00:00.642)       0:00:24.151 *********
[1;30mFAILED - RETRYING: Set node as license slave (60 retries left).[0m
[1;30mFAILED - RETRYING: Set node as license slave (59 retries left).[0m
[1;30mFAILED - RETRYING: Set node as license slave (58 retries left).[0m
[1;30mFAILED - RETRYING: Set node as license slave (57 retries left).[0m
[1;30mFAILED - RETRYING: Set node as license slave (56 retries left).[0m
[1;30mFAILED - RETRYING: Set node as license slave (55 retries left).[0m
[1;30mFAILED - RETRYING: Set node as license slave (54 retries left).[0m
[1;30mFAILED - RETRYING: Set node as license slave (53 retries left).[0m
[1;30mFAILED - RETRYING: Set node as license slave (52 retries left).[0m
[1;30mFAILED - RETRYING: Set node as license slave (51 retries left).[0m
```

All the retries fail. Any pointers on how to resolve this?

Cheers!

**Comment by pogdin** [comment]
Hello, you don't need to make reference to the CM in the LM definition.  Remove these lines
````
apiVersion: enterprise.splunk.com/v1
kind: LicenseMaster
metadata:
  name: morgan-license
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  etcVolumeStorageConfig:
    storageClassName: openebs-hostpath
  varVolumeStorageConfig:
    storageClassName: openebs-hostpath
  volumes:
    - name: licenses
      configMap:
        name: splunk-licenses
  licenseUrl: /mnt/licenses/enterprise.lic
  clusterMasterRef: <<<<<<<<<<<<<<<<<<<
    name: cm <<<<<<<<<<<<<<<<<<<
````
