### ISSUE TITLE
Changing the service of StandAlone to LoadBalancer

### ISSUE THREAD

**Issue by rajeshvijayarajan** [splunk/splunk-operator#324]
Hello,

I reconfigured my StandAlone deployment to change the service type to LoadBalancer. Please find the yml below:

```
apiVersion: enterprise.splunk.com/v1
kind: Standalone
metadata:
  name: gogen-test
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  etcVolumeStorageConfig:
    storageClassName: openebs-hostpath
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageClassName: openebs-hostpath
    storageCapacity: 500Gi
  volumes:
    - name: licenses
      configMap:
        name: splunk-licenses
  licenseUrl: /mnt/licenses/Splunk.License
  serviceTemplate:
    spec:
      type: LoadBalancer
  resources:
    requests:
      cpu: "36"
      memory: "128Gi"
    limits:
      cpu: "36"
      memory: "128Gi"  
```
The services come up correctly:

```
C:\Users\Administrator\Downloads\splunk-yml>kubectl get svc
NAME                                        TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                                                       AGE
splunk-gogen-test-standalone-headless       ClusterIP      None            <none>         8000/TCP,8088/TCP,8089/TCP,9997/TCP                           39m
splunk-gogen-test-standalone-service        LoadBalancer   10.110.255.30   10.10.35.241   8000:30017/TCP,8088:30463/TCP,8089:31766/TCP,9997:31852/TCP   39m
splunk-morgan-monitoring-console-headless   ClusterIP      None            <none>         8000/TCP,8088/TCP,8089/TCP,9997/TCP                           38m
splunk-morgan-monitoring-console-service    LoadBalancer   10.105.142.44   10.10.35.242   8000:32543/TCP,8088:31783/TCP,8089:30616/TCP,9997:30725/TCP   38m
splunk-operator-metrics                     ClusterIP      10.104.73.55    <none>         8383/TCP,8686/TCP                                             20h
```
However, am just not able to access the standalone-service using the Load Balancer provided IP of 10.10.35.241. The splunk UI is not accessible at http://10.10.35.241:8000. Interestingly enough, the montioring-console-service works perfectly fine and is available at http://10.10.35.242:8000. 

I don't see any issues in the logs of the pods or the operator. Also, did a sanity check using port-forwarding and the standalone pod is perfectly health, and am able to login through UI.

Do you have any insights on why we are not able to access the UI of the standalone instance through the Load Balancer provided IP? Any ideas on how to troubleshoot this?

Cheers!
Rajesh
