### ISSUE TITLE
Stacking of licenses

### ISSUE THREAD

**Issue by rajeshvijayarajan** [splunk/splunk-operator#326]
Hello,

I have a couple of licenses that I need to stack for my cluster. Can you provide me some guidance on how to achieve this?

- Would it mean creating two LicenseMasters each with a different ConfigMap (license file)? If so, how do you specify this in the licenseMasterRef in the ClusterMaster?

(OR)

- Can a single LicenseMaster be configured with two Configmaps / LicenseUrls ?

Cheers!
Rajesh

**Comment by pogdin** [comment]
You can add multiple licenses via configmap

`kubectl create configmap splunk-licenses-test --from-file=enterprise1.lic,enterprise2.lic`

Then separate by comma in the YAML file

````
apiVersion: enterprise.splunk.com/v1
kind: LicenseMaster
metadata:
  name: lm-test-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  volumes:
    - name: licenses
      configMap:
        name: splunk-licenses-test
  licenseUrl: "/mnt/licenses/enterprise1.lic,/mnt/licenses/enterprise2.lic"
````
