### ISSUE TITLE
Provide Example for using Local Persistent Volumes with SOK

### ISSUE THREAD

**Issue by crawdaddy18** [splunk/splunk-operator#34]
Please provide an example of how to configure the Splunk on Kubernetes to work with Local Persistent Volumes.

Through personal testing, I have set up a "local-storage" StorageClass:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```
However, any attempts to use this SC leaves the Pods in a "Pending" status which may be related to no claim actually being made.

Multiple attempts have been made to modify the splunk-operator by downloading the YAML from the tiny.cc URL and the SplunkEnterprise YAML, but so far no success.

**Comment by mikedickey** [comment]
Hi Chris, I haven't tried using local volumes yet but agree it's something we need to do and document. I do know that just adding a StorageClass is not sufficient. You'd need to manually create a bunch of PVs on your servers for it to use, unless you are using something else to do it for you. Have you tried this? https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner

**Comment by crawdaddy18** [comment]
@mikedickey I did try the link and did get it set up, but I don't think that was sufficient for what I was doing because I had only 2 EC2 instances and I believe that sidecar creates only 1 PV for each machine.

Here is what I did to get things working (EC2 instance with 1 500GB drive)

On each host I created directories in /mnt/disk by running this script:
```
#!/bin/bash

for i in {1..10}
do
  DIRNAME="vol${i}"
  mkdir -p /mnt/disk/$DIRNAME 
  chcon -Rt svirt_sandbox_file_t /mnt/disk/$DIRNAME
  chmod 777 /mnt/disk/$DIRNAME
done
```

In addition to the StorageClass above, here are my PV definitions:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv10
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disk/vol10
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-10-20-1-108.us-west-2.compute.internal

---
```
I have 10 of these, the file actually starts with my-local-pv1.  This is only for 1 box, I did the same for a second box and only changed the IP.  I have 20 PVs ready in total, each 50GiB

I added this to my cluster YAML under spec:
```
  storageClassName: local-storage
  resources:
    splunkIndexerStorage: 50Gi
```

It all worked after that:
NAME                                              READY   STATUS    RESTARTS   AGE
splunk-dfscluster-cluster-master-0                1/1     Running   0          8m13s
splunk-dfscluster-deployer-0                      1/1     Running   0          8m13s
splunk-dfscluster-indexer-0                       1/1     Running   0          8m13s
splunk-dfscluster-indexer-1                       1/1     Running   0          8m13s
splunk-dfscluster-indexer-2                       1/1     Running   0          8m13s
splunk-dfscluster-license-master-0                1/1     Running   0          8m13s
splunk-dfscluster-search-head-0                   1/1     Running   0          8m12s
splunk-dfscluster-search-head-1                   1/1     Running   1          8m12s
splunk-dfscluster-search-head-2                   1/1     Running   1          8m12s
splunk-dfscluster-spark-master-5949c94dbc-llbqc   1/1     Running   0          8m13s
splunk-dfscluster-spark-worker-d8fbf84d4-65pps    1/1     Running   0          8m13s
splunk-dfscluster-spark-worker-d8fbf84d4-b2skw    1/1     Running   0          8m13s
splunk-dfscluster-spark-worker-d8fbf84d4-gzw92    1/1     Running   0          8m13s
splunk-operator-7b86d8cb8c-5ns45                  1/1     Running   0          13h
```
