### ISSUE TITLE
Support SmartStore S3 encryption settings for Standalone/ClusterMaster deployments.

### ISSUE THREAD

**Issue by kmott** [splunk/splunk-operator#347]
## Summary

We are using the Splunk Operator with the following `smartstore` spec config, but unfortunately, our S3 buckets all require encryption:

```
---
apiVersion: enterprise.splunk.com/v1
kind: ClusterMaster
metadata:
   [ ... ]
spec:
  smartstore:
    defaults:
      remotePath: $_index_name
      volumeName: my-test-s3-storage
    volumes:
      - name: my-test-s3-storage
        path: my-test-s3-storage/kmott-test
        endpoint: https://s3.us-west-2.amazonaws.com
        secretRef: my-test-s3-storage-app-creds
```

With the config above, we would see messages in the `_internal` index from the `S3Client` that it could not write to the bucket (`PermissionDenied`).

To alleviate this, we modified [this line](https://github.com/splunk/splunk-operator/blob/develop/pkg/splunk/enterprise/configuration.go#L883) to hard-code `remote.s3.encryption = sse-s3`, which works with our deployment (for now).

It might be nice for others if the `remote.s3.encryption*` settings can be configured through the `smartstore` spec.

## Alternatives

We tried to deploy our SmartStore config using a `Splunk App`, but ran into several issues where the configuration settings were not properly deployed to the IndexerClusters from the ClusterMaster--we mainly saw errors like this (note that the access/secret keys do actually exist in the indexes.conf file):

```
Problem parsing indexes.conf: Cannot load IndexConfig: Unable to load remote volume "my-test-s3-storage" of scheme "s3" referenced by index "main": Could not find access_key and/or secret_key in a configuration file, in environment variables or via the AWS metadata endpoint.
Validating databases (splunkd validatedb) failed with code '1'.
```

Note that we are tracking this issue separately.

**Comment by pogdin** [comment]
Thanks for the feature request! While the CRD-based SmartStore configuration gives us a method to get up and running quickly, I don't believe we'll be adding new capabilities to it as we've discovered there are too many stanzas in indexes.conf and we would rather have the App framework (and future improvements to this) as the system of record for the cluster.  In this case, I would suggest we dig further into why the App approach is not working.  You *should* be able to simply copy the contents of the `splunk-operator` App that is working and generated by the CRD-approach and distribute it to the cluster given the [methods](https://github.com/splunk/splunk-operator/blob/develop/docs/Examples.md#installing-splunk-apps) we currently enable for this.  If this is still not working, please post what you can here for your CM and IDXC yaml and SmartStore App and we'll try to reproduce.

**Comment by kmott** [comment]
Thanks for taking the time to look at the Splunk App issue.  Here's my configuration--the error we see is from above:

```
Problem parsing indexes.conf: Cannot load IndexConfig: Unable to load remote volume "my-test-s3-storage" of scheme "s3" referenced by index "main": Could not find access_key and/or secret_key in a configuration file, in environment variables or via the AWS metadata endpoint.
Validating databases (splunkd validatedb) failed with code '1'.
```

The `indexers.conf` looks like this in my `smart-store.tgz` file, which I create as a ConfigMap in the CM (in this case, I only want the `main` index to use the S3 SmartStore config):

```
[default]
repFactor = auto
maxDataSize = auto

[volume:my-test-s3-storage]
storageType = remote
path = s3://kmott-test
remote.s3.access_key = < ... >
remote.s3.secret_key = < ... >
remote.s3.endpoint = https://my-test-s3-storage.s3.us-west-2.amazonaws.com
remote.s3.encryption = sse-s3

[main]
remotePath = volume:my-test-s3-storage/defaultdb
homePath   = $SPLUNK_DB/defaultdb/db
coldPath   = $SPLUNK_DB/defaultdb/colddb
thawedPath = $SPLUNK_DB/defaultdb/thaweddb
```

My `app.conf` in the smart-store.tgz file looks like this:

```
[install]
is_configured = 0
state = enabled

[ui]
is_visible = 1
label = Splunk SmartStore

[launcher]
author = Kyle Mott
description = Splunk SmartStore
version = 1.6
```

And here's my ClusterMaster yaml:

```
---
apiVersion: enterprise.splunk.com/v1
kind: ClusterMaster
metadata:
  name: splunk-cm
  annotations:
    prometheus.io/scrape: 'true'
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  volumes:
    - name: apps
      configMap:
        name: splunk-apps
  defaults: |-
    splunk:
      apps_location:
        - "/mnt/apps/smart-store.tgz"
```

And here's the IndexerCluster yaml:

```
---
apiVersion: enterprise.splunk.com/v1
kind: IndexerCluster
metadata:
  name: splunk-idc
  annotations:
    prometheus.io/scrape: 'true'
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  clusterMasterRef:
    name: splunk-cm
  replicas: 1
  licenseMasterRef:
    name: splunk-lic
```

If you are able to reproduce, that would be fantastic--other than modifying the Operator, I have not yet been able to get the SmartStore config to work delivered as a Splunk App when deployed using the Splunk Operator.

**Comment by pogdin** [comment]
Is the name of your file in the `smart-store.tgz` App `indexers.conf` or `indexes.conf` ?

**Comment by kmott** [comment]
We moved the app to `/opt/splunk/etc/apps` on the `ClusterMaster`, and it does work (we can access the remote S3 store with encryption).

However, if we try that same thing on the `IndexerCluster(s)`, it does not work.  Splunkd always reports this error when trying to start:

```
Splunk> Winning the War on Error

Checking prerequisites...
        Checking http port [8000]: open
        Checking mgmt port [8089]: open
        Checking appserver port [127.0.0.1:8065]: open
        Checking kvstore port [8191]: open
        Checking configuration... Done.
        Checking critical directories...        Done
        Checking indexes...
        
Problem parsing indexes.conf: Cannot load IndexConfig: Unable to load remote volume "my-test-s3-storage" of scheme "s3" referenced by index "main": Could not find access_key and/or secret_key in a configuration file, in environment variables or via the AWS metadata endpoint.
Validating databases (splunkd validatedb) failed with code '1'.  If you cannot resolve the issue(s) above after consulting documentation, please file a case online at http://www.splunk.com/page/submit_issue
```

If you have any suggestions, let me know--since it's not recommended to add the support for the S3 encryption directly to the splunk-operator's app (via the `smartstore` spec), I'm a bit stuck with getting our SmartStore deployment up and running.

---

More information from Splunk Support:

> Issue with Customer (GitHub issue 347) and AWS S2 config. The S2 App is in master-apps and looks correct.  The indexers are not reading the access and secret keys - that is the error.  On the CM - because it was not restarting - we moved the S2 App from master-apps to apps and restarted.  We were able to use the S3 access commands (splunk cmd splunkd rfs -- ls).
>
> On the indexers, we were seeing bundle errors for the S3 volume (no access or secret keys).  We added the S2 App to apps on the indexer and the bundle successfully downloaded.  The missing access and secret keys persist and are keeping splunkd from starting

**Comment by pogdin** [comment]
Hi, can you give me a Splunk Support Case number please?  Thanks.

**Comment by gaurav-splunk** [comment]
I tried reproducing it at my end but haven't been. able to repro it yet. Though I enabled Debug logging on couple of component on one of the indexer and it does spit out some useful logs after startup such as these - 
```
05-22-2021 03:41:21.150 +0000 DEBUG ConfigEncryptor - Encrypting indexes.conf/[volume:my-test-s3-storage]/remote.s3.secret_key
05-22-2021 03:41:21.151 +0000 DEBUG ConfigEncryptor - indexes.conf/[volume:my-test-s3-storage]/remote.s3.secret_key not found.
05-22-2021 03:41:21.151 +0000 DEBUG ConfigEncryptor - Encrypting indexes.conf/[volume:my-test-s3-storage]/remote.s3.access_key
05-22-2021 03:41:21.151 +0000 DEBUG ConfigEncryptor - indexes.conf/[volume:my-test-s3-storage]/remote.s3.access_key not found.
05-22-2021 03:41:21.151 +0000 DEBUG ConfigEncryptor - Encrypting indexes.conf/[volume:my-test-s3-storage]/remote.s3.kms.secret_key
05-22-2021 03:41:21.151 +0000 DEBUG ConfigEncryptor - indexes.conf/[volume:my-test-s3-storage]/remote.s3.kms.secret_key not found.
05-22-2021 03:41:21.151 +0000 DEBUG ConfigEncryptor - Encrypting indexes.conf/[volume:my-test-s3-storage]/remote.s3.kms.access_key
05-22-2021 03:41:21.151 +0000 DEBUG ConfigEncryptor - indexes.conf/[volume:my-test-s3-storage]/remote.s3.kms.access_key not found.
05-22-2021 03:41:21.152 +0000 DEBUG ConfigEncryptor - server.conf/[general]/legacyCiphers set to decryptOnly
05-22-2021 03:41:21.152 +0000 WARN  ConfigEncryptor - Decryption operation failed: AES-GCM Decryption failed!
05-22-2021 03:41:21.152 +0000 DEBUG ConfigEncryptor - server.conf/[general]/legacyCiphers set to decryptOnly
05-22-2021 03:41:21.152 +0000 WARN  ConfigEncryptor - Decryption operation failed: AES-GCM Decryption failed!
05-22-2021 03:41:21.152 +0000 DEBUG AwsCredentials - using signature version=v4 for stanza=
05-22-2021 03:41:21.152 +0000 DEBUG AwsCredentials - S3ClientProps did not find credentials in my-test-s3-storage, will try previously saved default credential
05-22-2021 03:41:21.152 +0000 DEBUG AwsCredentials - S3ClientProps did not find default credentials, will try env variables ...
05-22-2021 03:41:21.152 +0000 DEBUG AwsCredentials - S3ClientProps did not find credentials in env variables
05-22-2021 03:41:21.152 +0000 INFO  AwsCredentials - TaskAwsCredentials are not setup as the AWS_CONTAINER_CREDENTIALS_RELATIVE_URI is empty; falling back to InstanceAwsCredentials.
05-22-2021 03:41:21.152 +0000 DEBUG AwsCredentials - S3ClientProps did not find credentials in Task IAM role metadata endpoint
05-22-2021 03:41:21.152 +0000 DEBUG AwsCredentials - getting IAM role via url=http://169.254.169.254/latest/meta-data/iam/security-credentials/, attempt=1
05-22-2021 03:41:21.154 +0000 DEBUG AwsCredentials - IamAwsCredentials::updateCredentials uri=http://169.254.169.254/latest/meta-data/iam/security-credentials/<redacted_role>, attempt=1, statusCode=200, statusDescription=OK
05-22-2021 03:41:21.154 +0000 DEBUG AwsCredentials - IamAwsCredentials, updating credential expiration=1621674258
05-22-2021 03:41:21.154 +0000 DEBUG AwsCredentials - IamAwsCredentials, updating credentials, using IAM role=<redacted_role>
05-22-2021 03:41:21.154 +0000 DEBUG AwsCredentials - new credentials {access_key="ASI...WSK", secret_key="RKGF...Ytfn", token="IQoJ...XQ=="}
05-22-2021 03:41:21.154 +0000 DEBUG AwsCredentials - S3ClientProps using credentials from IAM role of instance
```
So at this point I am not sure if your IAM roles are set or not on indexers, but I would suggest setting the components `AwsCredentials` and `ConfigEncryptor` to debug mode on one of the indexers and paste the splunkd.log just after startup to see what does it show.

Another thing which I am not sure is this - 
> We moved the app to /opt/splunk/etc/apps on the ClusterMaster, and it does work (we can access the remote S3 store with encryption).
If you have deployed an app on CM then ansible just installs the app at etc/apps on CM and then copies over that to master-apps. So they should basically be same.

**Comment by rajeshvijayarajan** [comment]
I have run into a scenario where I need to specify the region to be used i.e. the field remote.s3.auth_region in indexes.conf, which  I don't see in the SmartStore spec, so I presume creating an app is the only way to go? Please advise.

**Comment by kmott** [comment]
> I have run into a scenario where I need to specify the region to be used i.e. the field remote.s3.auth_region in indexes.conf, which I don't see in the SmartStore spec, so I presume creating an app is the only way to go? Please advise.

@rajeshvijayarajan we ended up using a solution like this (we are using ClusterMaster), where the Splunk App provides additional configuration of SmartStore via conf-merge.

```
---
apiVersion: enterprise.splunk.com/v1
kind: ClusterMaster
metadata:
  name: splunk-cm
  annotations:
    prometheus.io/scrape: 'true'
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  etcVolumeStorageConfig:
    storageClassName: encrypted-gp2
    storageCapacity: 10Gi
  varVolumeStorageConfig:
    storageClassName: encrypted-gp2
    storageCapacity: 1024Gi
  volumes:
    - name: apps
      configMap:
        name: splunk-apps
  defaults: |-
    splunk:
      apps_location:
        - "/mnt/apps/smart-store.tgz"
  smartstore:
    defaults:
      remotePath: $_index_name
      volumeName: splunk-smart-storage
    volumes:
      - name: splunk-smart-storage
        path: splunk-smart-storage/production
        endpoint: https://s3.us-west-2.amazonaws.com
        secretRef: splunk-smart-storage-secrets
    indexes:
      - name: main
        remotePath: $_index_name
        volumeName: splunk-smart-storage
        hotlistRecencySecs: 86402
        maxGlobalDataSizeMB: 1000000
        maxGlobalRawDataSizeMB: 1100001
```

And then, the `smart-store.tgz` file contains and `indexes.conf` that looks like this--you should be able to add any of the arbitrary `remote.s3.*` config options to the volume definition, and have it apply to the volume:

```
[volume:splunk-smart-storage]
path = s3://production
remote.s3.encryption = sse-s3
```
