### ISSUE TITLE
Unusable Filesystem error when launching on Fargate EKS

### ISSUE THREAD

**Issue by troyfontaine** [splunk/splunk-operator#364]
I'm trying to test out launching a stand-alone splunk host on EKS Fargate and the Ansible playbook is failing at the step `splunk_common : Start Splunk via CLI` with the below error:

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "cmd": [
        "/opt/splunk/bin/splunk",
        "start",
        "--accept-license",
        "--answer-yes",
        "--no-prompt"
    ],
    "delta": "0:00:06.803097",
    "end": "2021-06-02 21:46:44.432315",
    "rc": 10,
    "start": "2021-06-02 21:46:37.629218"
}

STDOUT:


Splunk> 4TW

Checking prerequisites...
        Checking http port [8000]: open
        Checking mgmt port [8089]: open
        Checking appserver port [127.0.0.1:8065]: open
        Checking kvstore port [8191]: open
        Checking configuration... Done.
New certs have been generated in '/opt/splunk/etc/auth'.
        Checking critical directories...        Done
        Checking indexes...
                Creating: /opt/splunk/var/lib/splunk
                Creating: /opt/splunk/var/run/splunk
                Creating: /opt/splunk/var/run/splunk/appserver/i18n
                Creating: /opt/splunk/var/run/splunk/appserver/modules/static/css
                Creating: /opt/splunk/var/run/splunk/upload
                Creating: /opt/splunk/var/run/splunk/search_telemetry
                Creating: /opt/splunk/var/spool/splunk
                Creating: /opt/splunk/var/spool/dirmoncache
                Creating: /opt/splunk/var/lib/splunk/authDb
                Creating: /opt/splunk/var/lib/splunk/hashDb


STDERR:

homePath='/opt/splunk/var/lib/splunk/audit/db' of index=_audit on unusable filesystem.
Validating databases (splunkd validatedb) failed with code '1'.  If you cannot resolve the issue(s) above after consulting documentation, please file a case online at http://www.splunk.com/page/submit_issue


MSG:

non-zero return code
```

My configuration is as follows for the server:

```
apiVersion: enterprise.splunk.com/v1
kind: Standalone
metadata:
  name: lab
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  etcVolumeStorageConfig:
    ephemeralStorage: true
  varVolumeStorageConfig:
    ephemeralStorage: true
```

Fargate EKS does cap the storage either at 20GB or 30GB (the documentation contradicts itself).  Would the lack of ephemeral storage space be the cause of this error or would it come down to some sort of file system on the host being the issue?  Thanks!

**Comment by rajeshvijayarajan** [comment]
I did run into this as well. In my case, it had to do with the filesystem on the host. The link below provides more insight:
https://docs.splunk.com/Documentation/Splunk/8.2.0/Troubleshooting/FSLockingIssues

**Comment by pogdin** [comment]
Can confirm.  I'm using:
````
apiVersion: enterprise.splunk.com/v1
kind: Standalone
metadata:
  name: s1
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  etcVolumeStorageConfig:
    ephemeralStorage: true
  varVolumeStorageConfig:
    ephemeralStorage: true
  defaults: |-
    splunk:
      launch:
        OPTIMISTIC_ABOUT_FILE_LOCKING: 1
````
The single instance will come up but this will break our implementation of the Monitoring Console pod.
