### ISSUE TITLE
Cannot use custom HEC tokens with Splunk Operator deployment.

### ISSUE THREAD

**Issue by kmott** [splunk/splunk-operator#372]
## Summary

We have a Splunk Operator deployment (v1.0.0), with several custom HEC tokens.  These HEC tokens are scoped to a specific indexes as they represent different environments, like `logs-staging`.

We created HEC tokens using the Splunk UI on the `IndexerCluster` (alongside the default HEC token deployed by the Operator automagically).

Here's an example HEC token settings:

```
                   Name: logs-staging_hec_token
       Selected Indexes: logs-staging, metrics
          Default Index: logs-staging
Indexer Acknowledgement: Disabled
                  Token: dead-beef
```

When we try to use that custom HEC token in a simple `curl` call to the HEC endpoint, it throws messages like this (sometimes it does work intermittently, though):

```
curl -X POST https://splunk-hec.ingest.mydomain.com/services/collector -H "Authorization: Splunk dead-beef" -H 'Content-Type: application/json' -d '{"event":"Hello, World2!"}'
{"text":"Invalid token","code":4}
```

No matter if we specify the `"sourcetype":"manual"` or `"index":"logs-staging"` in the `curl` call, it doesn't work reliably.

## More Information

I was poking around the IndexerCluster pod instances, and I did notice quite a few messages like this (but it unfortunately doesn't say why it was unable to process the http input, `parsing_err` is empty):

```
06-11-2021 17:50:40.896 +0000 ERROR HttpInputDataHandler - Failed processing http input, token name=n/a, channel=n/a, source_IP=10.0.14.172, reply=4, events_processed=0, http_input_body_size=7453, parsing_err=""
06-11-2021 17:50:41.247 +0000 ERROR HttpInputDataHandler - Failed processing http input, token name=n/a, channel=n/a, source_IP=10.0.44.103, reply=4, events_processed=0, http_input_body_size=30670, parsing_err=""
06-11-2021 17:50:41.415 +0000 ERROR HttpInputDataHandler - Failed processing http input, token name=n/a, channel=n/a, source_IP=10.0.14.172, reply=4, events_processed=0, http_input_body_size=16833, parsing_err=""
06-11-2021 17:50:43.602 +0000 ERROR HttpInputDataHandler - Failed processing http input, token name=n/a, channel=n/a, source_IP=10.0.14.172, reply=4, events_processed=0, http_input_body_size=25396, parsing_err=""
```

## Repro Steps

1. Setup a port-forward to the cm-indexer-service:

```
k8s port-forward svc/splunk-cm-indexer-service -n splunk 8000:8000
```

2. Log in to the port forward UI, and go to `Settings` -> `Data Inputs` -> `HTTP Event Collector`
3. Create a new HEC token (test), scoped to a specific index (`test-index` ONLY, also set as DEFAULT)
4. Take the newly created token, and attempt to manually inject some data (which somewhat works, albeit intermittently):

```
curl --silent -X POST https://splunk-hec.mydomain.com/services/collector -H "Authorization: Splunk ${TEST_HEC_TOKEN}" -d '{"event":"Hello World (test HEC)"}' | jq -r ''
{
  "text": "Success",
  "code": 0
}
curl --silent -X POST https://splunk-hec.mydomain.com/services/collector -H "Authorization: Splunk ${TEST_HEC_TOKEN}" -d '{"event":"Hello World (test HEC)"}' | jq -r ''
{
  "text": "Success",
  "code": 0
}
curl --silent -X POST https://splunk-hec.mydomain.com/services/collector -H "Authorization: Splunk ${TEST_HEC_TOKEN}" -d '{"event":"Hello World (test HEC)"}' | jq -r ''
{
  "text": "Success",
  "code": 0
}
curl --silent -X POST https://splunk-hec.mydomain.com/services/collector -H "Authorization: Splunk ${TEST_HEC_TOKEN}" -d '{"event":"Hello World (test HEC)"}' | jq -r ''
{
  "text": "Invalid token",
  "code": 4
}
curl --silent -X POST https://splunk-hec.mydomain.com/services/collector -H "Authorization: Splunk ${TEST_HEC_TOKEN}" -d '{"event":"Hello World (test HEC)"}' | jq -r ''
{
  "text": "Invalid token",
  "code": 4
}
curl --silent -X POST https://splunk-hec.mydomain.com/services/collector -H "Authorization: Splunk ${TEST_HEC_TOKEN}" -d '{"event":"Hello World (test HEC)"}' | jq -r ''
{
  "text": "Invalid token",
  "code": 4
}
curl --silent -X POST https://splunk-hec.mydomain.com/services/collector -H "Authorization: Splunk ${TEST_HEC_TOKEN}" -d '{"event":"Hello World (test HEC)"}' | jq -r ''
{
  "text": "Invalid token",
  "code": 4
}
curl --silent -X POST https://splunk-hec.mydomain.com/services/collector -H "Authorization: Splunk ${TEST_HEC_TOKEN}" -d '{"event":"Hello World (test HEC)"}' | jq -r ''
{
  "text": "Success",
  "code": 0
}
```

## Workaround

The only workaround we have for now is to use the one default HEC token (created by the Operator) for all of our indexes--which works fine, but is not how we'd like to run things long-term.

Is there something we are missing or potentially have mis-configured when creating custom HEC tokens?

**Comment by pogdin** [comment]
Hi, I believe the problem may be related to where the HEC config is sitting.  In an Indexer Cluster, all content that resides on the cluster members must be defined in the Cluster Master (CM) CRD and pushed to the Indexer Cluster members. When you define an App at the CM CRD level, the Ansible automation will pick this up, put it in the etc/master-apps folder on the CM and then distribute the App payload. Otherwise, the HEC token will exist on only one Indexer which may explain why you are getting some success when the Load Balancers hits the correctly configured Indexer and failures when sending to the others. Create a simple App with the inputs.conf in local:

````
bash-3.2$ cat inputs.conf
[http://test]
disabled = 0
token = e5dced0b-6496-41fb-b04d-b4e956a1a2a1
````
I'm just using my splunk-apps configmap that also contains the SmartStore config so:

`kubectl create configmap splunk-apps --from-file=HEC.tgz --from-file=smart-store.tgz`

And I update my CM CRD with the new HEC.tgz App:

````
apiVersion: enterprise.splunk.com/v1
kind: ClusterMaster
metadata:
  name: cm-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  licenseMasterRef:
    name: lm-example
  smartstore:
    defaults:
        remotePath: $_index_name
        volumeName: pogdin_smartstore
    indexes:
      - name: main
        remotePath: $_index_name
        volumeName: pogdin_smartstore
        hotlistRecencySecs: 86402
        maxGlobalDataSizeMB: 1000000
        maxGlobalRawDataSizeMB: 1100001
    volumes:
      - name: pogdin_smartstore
        path: pogdin/smartstore
        endpoint: https://s3-us-west-2.amazonaws.com
        secretRef: s3secret
  volumes:
    - name: apps
      configMap:
        name: splunk-apps
  defaults: |-
    splunk:
      apps_location:
        - "/mnt/apps/smart-store.tgz"
        - "/mnt/apps/HEC.tgz"
````
Now when you `kubectl apply -f` your updated CM CRD yaml, it should pick up the HEC app and the automation will distribute to the indexer cluster members.
