### ISSUE TITLE
Apps are installed only on search head and not on indexers

### ISSUE THREAD

**Issue by nicolasappdirect** [splunk/splunk-operator#38]
Hi,

We have the following configuration for our Splunk Operator.

defaults.yml
```
---
splunk:
  password: xxxx
  license_uri: "/mnt/licenses/Splunk.License"
  smartstore:
    cachemanager:
      max_cache_size: 500
      max_concurrent_uploads: 7
  conf:
    splunk-launch:
      directory: /opt/splunk/etc
      content:
        SPLUNK_HOME: /opt/splunk
        SPLUNK_DB: /opt/splunk
        SPLUNK_SERVER_NAME: splunkd
    indexes:
      directory: /opt/splunk/etc/system/local
      content:
        remotePath: volume:s3bucket/$_index_name
        repFactor: auto

        volume:s3bucket:
          storageType: remote
          path: s3://xxxx.amazonaws.com
          remote.s3.access_key: xxxxx
          remote.s3.secret_key: xxxx
          remote.s3.endpoint: https:|http://xxxx.amazonaws.com
        os:
          homePath: $SPLUNK_DB/os/db
          coldPath: $SPLUNK_DB/os/colddb
          thawedPath: $SPLUNK_DB/os/thaweddb
          maxGlobalDataSizeMB: 500
          maxGlobalRawDataSizeMB: 200
          hotlist_recency_secs: 30
          hotlist_bloom_filter_recency_hours: 1
        poc-eng:
          homePath: $SPLUNK_DB/poc-eng/db
          coldPath: $SPLUNK_DB/poc-eng/colddb
          thawedPath: $SPLUNK_DB/poc-eng/thaweddb
          maxGlobalDataSizeMB: 500
          maxGlobalRawDataSizeMB: 200
          hotlist_recency_secs: 30
          hotlist_bloom_filter_recency_hours: 1
  apps_location:
    - /mnt/apps/SplunkAddOnForNIX512.tgz
```

SplunkEnterprise file:

```
---
apiVersion: enterprise.splunk.com/v1alpha1
kind: SplunkEnterprise
metadata:
  name: cluster
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  splunkImage: splunk/splunk:8.0.2
  splunkVolumes:
    - name: apps
      configMap:
        name: splunk-apps
    - name: defaults
      configMap:
        name: splunk-defaults
    - name: licenses
      configMap:
        name: splunk-licenses
  defaultsUrl: /mnt/defaults/defaults.yml
  licenseUrl: /mnt/licenses/Splunk.License

  resources:
    splunkVarStorage: 10Gi
    splunkIndexerStorage: 50Gi
  topology:
    indexers: 3
    searchHeads: 3
```

The /mnt/apps/SplunkAddOnForNIX512.tgz directory is well present/mounted on indexers and search head. However, the application is only installed on search head and not on the indexers.

If we try to go on "/opt/splunk/etc/apps/", we see the application installed, "Splunk_TA_nix" directory on the search head whereas on the indexers, the application is not present at this path.
