### ISSUE TITLE
ClusterMaster CRD Creates record conflict

### ISSUE THREAD

**Issue by ryanfaircloth** [splunk/splunk-operator#394]
Using the following cr leads to a new svc named `splunk-s1-indexer-service` the correct name for this record is `splunk-s1-cluster-master-service` this leads to a conflict with an indexercluster with the same name
```
apiVersion: enterprise.splunk.com/v1
kind: ClusterMaster
metadata:
  name: s1
  finalizers:
    - enterprise.splunk.com/delete-pvc
```
