### ISSUE TITLE
Unable to manage MC ingress with istio and nlb

### ISSUE THREAD

**Issue by ryanfaircloth** [splunk/splunk-operator#395]
When configued with istio and aws nlb TLS can be offloaded to the NLB for compliance with TLS security requirements however because the MC does not have a CRD we are unable to configure using defaults. This is required when the user session is https://:443 but the backend splunk server uses http://:8000

```
  defaults: |-
    splunk:
      conf:
        - key: web
          value:
            content:
              settings:
                "tools.proxy.on": "true"
                "tools.proxy.base": "https://s1-lm.${DOMAIN_NAME}"    
```
