### ISSUE TITLE
Release arm64 version of operator container

### ISSUE THREAD

**Issue by ryanfaircloth** [splunk/splunk-operator#404]
Customers often desire to use arm64 where possible to reduce costs. While Splunk Enterprise is amd64 only the operator container build can be released as both. Until this can be accomplished the deployment manifest should have the following

```
template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64      
```
