### ISSUE TITLE
Utilization reported by the Monitoring Console

### ISSUE THREAD

**Issue by rajeshvijayarajan** [splunk/splunk-operator#445]
The resource utilization reported by the Splunk Monitoring Console seems to be on the basis of the %ge of the resources (CPU and memory) of the physical host on which the pod is running. It does not seem to have a means to provide the utilization on the basis of the resources allocated to the pod. We use the guaranteed SLA i.e. requests and limits set to the same value. 

In summary, the utilization will look misleadingly low, even though the utilization of the allocated resources is optimal or high.

Any creative ways of knowing the actual utilization? docker stat <container-id> too didn't seem to help a great deal.

**Comment by pogdin** [comment]
Hi, thanks for opening this.  There is a known issue with the method in which Monitoring Console gathers info from the container about its resources.  The Splunk container and underlying introspection is unfortunately not container aware yet.  We're looking to pivot resource collection to be based upon the cgroup info in the container or potentially other methods.

**Comment by pogdin** [comment]
CSPL-1481

**Comment by akondur** [comment]
Closing as container awareness is fixed in latest release.

**Comment by rajeshvijayarajan** [comment]
Very cool, thank you!

**Comment by dp-42** [comment]
Hi @akondur,

could please elaborate a bit how this was implemented?

I have setup brand new `splunk-operator` (v2.2.0) and a simple standalone instance based on the install guide:

- https://github.com/splunk/splunk-operator/blob/main/docs/README.md#installing-the-splunk-operator
- https://github.com/splunk/splunk-operator/blob/main/docs/README.md#creating-a-splunk-enterprise-deployment

However, when I go into the monitoring console I still see the node specs instead of the cgroup/pod specs: 

![image](https://user-images.githubusercontent.com/65650723/216461723-6b1ce379-4dfa-40e2-91ee-5aa0ad688bc2.png)

```yaml
...
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: 100m
        memory: 512Mi
    startupProbe:
...
```

@rajeshvijayarajan did already have time to check if your issue was solved with the new version? 😊

**Comment by akondur** [comment]
Hey @dp-42 , I deployed a standalone with MonitoringConsole using 2.2.0 version of the operator.

```
apiVersion: enterprise.splunk.com/v4
kind: MonitoringConsole
metadata:
  name: example-mc
  namespace: splunk-operator
  finalizers:
  - enterprise.splunk.com/delete-pvc
---
apiVersion: enterprise.splunk.com/v4
kind: Standalone
metadata:
  name: single
  namespace: splunk-operator
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  monitoringConsoleRef:
    name: example-mc
```

Resources:

```
$ kubectl get pods splunk-single-standalone-0 -o yaml | grep -i resources: -A 5
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: 100m
```

PFA images showing the right cpu and memory limits showing up on the standalone as well as the MonitoringConsole attached to it.

MC Dashboard:
<img width="786" alt="Monitoring Console Dashboard" src="https://user-images.githubusercontent.com/69369319/216678339-f896e6cb-3446-4fd0-841b-1e4f7f8a84cb.png">

Standalone dashboard:
<img width="344" alt="Standalone dashboard" src="https://user-images.githubusercontent.com/69369319/216678345-f2f854b0-37eb-45a3-b44f-b5963d48fc17.png">

**Comment by dp-42** [comment]
Hi @akondur,

many thanks for your feedback - I have now simply copied your 2 instances and created them on my cluster.

MC: 
![image](https://user-images.githubusercontent.com/65650723/217099563-56450047-4c54-43fb-b7f9-85054974e52a.png)

Standalone:
![image](https://user-images.githubusercontent.com/65650723/217099853-0493c42f-da56-4c00-a5a6-171959ecf154.png)

It is very weird - I am also using the correct images:

```
➜ kubectl get pod splunk-operator-controller-manager-7594c4f88c-l8qgz -o yaml | grep "image:"
    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
    image: splunk/splunk-operator:2.2.0
    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
    image: splunk/splunk-operator:2.2.0

➜ kubectl get pod splunk-single-standalone-0 -o yaml | grep "image:"
    image: splunk/splunk:9.0.3-a2
    image: splunk/splunk:9.0.3-a2

➜ kubectl get pod splunk-single-standalone-0 -o yaml | grep "resources:" -A 6
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: 100m
        memory: 512Mi
```

So it kinda has to be something in my environment:

- We use Rancher as K8s provider - Rancher Kubernetes Engine (RKE)
- Host is an Ubuntu 18.04.6 LTS
- K8s version is v1.19.16

Although I am aware that my setup might not be the "freshest" I don´t really see how this could conflict with the gathering resource information.

Do you have any idea what could be the cause of this? Can you maybe provide insights on how Splunk detects that it runs insides an container and how it reads out the information? 

Many, many thanks!
