### ISSUE TITLE
no matches for kind "Standalone" in version "enterprise.splunk.com/v2"

### ISSUE THREAD

**Issue by vzabawski** [splunk/splunk-operator#456]
Hi. I've created CRD using the command from documentation:
```wget -O splunk-operator.yaml https://github.com/splunk/splunk-operator/releases/download/1.0.1/splunk-operator-install.yaml```

Then I'm trying to create a standalone Splunk instance with the following k8s manifest:
```
apiVersion: enterprise.splunk.com/v2
kind: Standalone
metadata:
  name: indexer
  namespace: splunk
  finalizers:
  - enterprise.splunk.com/delete-pvc
```
I receive the error:
`no matches for kind "Standalone" in version "enterprise.splunk.com/v2"`

After changing apiVersion to `apiVersion: enterprise.splunk.com/v1`, the resource is created.
Is it something wrong on my side or it's just a mistake in documentation?
