### ISSUE TITLE
Self-Signed/Additional trusted certificate support in AppFramework

### ISSUE THREAD

**Issue by Akhalaka** [splunk/splunk-operator#479]
When starting up a new splunk resource with the app framework configured, the init container fails with:
```
fatal error: SSL Validation failed for https://XXXXXXXXX [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:  self signed certificate in certificate chain (_ssl.c:1125)
```

The appRepo configuration is as follows:
```
appRepo:
  appsRepoPollIntervalSeconds: 600
  defaults:
    volumeName: test-apps
    scope: local
  appSources:
  - name: configApps
    location: common-config-apps/
  volumes:
  - name: test-apps
    storageType: s3
    provider: aws
    path: splunk-dev-apps/
    endpoint: https://XXXXXXXXXXXXXXX
    secretRef: s3
```

The endpoint URL points to a ceph s3 endpoint that I have trusted certificates available, but would need to be able to configure the amazon/aws-cli image with.  Based on looking at the code this all looks to be hardcoded right now.

Other notes: I did hack the underlying statefulset to add --no-verify-ssl option in the runtime args of the init container.  This did allow the pod to start and the 1 test app to download to /init-apps/configApps/test.tgz.  This clearly is not a sustainable solution because the next time the splunk definition is changed, this does get wiped out.  That said, this trusted certificate also needs to be available in the splunk-operator itself.  The splunk operator started producing the error
```
{"level":"info","ts":1629738397.8384712,"logger":"splunk.client.GetAppsList","msg":"Got an object error","object.Err":"get \"https://XXXXXXXXXXXXXXXXXXXXX\": x509: certificate signed by unknown authority","client.BucketName":"splunk-dev-apps"}
```

Some potential solutions would be:
- to allow the configuration of the amazon/aws-cli image to use.  This would allow me to build the identical image but with the additional trust built in (I can do the same thing with the actual splunk container...have not tested this yet though).  This would also be useful/necessary to continue to support the full use of Private registries (ie with the RELATED_IMAGE_SPLUNK_ENTERPRISE piece of config)
- allow for additional configuration in the referenced secret to include additional trusted CA certificates and take appropriate actions to add this to the necessary trust.

**Comment by magguns** [comment]
Any news on this? We are using rook-ceph object store, and thus `provider: minio` . Since TLS is required and the http connection is force-upgrade to https there should be some means of supplying the CA certificate ourselves.

**Comment by PrymalInstynct** [comment]
I have run into the same issue working in a network that is not connected to the internet. so using tools like certmanager and lets encrypt to get a globally trusted cert just is not possible. We are limited to using a Certificate Authority without any outside trust.

I had success as described by @magguns by configuring Minio to use insecure http, which is fine for development but that ultimately will not fly in production.

What is odd to me is that the SmartStore configuration does not have the same issue as the AppFramework does.

**Comment by iaroslav-nakonechnikov** [comment]
yes, support of self-signed certificates is needed. 

and i've checked splunk-ansible and splunk-docker projects - nothing supports it. But it is really needed.

**Comment by michal-tatusko-splunk** [comment]
Tracking under: CSPL-1788

**Comment by PrymalInstynct** [comment]
Coming back to this issue after 2 years of waiting for a resolution I have recently been testing new work arounds but am still not having any success.

### Mounting ca.crt secret into each Splunk Cluster resource

**Examples from clusterManager portion of manifest**

```yaml
clusterManager:
  volumes:
    - name: private-ca-vol
      secret:
        secretName: private-ca-cert-secret
```

### Creating a custom server.conf with both sslRootCAPath and caTrustStore defined

```yaml
clusterManager:
  defaults:
    splunk:
      conf:
        - key: server
          value:
            content:
              sslConfig:
                sslRootCAPath: /mnt/private-ca-vol/ca.crt
                caTrustStore: "splunk,os"
                caTrustStorePath: /mnt/private-ca-vol/ca.crt
```

I am still seeing the following error from the splunk-operator pod

```
2025-04-25T13:34:27.242143034Z	INFO	InitMinioClientSession	Connecting to Minio S3 for apps	{"controller": "searchheadcluster", "controllerGroup": "enterprise.splunk.com", "controllerKind": "SearchHeadCluster", "SearchHeadCluster": {"name":"shc","namespace":"splunk-enterprise"}, "namespace": "splunk-enterprise", "name": "shc", "reconcileID": "2e5c0951-238b-49f8-bcd3-005990a32df9", "appS3Endpoint": "s3.local.domain:9000"}
2025-04-25T13:34:27.274413373Z	ERROR	GetAppListFromRemoteBucket	Unable to get apps list	{"controller": "searchheadcluster", "controllerGroup": "enterprise.splunk.com", "controllerKind": "SearchHeadCluster", "SearchHeadCluster": {"name":"shc","namespace":"splunk-enterprise"}, "namespace": "splunk-enterprise", "name": "shc", "reconcileID": "2e5c0951-238b-49f8-bcd3-005990a32df9", "name": "shc", "namespace": "splunk-enterprise", "appSource": "esApp", "error": "got an object error: Get \"https://s3.local.domain:9000/app-framework/?location=\": tls: failed to verify certificate: x509: certificate signed by unknown authority for bucket: app-framework"}
```

And the only logs coming from the cluster-manager pod that reference the ca.crt file are from the KVStore/mongodb logs

**mogod.log**

```json
{"t":{"$date":"2025-04-25T13:05:51.818Z"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"0.0.0.0","port":8191,"tls":{"CAFile":"/mnt/private-ca-vol/ca.crt","allowInvalidHostnames":true,"certificateKeyFile":"/opt/splunk/etc/auth/server.pem","certificateKeyFilePassword":"<password>","disabledProtocols":"noTLS1_0,noTLS1_1","mode":"requireTLS","tlsCipherConfig":"ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDH-ECDSA-AES256-GCM-SHA384:ECDH-ECDSA-AES128-GCM-SHA256:ECDH-ECDSA-AES128-SHA256:AES256-GCM-SHA384:AES128-GCM-SHA256:AES128-SHA256"},"unixDomainSocket":{"enabled":false}},"replication":{"oplogSizeMB":200,"replSet":"B08F53E0-4244-41C9-A4E1-D18E902DC2FB"},"security":{"javascriptEnabled":false,"keyFile":"/opt/splunk/var/lib/splunk/kvstore/mongo/splunk.key"},"setParameter":{"enableLocalhostAuthBypass":"0","minSnapshotHistoryWindowInSeconds":"5","oplogFetcherSteadyStateMaxFetcherRestarts":"0"},"storage":{"dbPath":"/opt/splunk/var/lib/splunk/kvstore/mongo","engine":"wiredTiger","wiredTiger":{"engineConfig":{"cacheSizeGB":1.2}}},"systemLog":{"timeStampFormat":"iso8601-utc"}}}}
```

**splunkd.log**
```
04-25-2025 13:05:51.753 +0000 INFO  MongodRunner [2603 KVStoreConfigurationThread] - Using mongod command line --sslCAFile /mnt/private-ca-vol/ca.crt
```

**Comment by yaroslav-nakonechnikov** [comment]
as work around you can try to add pre/post ansible playbook.

in short:
* create something like with name `task.yml`:
```
- name: Exec command to install custom ca.
  ansible.builtin.command: cp /mnt/private-ca-vol/ca.crt /usr/local/share/ca/ && update-ca-certificates
```
* mount that task.yml (any way: as secret, or as configmap, or just file in some volume)
* provide env variable to defaults yml:
```
"extraEnv" = [
        { "name" = "SPLUNK_ANSIBLE_PRE_TASKS", "value" = "file:///mnt/tasks/task.yml" }
      ] 
```
or in defaults.yml (https://github.com/splunk/splunk-ansible/blob/develop/docs/advanced/default.yml.spec.md)
```
ansible_pre_tasks:
  - file:///mnt/tasks/task.yml
```

in this *example*, it will try to install ca before running other ansible tasks to configure splunk.

**Comment by PrymalInstynct** [comment]
@yaroslav-nakonechnikov Maybe I am missing something but I cant seem to get the task to execute without throwing permission errors. Looking at the container as it is running, there is a user ansible who is in the `sudo` group, I have tried including `become: true` and `become_user: root` with the tasks to get appropiate permissions to copy the ca.crt file into the correct directly but just get the error below.

```
TASK [Execute pre-setup playbooks] *********************************************
included: /opt/ansible/execute_adhoc_plays.yml for localhost => (item=file:///mnt/prelim-task-vol/ca-task.yml)
Friday 25 April 2025  19:41:08 +0000 (0:00:00.047)       0:00:01.289 **********
TASK [Fetch adhoc playbooks] ***************************************************
changed: [localhost]
Friday 25 April 2025  19:41:09 +0000 (0:00:00.887)       0:00:02.177 **********
TASK [Execute playbooks] *******************************************************
included: /opt/container_artifact/ca-task.yml for localhost
Friday 25 April 2025  19:41:09 +0000 (0:00:00.075)       0:00:02.252 **********
TASK [Copy Private CA Cert to Trust Store] *************************************
fatal: [localhost]: FAILED! => {
    "changed": false,
    "rc": 1
}
MSG:
MODULE FAILURE
See stdout/stderr for the exact error
MODULE_STDERR:
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```

**ca-trust.yml ConfigMap**
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prelim-task-configmap
  namespace: splunk-enterprise
data:
  ca-task.yml: |
    ---
    - name: Copy Private CA Cert to Trust Store
      ansible.builtin.copy:
        remote_src: true
        src: /mnt/private-ca-vol/ca.crt
        dest: /etc/pki/ca-trust/source/anchors/private-ca.crt
        owner: root
        group: root
        mode: '0644'
      become: true
      become_user: root

    - name: Exec command to install custom ca.
      ansible.builtin.shell: update-ca-trust
      become: true
      become_user: root

```
