### ISSUE TITLE
Generate an additional "service" for indexer cluster hec with ack

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#48]
Certain ingress providers such as istio apply session affinity based on the destination service Splunk HEC is unique in that it has two use cases with and session affinity. To support hec use with and without ack we need two services internally

**Comment by mikedickey** [comment]
With istio, session affinity is handled using `DestinationRule`. For example:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: splunk-search-head-rule
spec:
  host: splunk-example-search-head-service
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: SPLUNK_ISTIO_SESSION
          ttl: 3600s
```

Not clear to me why affinity for HEC ack should be handled any differently.
