### ISSUE TITLE
Ansible error: sudo: a password is required error when JAVA_VERSION env var defined

### ISSUE THREAD

**Issue by Proger666** [splunk/splunk-operator#538]
I'm trying to deploy Splunk on a fresh new k8s host and new installation.

I've created a standalone environment as follows:

```
cat <<EOF | kubectl apply -f -
apiVersion: enterprise.splunk.com/v2
kind: Standalone
metadata:
  name: s1
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  imagePullPolicy: Always
  extraEnv:
  - name: JAVA_VERSION
    value: "openjdk:11"
  - name: SPLUNK_PASSWORD
    value: "P@ssw0rd"
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.1"
    limits:
      memory: "16Gi"
      cpu: "8"
EOF
```

After that, ansible inside standalone throw me the error upon first run:

```
MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

sudo: a password is required


PLAY RECAP *********************************************************************
localhost                  : ok=24   changed=0    unreachable=0    failed=1    skipped=26   rescued=0    ignored=0  

```

It could not install java which is required for DB connect.

Without JAVA_VERSION env ansible runs without errors.

How to fix this?
