### ISSUE TITLE
Splunk Deployer init container not able to use AWS web identity token

### ISSUE THREAD

**Issue by dhanasekar79** [splunk/splunk-operator#594]
Hi,

The deployer crashes when we use the SA account for splunk to inject the POD WEB IDENTITY TOKEN FILE  that has the token for the Role that has full access to S3 bucket.

Looking at the crash logs, I see "./aws" permission denied. I copied the init container configuration to see what's going wrong and it appears that the issue is that, when the init container run as non-root user, it cannot assume the WEB IDENTITY TOKEN FILE.

I confirmed this with AWS by raising the ticket. The only way to make it work is to run the init container as the ROOT.

I see the operator is deploying the statefulset for search head that runs the POD with the below security context

      securityContext:
        fsGroup: 41812
        runAsUser: 41812

I would like to check to see  whether the WEB_IDENTITY TOKEN use case is tested . If it is a bug, is there a workaround for timebeing  for me to be able to run the init container as root?

Kindly see the below output from my testing for your reference.

bash-4.2$ aws sts get-caller-identity

[Errno 13] Permission denied: '/.aws'

bash-4.2$ env |grep AWS
AWS_ROLE_ARN=arn:aws:iam::020363268947:role/MinioS3Role
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_DEFAULT_REGION=us-west-2
AWS_REGION=us-west-2

bash-4.2$ unset AWS_WEB_IDENTITY_TOKEN_FILE
bash-4.2$ aws sts get-caller-identity
{
    "UserId": "AROAQJPN62NJZZUMAPIFG:i-00ebf38ec81e77315",
    "Account": "XXXXXXXX",
    "Arn": "arn:aws:sts::XXXXXXXX:assumed-role/vz-thingspace-eks-node-instance-role/i-00ebf38ec81e77315"
}

**Comment by dhanasekar79** [comment]
apiVersion: enterprise.splunk.com/v3
kind: SearchHeadCluster
metadata:
  name: shc
  namespace: splunk
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  appRepo:
    appSources:
      - name: SamlApp
        location: SamlApp

**Comment by pogdin** [comment]
Hi, please use apiVersion v2, v3 is not released yet.  Here is my example:
````
apiVersion: enterprise.splunk.com/v2
kind: SearchHeadCluster
metadata:
  name: shc-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterMasterRef:
    name: cm-example
  licenseMasterRef:
    name: lm-example
  appRepo:
    appsRepoPollIntervalSeconds: 600
    defaults:
      volumeName: volume_app_repo
      scope: cluster
    appSources:
      - name: shApps
        location: SearchHead/
    volumes:
      - name: volume_app_repo
        storageType: s3
        provider: aws
        path: pogdin/Apps/
        endpoint: https://s3-us-west-2.amazonaws.com
        secretRef: s3-secret
````
I would try first using the s3 secret and make sure everything is working before attempting the IAM method.
