### ISSUE TITLE
Create Finalizer to clean up each resource type to support Continuous Delivery technologies

### ISSUE THREAD

**Issue by PrymalInstynct** [splunk/splunk-operator#597]
When working with this project to deploy a distributed splunk cluster i have found that in version 1.0.3 the clustermaster statefulset is not being deleted when the rest of the deployment is being deleted just fine.

I also have found that I needed to manually delete a few services as well,

cluster master service
indexer cluster service
monitoring console headless
monitoring console service

**My Manifest**
```yaml
---
apiVersion: enterprise.splunk.com/v2
kind: LicenseMaster
metadata:
  name: lm-dev
  namespace: splunk-cluster-dev
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterMasterRef:
    name: cm-dev
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.1"
    limits:
      memory: "8Gi"
      cpu: "4"
  etcVolumeStorageConfig:
    storageClassName: longhorn
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageClassName: longhorn
    storageCapacity: 25Gi
  containers:
  volumes:
    - name: defaults
      configMap:
        name: splunk-cluster-defaults
    - name: licenses
      configMap:
        name: splunk-licenses
  licenseUrl: /mnt/licenses/enterprise.lic
  defaultsUrl: /mnt/defaults/default.yml
---
apiVersion: enterprise.splunk.com/v2
kind: ClusterMaster
metadata:
  name: cm-dev
  namespace: splunk-cluster-dev
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  licenseMasterRef:
    name: lm-dev
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.1"
    limits:
      memory: "8Gi"
      cpu: "4"
  etcVolumeStorageConfig:
    storageClassName: longhorn
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageClassName: longhorn
    storageCapacity: 25Gi
  volumes:
    - name: defaults
      configMap:
        name: splunk-cluster-defaults
  defaultsUrl: /tmp/defaults/default.yml
---
apiVersion: enterprise.splunk.com/v2
kind: IndexerCluster
metadata:
  name: idx-dev
  namespace: splunk-cluster-dev
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterMasterRef:
    name: cm-dev
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.1"
    limits:
      memory: "8Gi"
      cpu: "4"
  etcVolumeStorageConfig:
    storageClassName: longhorn
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageClassName: longhorn
    storageCapacity: 100Gi
  volumes:
    - name: defaults
      configMap:
        name: splunk-cluster-defaults
  defaultsUrl: /tmp/defaults/default.yml
---
apiVersion: enterprise.splunk.com/v2
kind: SearchHeadCluster
metadata:
  name: sh-dev
  namespace: splunk-cluster-dev
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterMasterRef:
    name: cm-dev
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.1"
    limits:
      memory: "8Gi"
      cpu: "4"
  etcVolumeStorageConfig:
    storageClassName: longhorn
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageClassName: longhorn
    storageCapacity: 25Gi
  volumes:
    - name: defaults
      configMap:
        name: splunk-cluster-defaults
  defaultsUrl: /tmp/defaults/default.yml

```

**Comment by pogdin** [comment]
Hi, you should delete by resource
````
bash-3.2$ kubectl api-resources | grep enterprise.splunk.com/v2
clustermasters                    cm-idxc      enterprise.splunk.com/v2          true         ClusterMaster
indexerclusters                   idc,idxc     enterprise.splunk.com/v2          true         IndexerCluster
licensemasters                    lm           enterprise.splunk.com/v2          true         LicenseMaster
searchheadclusters                shc          enterprise.splunk.com/v2          true         SearchHeadCluster
standalones                       stdaln       enterprise.splunk.com/v2          true         Standalone
````
then
````
bash-3.2$ kubectl delete lm --all
licensemaster.enterprise.splunk.com "lm-dev" deleted
bash-3.2$ kubectl delete shc --all
searchheadcluster.enterprise.splunk.com "sh-dev" deleted
````
etc

**Comment by PrymalInstynct** [comment]
ok, that makes sense but is a bit disappointing I am working to utilize splunk operator in conjunction with FluxCD to manage the cluster and in that situation I do not believe Flux can be extended support that methodology without more work.

**Comment by pogdin** [comment]
Ah.  Seems like this could be done with a finalizer in your Operator yaml but I would have to look into it further.

**Comment by PrymalInstynct** [comment]
I am not 100% sure I understand what you mean, could you give me a simple example?

**Comment by pogdin** [comment]
Sure, [finalizers](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#finalizers) "allow controllers to implement asynchronous pre-delete hooks".  We currently use them to delete the PVC so you don't end up of a bunch of them hanging around.

````
apiVersion: enterprise.splunk.com/v2
kind: Standalone
metadata:
  name: s1
  finalizers:
  - enterprise.splunk.com/delete-pvc
```` 
I was thinking you could implement a custom finalizer that would delete the service or anything else you might want.
