### ISSUE TITLE
statefulset/horizontalpodautoscaling not applying correctly

### ISSUE THREAD

**Issue by PrymalInstynct** [splunk/splunk-operator#600]
## Issue
When testing out the standup of a distributed cluster via splunk-operator a few settings are not applying as I expect in association with IndexerCluster and SeachHeadCluster stateful sets.

## Actual Results
```
# kubectl get idxc -n splunk-cluster-dev
NAME      PHASE   MASTER   DESIRED   READY   AGE
idx-dev   Ready   Ready    2         3       118m

# kubectl get shc -n splunk-cluster-dev
NAME     PHASE   DEPLOYER   DESIRED   READY   AGE
sh-dev   Ready   Ready      3         3       119m

NAME                                                            READY   AGE
statefulset.apps/splunk-cm-dev-cluster-master                   1/1     119m
statefulset.apps/splunk-idx-dev-indexer                         3/3     93m
statefulset.apps/splunk-lm-dev-license-master                   1/1     119m
statefulset.apps/splunk-sh-dev-deployer                         1/1     119m
statefulset.apps/splunk-sh-dev-search-head                      3/3     119m
statefulset.apps/splunk-splunk-cluster-dev-monitoring-console   1/1     105m

NAME                                            REFERENCE                  TARGETS    MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/idx-scale   IndexerCluster/idx-dev     195%/75%   2         2         2          119m
horizontalpodautoscaler.autoscaling/sh-scale    SearchHeadCluster/sh-dev   172%/75%   2         2         2          119m
```

## Expect Results
Splunk cluster starts with only 2 Indexers and 2 search heads in the cluster

`splunk-cluster.yaml`
Setting replicas value for both IDXC and SHC to 2

## Configs
```yaml
---
apiVersion: enterprise.splunk.com/v2
kind: LicenseMaster
metadata:
  name: lm-dev
  namespace: splunk-cluster-dev
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterMasterRef:
    name: cm-dev
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.1"
    limits:
      memory: "4Gi"
      cpu: "2"
  etcVolumeStorageConfig:
    storageClassName: longhorn
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageClassName: longhorn
    storageCapacity: 25Gi
  volumes:
    - name: defaults
      configMap:
        name: splunk-cluster-defaults
    - name: licenses
      configMap:
        name: splunk-licenses
  licenseUrl: /mnt/licenses/enterprise.lic
  defaultsUrl: /mnt/defaults/default.yml
---
apiVersion: enterprise.splunk.com/v2
kind: ClusterMaster
metadata:
  name: cm-dev
  namespace: splunk-cluster-dev
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  licenseMasterRef:
    name: lm-dev
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.1"
    limits:
      memory: "8Gi"
      cpu: "4"
  etcVolumeStorageConfig:
    storageClassName: longhorn
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageClassName: longhorn
    storageCapacity: 25Gi
  volumes:
    - name: defaults
      configMap:
        name: splunk-cluster-defaults
  defaultsUrl: /tmp/defaults/default.yml
---
apiVersion: enterprise.splunk.com/v2
kind: IndexerCluster
metadata:
  name: idx-dev
  namespace: splunk-cluster-dev
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterMasterRef:
    name: cm-dev
  replicas: 2
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.1"
    limits:
      memory: "8Gi"
      cpu: "4"
  etcVolumeStorageConfig:
    storageClassName: longhorn
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageClassName: longhorn
    storageCapacity: 100Gi
  volumes:
    - name: defaults
      configMap:
        name: splunk-cluster-defaults
  defaultsUrl: /tmp/defaults/default.yml
---
apiVersion: enterprise.splunk.com/v2
kind: SearchHeadCluster
metadata:
  name: sh-dev
  namespace: splunk-cluster-dev
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterMasterRef:
    name: cm-dev
  replicas: 2
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.1"
    limits:
      memory: "8Gi"
      cpu: "4"
  etcVolumeStorageConfig:
    storageClassName: longhorn
    storageCapacity: 15Gi
  varVolumeStorageConfig:
    storageClassName: longhorn
    storageCapacity: 25Gi
  volumes:
    - name: defaults
      configMap:
        name: splunk-cluster-defaults
  defaultsUrl: /tmp/defaults/default.yml
```

`autoscale.yaml`
Trying for force auto scaling to only allow 2 pods
```yaml
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: idx-scale
  namespace: splunk-cluster-dev
spec:
  scaleTargetRef:
    apiVersion: enterprise.splunk.com/v2
    kind: IndexerCluster
    name: idx-dev
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 75
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sh-scale
  namespace: splunk-cluster-dev
spec:
  scaleTargetRef:
    apiVersion: enterprise.splunk.com/v2
    kind: SearchHeadCluster
    name: sh-dev
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 75
```

`default.yml`
Setting all replication factors to 2

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: splunk-cluster-defaults
  namespace: splunk-cluster-dev
data:
  default.yml: |
    ---
    ansible_connection: local
    ansible_environment: {}
    ansible_post_tasks: []
    ansible_pre_tasks: []
    cert_prefix: https
    config:
      baked: default.yml
      defaults_dir: /mnt/defaults
      env:
        headers: null
        var: SPLUNK_DEFAULTS_URL
        verify: true
      host:
        headers: null
        url: null
        verify: true
      max_delay: 60
      max_retries: 3
      max_timeout: 1200
    dmc_asset_interval: 3,18,33,48 * * * *
    dmc_forwarder_monitoring: false
    docker: true
    es_ssl_enablement: --ssl_enablement auto
    hide_password: false
    java_download_url: null
    java_update_version: null
    java_version: null
    retry_delay: 6
    retry_num: 60
    shc_sync_retry_num: 60
    splunk:
      admin_user: admin
      allow_upgrade: true
      app_paths:
        default: /opt/splunk/etc/apps
        deployment: /opt/splunk/etc/deployment-apps
        httpinput: /opt/splunk/etc/apps/splunk_httpinput
        idxc: /opt/splunk/etc/master-apps
        shc: /opt/splunk/etc/shcluster/apps
      apps_location_local: []
      appserver:
        port: 8065
      asan: false
      auxiliary_cluster_masters: []
      build_url_bearer_token: null
      cluster_master_url: null
      connection_timeout: 0
      declarative_admin_password: false
      deployer_url: null
      deployment_client:
        name: null
      dfs:
        dfc_num_slots: 4
        dfw_num_slots: 10
        dfw_num_slots_enabled: false
        enable: false
        port: 9000
        spark_master_host: 127.0.0.1
        spark_master_webui_port: 8080
      disable_popups: false
      dsp:
        cert: null
        enable: false
        pipeline_desc: null
        pipeline_name: null
        pipeline_spec: null
        server: forwarders.scp.splunk.com:9997
        verify: false
      enable_service: false
      es:
        ssl_enablement: auto
      exec: /opt/splunk/bin/splunk
      group: splunk
      hec:
        cert: null
        enable: true
        password: null
        port: 8088
        ssl: true
      home: /opt/splunk
      http_enableSSL: 0
      http_enableSSL_cert: null
      http_enableSSL_privKey: null
      http_enableSSL_privKey_password: null
      http_port: 8000
      idxc:
        label: idxc_label
        replication_factor: 2
        replication_port: 9887
        search_factor: 2
      ignore_license: false
      kvstore:
        port: 8191
      launch: {}
      license_download_dest: /tmp/licenses/enterprise.lic
      license_master_url: ''
      multisite_master_port: 8089
      multisite_replication_factor_origin: 2
      multisite_replication_factor_total: 3
      multisite_search_factor_origin: 1
      multisite_search_factor_total: 3
      opt: /opt
      pass4SymmKey: null
      pid: /opt/splunk/var/run/splunk/splunkd.pid
      root_endpoint: null
      s2s:
        ca: null
        cert: null
        enable: true
        password: null
        port: 9997
        ssl: false
      search_head_captain_url: null
      secret: null
      service_name: null
      set_search_peers: true
      shc:
        deployer_push_mode: null
        label: shc_label
        replication_factor: 2
        replication_port: 9887
      smartstore: null
      ssl:
        ca: null
        cert: null
        enable: true
        password: null
      svc_port: 8089
      tar_dir: splunk
      user: splunk
      wildcard_license: false
    splunk_home_ownership_enforcement: true
    splunkbase_password: null
    splunkbase_token: null
    splunkbase_username: null
    wait_for_splunk_retry_num: 60
```

**Comment by pogdin** [comment]
Hey @PrymalInstynct , minimum number of [SHC members is 3](https://github.com/splunk/splunk-operator/blob/master/docs/CustomResources.md#searchheadcluster-resource-spec-parameters) due to raft re-election.

Not sure what is going on with the IDXC.  It should allow you to set replica count = RF but I'll need to try to reproduce.

**Comment by PrymalInstynct** [comment]
Dang, I think i stared at the SHC reference you posted a least a few times and totally overlooked the table.

**Comment by pogdin** [comment]
@PrymalInstynct , before we get into the hpa stuff, let's verify it is honoring the rep factor setting.  Not sure if it has something to do with passing the value via your defaults URL but this direct method worked for me.  Also, perhaps only try setting the value on the Cluster Master CR.

````
apiVersion: enterprise.splunk.com/v2
kind: ClusterMaster
metadata:
  name: cm-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  licenseMasterRef:
    name: lm-example
  smartstore:
    defaults:
        volumeName: pogdin_smartstore
    indexes:
      - name: main
        remotePath: $_index_name
        volumeName: pogdin_smartstore
        hotlistRecencySecs: 86402
        maxGlobalDataSizeMB: 1000000
        maxGlobalRawDataSizeMB: 1100001
    volumes:
      - name: pogdin_smartstore
        path: pogdin/smartstore
        endpoint: https://s3-us-west-2.amazonaws.com
        secretRef: s3-secret
  defaults: |-
    splunk:
      idxc:
        replication_factor: 2
````
````
bash-3.2$ kubectl get idxc
NAME           PHASE   MASTER   DESIRED   READY   AGE
idxc-example   Ready   Ready    2         2       8m25s
bash-3.2$ kubectl get pods
NAME                                  READY   STATUS    RESTARTS   AGE
splunk-cm-example-cluster-master-0    1/1     Running   0          12m
splunk-default-monitoring-console-0   1/1     Running   0          8m18s
splunk-idxc-example-indexer-0         1/1     Running   0          8m34s
splunk-idxc-example-indexer-1         1/1     Running   0          8m34s
splunk-lm-example-license-master-0    1/1     Running   0          13m
splunk-operator-664fcf4d46-tg8mq      1/1     Running   0          11d
````
