### ISSUE TITLE
blocked:mixed-content for Splunk app static files without locale set after Splunk webserver redirect

### ISSUE THREAD

**Issue by BGrasnick** [splunk/splunk-operator#608]
Hey everyone,

we have a big network problem with Splunk using splunk-operator.

Our setup is the following:
- AWS EKS Cluster (v1.21)
- nginx-ingress-controller (v0.47.0) (AWS ACM certificate ARN included) -> creates ELB
- EC2 ELB with AWS ACM certificate
- cluster internally we use weavenet (v2.8.1)
- the splunk-operator (v1.0.3) creates a clustered Splunk (v8.2.2) environment consisting of IndexerCluster (+ ClusterMaster), SearchHeadCluster (+ SearchHeadDeployer) and Heavy Forwarder (+ DMC)
- we have an ingress allowing access to the Splunk WebUI via our intranet
- SSL termination happens on the ELB (after that there is unencrypted HTTP traffic but cluster internally everything is encrypted using weave)

So all user accesses are HTTPS from the outside but HTTP at the Splunk UI.

When requesting static content without a language prefix at the beginning of the URI path (i.e. en-EN) Splunk answers with a redirect (303) to a URL containing the language prefix. The Splunk-genereted redirect-URL is a HTTP-URL.

This breaks the browser access to the page because the browser detects a security risk and refuses to follow the redirect because of "blocked:mixed-content".

To solve the problem we configured in web.conf

[settings]
tools.proxy.on = true
tools.proxy.base = https://webui-dev.example.com

This did not work and the redirects generated from Splunk are still

http://webui-dev.example.com

We also tried adding the following annotations in nginx-ingress-controller which did not solve the issue:
nginx.ingress.kubernetes.io/force-ssl-redirect: "true"          
nginx.ingress.kubernetes.io/ssl-redirect: "true"

Do you have any ideas how this problem can be solved?

----

Please find attached an example wget call for the problematic URL as well as configs for nginx-ingress-controller and the Ingress to the WebUI

wget call:
```
mycomputer > wget -S --max-redirect=3 https://webui-dev.example.com/static/app/fancy_app/table/table.js
--2021-12-01 10:39:12-- https://webui-dev.example.com/static/app/fancy_app/table/table.js
Resolving webui-dev.example.com (webui-dev.example.com)... 10.109.140.50, 10.109.142.124, 10.109.141.248
Connecting to webui-dev.example.com (webui-dev.example.com)|10.109.140.50|:443... connected.
HTTP request sent, awaiting response...
HTTP/1.1 303 See Other
Content-Type: text/html; charset=UTF-8
Date: Wed, 01 Dec 2021 09:39:15 GMT
Location: http://webui-dev.example.com/en-US/static/app/fancy_app/table/table.js
Set-Cookie: INGRESSCOOKIE=1638351556.615.2298.369244; Path=/; HttpOnly
Vary: Accept-Language
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Content-Length: 449
Connection: keep-alive
Location: http://webui-dev.example.com/en-US/static/app/fancy_app/table/table.js [following]
URL transformed to HTTPS due to an HSTS policy
--2021-12-01 10:39:14-- https://webui-dev.example.com/en-US/static/app/fancy_apptable/table.js
Reusing existing connection to webui-dev.example.com:443.
HTTP request sent, awaiting response...
HTTP/1.1 200 OK
Cache-Control: public, max-age=31536000
Content-Type: text/javascript
Date: Wed, 01 Dec 2021 09:39:15 GMT
ETag: "6F68E827D9C6CD437DE91F3D5DDB032D447D8FA4"
Expires: Wed, 01 Dec 2022 09:39:15 GMT
Last-Modified: Tue, 30 Nov 2021 15:28:40 GMT
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Content-Length: 673
Connection: keep-alive
Length: 673 [text/javascript]
Saving to: ‘table.js’
```

nginx-ingress-controller helmfile:
```
repositories:
  - name: ingress-nginx 
    url: https://kubernetes.github.io/ingress-nginx
    # source: https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx

environments:
  platform-infra:
    values:
      - ../values/globals.platform-infra.yaml
    secrets:
      - ../values/secrets.platform-infra.yaml
 
releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 3.34.0
    installed: true
    wait: true
    values:
      - controller:
          image:
            repository: k8s-gcr-docker-remote.example.com/ingress-nginx/controller
          patch:
            enabled: true
            image:
              repository: docker-hub-remote.example.com/jettech/kube-webhook-certgen
          service:
            enabled: true
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-internal: '0.0.0.0/0'
              service.beta.kubernetes.io/aws-load-balancer-ssl-cert:  "{{ .Values.sslCertArn }}"
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'http'
              service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            targetPorts:
              https: 80
          publishService:
            enabled: true
          admissionWebhooks:
            patch:
              image:
                repository: docker-hub-remote.example.com/jettech/kube-webhook-certgen
          config:
            log-format-escape-json: 'true'
            log-format-upstream: '{"timestamp": "$time_iso8601", "requestID": "$req_id", "proxyUpstreamName":
            "$proxy_upstream_name", "proxyAlternativeUpstreamName": "$proxy_alternative_upstream_name","upstreamStatus":
            "$upstream_status", "upstreamAddr": "$upstream_addr","httpRequest":{"requestMethod":
            "$request_method", "requestUrl": "$host$request_uri", "status": $status,"requestSize":
            "$request_length", "responseSize": "$upstream_response_length", "userAgent": "$http_user_agent",
            "remoteIp": "$remote_addr", "referer": "$http_referer", "latency": "$upstream_response_time s",
            "protocol":"$server_protocol"}}'
          {{ if .Values.nginxHostNetwork }}
          dnsPolicy: ClusterFirstWithHostNet
          hostNetwork: true
          {{ end }}
```

ingress.yaml:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.global.namespace.name }}
  name: splunk-webui-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/hostname: webui-{{ .Values.global.namespace.name }}.example.com
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  rules:
  - host: webui-{{ .Values.global.namespace.name }}.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: splunk-sh-cluster-search-head-service
            port: 
              number: 8000
```

If you need any other info / yaml file content to understand the problem please let me know.
