### ISSUE TITLE
SmartStore configuration error: Could not find access key and secret key

### ISSUE THREAD

**Issue by onlineid** [splunk/splunk-operator#663]
I am following this document to setup my study env. 
https://splunk.github.io/splunk-operator/SmartStore.html#storing-smartstore-secrets

1. MinIO has been setup on Azure follow document provided by MinIO
2. Secret object created
```
kubectl -n splunk create secret generic smartstore-secret \
    --from-literal=s3_access_key=xxxxx... \
    --from-literal=s3_secret_key=xxxxxxx...
```

3. Updated custom resources in ClusterMaster yaml
```
...
  smartstore:
    defaults:
      volumeName: poc_vol
    indexes:
    - name: data1
      remotePath: $_index_name
      volumeName: poc_vol
    - name: data2
      remotePath: $_index_name
      volumeName: poc_vol
    - name: data3
      remotePath: $_index_name
      volumeName: poc_vol
    volumes:
    - name: poc_vol
      path: indexdata-poc-bucket/cluster/ss-data/
      endpoint: https://blobsplunk.az.minio.io/minio/
      secretRef: smartstore-secret
```

4. Apply cluster-master.yaml sucessfully and cluster master status seems normal
5. Indexer cluster fail to start, error in log below.
`Problem parsing indexes.conf: Cannot load IndexConfig: Unable to load remote volume "poc_vol" of scheme "s3" referenced by index "_audit": Could not find access_key and/or secret_key in a configuration file, in environment variables or via the AWS metadata endpoint.
`
Please help.
Thanks.
