### ISSUE TITLE
IndexerCluster serviceAccount update is ignored by the Operator v1.0.5

### ISSUE THREAD

**Issue by w00jay** [splunk/splunk-operator#667]
An IndexerCluster CR with a newly added `.spec.serviceAccount` entry does not update the cluster.  

It seems the operator function [MergePodSpecUpdates()](https://github.com/splunk/splunk-operator/blob/c70f6b07178be3314c324d5f2afc14d75f8f8e57/pkg/splunk/controller/util.go#L78) in `pkg/splunk/controller/util.go` does not inspect changes in `.spec.serviceAccount`.

This was noted running `docker.io/splunk/splunk-operator:1.0.5` Operator managing `splunk/splunk:8.2.3.3` Splunk clusters.

IndexerCluster CR:
```
apiVersion: enterprise.splunk.com/v2
kind: IndexerCluster
metadata:
  labels:
    app: splunk-indexer
    site: site1
  name: testidx05site1
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
            - splunk-indexer
          - key: site
            operator: In
            values:
            - site1
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - splunk-indexer
        topologyKey: kubernetes.io/hostname
  clusterMasterRef:
    name: testsite01
  defaults: |
    splunk: {license_master_url: '...',
      multisite_master: ..., site: site1}
  etcVolumeStorageConfig:
    storageCapacity: 50Gi
    storageClassName: local-path
  image: splunk/splunk:8.2.3.3
  replicas: 1
  serviceAccount: splunk-indexer-svc-account
  tolerations:
  - effect: NoSchedule
    key: indexer
    operator: Equal
    value: "true"
  - effect: NoSchedule
    key: site
    operator: Equal
    value: site1
  varVolumeStorageConfig:
    storageCapacity: 1024Gi
    storageClassName: local-path
status:
  IdxcPasswordChangedSecrets: {}
  clusterMasterPhase: Ready
  indexer_secret_changed_flag: []
  indexing_ready_flag: true
  initialized_flag: true
  maintenance_mode: false
  namespace_scoped_secret_resource_version: "2206262"
  peers:
  - active_bundle_id: ...
    bucket_count: 705
    guid: ...
    is_searchable: true
    name: ...
    status: Up
  phase: Ready
  readyReplicas: 1
  replicas: 1
  selector: ...
  service_ready_flag: true
```
