### ISSUE TITLE
panic: odd number of arguments passed as key-value pairs for logging

### ISSUE THREAD

**Issue by mdaniel** [splunk/splunk-operator#763]
```
2022-04-27T02:04:06.977Z        ERROR   splunk.reconcile.GetSecretByName        Unable to get secret    {"name": "cm", "namespace": "splunk", "secret name": "", "error": "Secret \"\" not found"}
github.com/splunk/splunk-operator/pkg/splunk/enterprise.DeleteOwnerReferencesForResources
        /workspace/pkg/splunk/enterprise/util.go:496
github.com/splunk/splunk-operator/pkg/splunk/enterprise.ApplyClusterManager
        /workspace/pkg/splunk/enterprise/clustermaster.go:121
github.com/splunk/splunk-operator/controllers.(*ClusterMasterReconciler).Reconcile
        /workspace/controllers/clustermaster_controller.go:103
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227
2022-04-27T02:04:06.977Z        DPANIC  controller.clustermaster.DeleteOwnerReferencesForS3Secrets      odd number of arguments passed as key-value pairs for logging   {"reconciler group": "enterprise.splunk.com", "reconciler kind": "ClusterMaster", "name": "cm", "namespace": "splunk", "kind": "ClusterMaster", "name": "cm", "namespace": "splunk", "ignored key": ""}
github.com/splunk/splunk-operator/pkg/splunk/enterprise.DeleteOwnerReferencesForResources
        /workspace/pkg/splunk/enterprise/util.go:496
github.com/splunk/splunk-operator/pkg/splunk/enterprise.ApplyClusterManager
        /workspace/pkg/splunk/enterprise/clustermaster.go:121
github.com/splunk/splunk-operator/controllers.(*ClusterMasterReconciler).Reconcile
        /workspace/controllers/clustermaster_controller.go:103
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227
panic: odd number of arguments passed as key-value pairs for logging
```
image: splunk/splunk-operator:1.1.0

**Comment by pogdin** [comment]
Thanks @mdaniel .  Can you post as much of your Cluster Manager yaml as possible please?

**Comment by mdaniel** [comment]
```yaml
apiVersion: enterprise.splunk.com/v3
kind: ClusterMaster
metadata:
  name: cm
  namespace: splunk
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  smartstore:
    defaults:
      volumeName: s3volume
    volumes:
    - name: s3volume
      provider: aws
      storageType: s3
      endpoint: https://s3-us-west-2.amazonaws.com
      path: some-bucket-name
  serviceAccount: splunk
  resources:
    limits:
      memory: 1Gi
  etcVolumeStorageConfig:
    ephemeralStorage: true
  varVolumeStorageConfig:
    ephemeralStorage: true
```
the panic showed up when I _deleted_ the CM and then repeatedly kept panicking thereafter
