### ISSUE TITLE
Red Hat OpenShift Configuration has the wrong service account in the documentation

### ISSUE THREAD

**Issue by roggy85** [splunk/splunk-operator#764]
Hi,

the documentation for OpenShift in this project still states that the ServiceAccount `default` needs the scc `nonroot`.

But the ServiceAccountName in the splunk-operator-install.yaml is `splunk-operator-controller-manager`

So I think the documentation has to be adopted to

```
oc adm policy add-scc-to-user nonroot -z splunk-operator-controller-manager
```

regards
Martin

**Comment by akondur** [comment]
Hi @roggy85 , the statefulSets deployed as a part of Splunk Enterprise CR's are not attached to a particular service account unless the service account in the [common spec](https://github.com/splunk/splunk-operator/blob/master/docs/CustomResources.md#common-spec-parameters-for-splunk-enterprise-resources) is configured on the CR. Due to this, the statefulSets(of CRs) adopt the default service account.

The documentation [here](https://github.com/splunk/splunk-operator/blob/master/docs/OpenShift.md) is using the service account `default` so as to provide it the permission to run the containers as non-root(in-turn provides the statefulSets of Splunk Enterprise CRs the permission as well). Also if you notice in the 1.0.5 [splunk-operator-install.yaml](https://github.com/splunk/splunk-operator/releases/download/1.0.5/splunk-operator-install.yaml) file the service account used on the operator is `splunk-operator` while the documentation still uses the `default` service account.

Please let me know if that helps resolve the issue

**Comment by roggy85** [comment]
Hi @akondur 
yes the deployed satefulSet is running as default.
But I'm talking about the operator itself.

In version 1.1.0 of `splunk-operator-install.yaml` you can find the following:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    name: splunk-operator
  name: splunk-operator-controller-manager
  namespace: splunk-operator
...
spec:
  template:
    metadata:
      labels:
        control-plane: controller-manager
        name: splunk-operator
    spec:
      serviceAccountName: splunk-operator-controller-manager
...
```

And for that - there is nothing in the documentation to give that serviceaccount the scc nonroot. And without the SCC the operator can't start.
