### ISSUE TITLE
Error from server (Forbidden) when trying to deploy a splunk instance

### ISSUE THREAD

**Issue by roggy85** [splunk/splunk-operator#773]
Hi,

I've successfully deployed the splunk-operator in our OpenShift 4 cluster (Version 4.9.25).
The operator is running in the namespace `splunk-operator` (Version 1.1.0).

But when I try to deploy a simple "standalone" instance in my own namespace I got the error:

```
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "enterprise.splunk.com/v3, Resource=standalones", GroupVersionKind: "enterprise.splunk.com/v3, Kind=Standalone"
Name: "s1", Namespace: "mysplunk"
Object: &{map["metadata":map["name":"s1" "namespace":"mysplunk" "annotations":map["kubectl.kubernetes.io/last-applied-configuration":""]] "apiVersion":"enterprise.splunk.com/v3" "kind":"Standalone"]}
from server for: "dummy.yaml": standalones.enterprise.splunk.com "s1" is forbidden: User "roggy85" cannot get resource "standalones" in API group "enterprise.splunk.com" in the namespace "mysplunk"
```

The ConfigMap `splunk-operator-config` in the `splunk-operator` namespace has the namespace `mysplunk` under `WATCH_NAMESPACE`:

```
oc get cm/splunk-operator-config -o yaml -n splunk-operator
apiVersion: v1
data:
  OPERATOR_NAME: '"splunk-operator"'
  RELATED_IMAGE_SPLUNK_ENTERPRISE: splunk/splunk:8.2.6
  WATCH_NAMESPACE: mysplunk
kind: ConfigMap
metadata:
...
```

So it looks like it something wrong with the permissions? Is a Rolebinding missing? I can't find something about that in the documentation :(

regards
Martin
