### ISSUE TITLE
indexers: readinessProbe and livenessProbe during a splunkd rolling-restart

### ISSUE THREAD

**Issue by dadux** [splunk/splunk-operator#82]
When pushing a bundle that requires a rolling restart of the indexers, the pods state are never updated to not-ready, leading to a bunch of `5xx` or `4xx` on the HEC ingress.

```
          readinessProbe:
            exec:
              command:
                - /bin/grep
                - started
                - /opt/container_artifact/splunk-container.state
```

`splunk-container.state` only gets updated once the ansible-play have finished.

Furthermore, if the `splunkd` restart takes more than 3x 30s, the pod could killed. 
```
          livenessProbe:
            exec:
              command:
                - /sbin/checkstate.sh
            failureThreshold: 3
            initialDelaySeconds: 300
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 30
```
