### ISSUE TITLE
s3 endpoint for SmartStore

### ISSUE THREAD

**Issue by e9169** [splunk/splunk-operator#822]
Hi,

I'm using the latest code and Kubernetes 1.22 on EKS and I had issues while setting up SmartStore. Logs were complaining about the URL of the s3 endpoint so I changed it from s3-region.amazonaws.com to s3.region.amazonaws.com and it started working. This URL appears in both SmartStore and AppFramework documentation. I don't know if it's okay or not or if the operator should just translate that from the YAML into a valid URL but it's not happening as can be seen in the logs. I tested inside a standalone instance, /opt/var/logs/splunkd.log, looking for s3 operations. 

After that change on the URL I managed to synchronize data with the bucket. I would create the PR myself but I'd like to understand first if this URL is fine or if it's wrong in different places in the docs.

Thank you

**Comment by akondur** [comment]
Hi @e9169 , would you mind sharing the smartstore snippet of the failing yaml?

**Comment by e9169** [comment]
I just want to know if this URL in your docs is correct or not for the endpoint since it says https://s3-region.amazonaws.com

Shouldn't it be https://s3.region.amazonaws.com instead?

![Screenshot 2022-07-29 at 08 26 21](https://user-images.githubusercontent.com/1758637/181696598-1794b508-c838-4649-b29e-aa6f373b2a1c.png)

**Comment by dallasmarlow** [comment]
@e9169 both regional URL variants work when the requester is using public DNS and has internet access, but the "<service name>.<region>.amazonaws.com" variant is the more common form (https://docs.aws.amazon.com/general/latest/gr/rande.html).

Are you using a VPC interface endpoint for S3 w/ private DNS enabled by chance? That may be the cause of the "s3-<region>" URL variants not working for you. I think that using the "s3.<region>" URL variant would be preferable IMHO.

**Comment by akondur** [comment]
Hey @e9169 , I have tested the following yaml:

```
apiVersion: enterprise.splunk.com/v3
kind: ClusterMaster
metadata:
  name: cm-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  smartstore:
    defaults:
        volumeName: xxx
    indexes:
      - name: xxx
        remotePath: xxx
        volumeName: xxx
      - name: xxx
        remotePath: xxx
        volumeName: xxx
    volumes:
      - name: xxx
        path: xxx
        endpoint: https://s3-us-west-2.amazonaws.com
        secretRef: xxx
---
apiVersion: enterprise.splunk.com/v3
kind: IndexerCluster
metadata:
  name: idxc-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  replicas: 3
  clusterMasterRef:
    name: cm-example
```

I see that Splunk's connection to S3 is successful aligning with the configuration mentioned in the docs.
