### ISSUE TITLE
 Global K8S Secret object doesn't seem to override settings in defaultsUrl

### ISSUE THREAD

**Issue by marcusschiesser** [splunk/splunk-operator#832]
Found while testing https://github.com/splunk/splunk-operator/issues/657#issuecomment-1167580568 with splunk-operator version 1.1.0

I am having a [Global K8S Secret object](https://splunk.github.io/splunk-operator/Examples.html#managing-global-kubernetes-secret-object) with `password` set and I am setting a `default.yml` encoded in a secret via `defaultsUrl` as [recommended by @pogdin](https://github.com/splunk/splunk-operator/issues/657#issuecomment-1080967050):

```yaml
apiVersion: enterprise.splunk.com/v2
kind: Standalone
metadata:
  name: s1
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  volumes:
    - name: default
      secret:
        secretName: splunk-ldap-secret
  defaultsUrl: /mnt/default/default.yml
```

Actual behavior:
If I use the `defaultsUrl` setting, the password from the _Global K8S Secret object_ is not used. If I don't use the `defaultsUrl` setting the password is used.

Expected behavior:
The password from the _Global K8S Secret object_ is used in both cases.

**Comment by akondur** [comment]
Hey @marcusschiesser , I deployed a Standalone as per this [comment](https://github.com/splunk/splunk-operator/issues/657#issuecomment-1080967050) and tried logging into the UI with the password from the Global K8s secret object and was successful in doing so.

```
[splunk@splunk-s1-standalone-0 splunk]$ ls -ltr  /mnt/splunk-secrets/
total 0
lrwxrwxrwx 1 root splunk 17 Jun 29 17:37 shc_secret -> ..data/shc_secret
lrwxrwxrwx 1 root splunk 15 Jun 29 17:37 password -> ..data/password
lrwxrwxrwx 1 root splunk 19 Jun 29 17:37 pass4SymmKey -> ..data/pass4SymmKey
lrwxrwxrwx 1 root splunk 18 Jun 29 17:37 idxc_secret -> ..data/idxc_secret
lrwxrwxrwx 1 root splunk 16 Jun 29 17:37 hec_token -> ..data/hec_token
lrwxrwxrwx 1 root splunk 18 Jun 29 17:37 default.yml -> ..data/default.yml

[splunk@splunk-s1-standalone-0 splunk]$ cat /mnt/default/default.yml
splunk:
   conf:
   - key: authentication
     value:
        directory: /opt/splunk/etc/system/local
        content:
          AD:
            bindDN : ldapuser.example.net
            bindDNpassword : foobar

[splunk@splunk-s1-standalone-0 splunk]$ env | grep -i defaults
SPLUNK_DEFAULTS_URL=/mnt/default/default.yml,/mnt/splunk-secrets/default.yml
```

Do you mind sharing the steps you followed along with yaml files to deploy and test the same? Also could you share if the global secret was created and mounted on the standalone pod?

**Comment by akondur** [comment]
Hi @marcusschiesser , I did mount a secret on the standalone as follows:

```
apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  name: s1
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  volumes:
    - name: default
      secret:
        secretName: splunk-ldap-secret
  defaultsUrl: /mnt/default/default.yml
```

I had a chat with @pogdin regarding the same and we would like to know if the same steps were followed.

**Comment by marcusschiesser** [comment]
Hmm, I thought @pogdin reproduced the problem too. As far as I recall I used:

For the `default.yml` secret (stored in file named `$TEMPLATE`):

```yaml
splunk:
   conf:
   - key: authentication
     value: 
        directory: /opt/splunk/etc/system/local
        content:
          AD:
            bindDNpassword : ${AD_PASSWORD}
```

Then for generating the two secrets:
```bash
YML=$(cat $TEMPLATE | sed -e "s/\${AD_PASSWORD}/${AD_PASSWORD}/")

kubectl create secret generic splunk-config-secret --from-literal=default.yml="${YML}"
kubectl create secret generic splunk-default-secret --from-literal="password=${SPLUNK_PASSWORD}" --from-literal="pass4SymmKey=${GENERAL_PASS4SYMMKEY}"
```

And then something like this as the manifest file:
```yaml
apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  namespace: playground
  name: staging-playground
spec:
  etcVolumeStorageConfig:
    ephemeralStorage: true
  varVolumeStorageConfig:
    storageClassName: gp2
    storageCapacity: 100Gi
  extraEnv:
    - name: TZ
      value: "Europe/Berlin"
  serviceAccount: dltk-sa
  volumes:
    - name: default
      secret:
        secretName: splunk-config-secret
  defaultsUrl: /mnt/default/default.yml
```

Maybe it's because I also used a `serviceAccount`?

**Comment by pogdin** [comment]
I think I may have spoken too soon @marcusschiesser.  Looking at the pod I have running, I'm able to see the ldap secret and the global secret same as @akondur .

**Comment by marcusschiesser** [comment]
@akondur yes sorry, that's a typo above. I was using `splunk-<namespace>-secret` and running in this issue. As you can't reproduce it and as I am using for now just one secret with the `default.yml` as a workaround, I suggest you close this ticket for the time being.

**Comment by akondur** [comment]
Thanks for the clarification @marcusschiesser , closing the ticket.

**Comment by marcusschiesser** [comment]
@akondur Just tested this issue again and it's reproducible in my setup (using operator 1.1.0). 

I actually wonder how this should work looking at the operator's source. Seems to me that the operator is generating a `/mnt/splunk-secrets/default.yml` from the Global K8S Secret, and this file is then used as the default for the Splunk Ansible configuration:

https://github.com/splunk/splunk-operator/blob/be424de4ec4bdd2a12b777aa20b326206c669d18/pkg/splunk/enterprise/configuration.go#L639

This ansible configuration can then be overwritten using the `defaultsUrl` attribute which is used in the workaround mentioned above:
https://github.com/splunk/splunk-operator/blob/be424de4ec4bdd2a12b777aa20b326206c669d18/pkg/splunk/enterprise/configuration.go#L644-L646

So from my understanding, the Global K8S Secrets are never used if I use a custom `defaultsUrl`. What am I missing here?

**Comment by marcusschiesser** [comment]
@akondur Got it. I tried it now again with the same `/mnt/default/default.yml` and `/mnt/splunk-secrets/default.yml`. I am using image 8.2.6. The good news is that I can log in with the password specified in the Global K8S secrets. Did you guys only test `password`? What doesn' t seem to work is at least `idxc.secret` - Also, after ansible is finished, I couldn't find any `server.conf` file with this setting. Where is ansible generating the conf?

**Comment by marcusschiesser** [comment]
@akondur Today, I had some time to dig a bit deeper into this. It's actually a problem of ansible, but it impacts at least the `idxc.secret` configuration of the `splunk-operator`, so from my (the customer’s) perspective, it did look like a `splunk-operator` issue 😄  Sorry for barking at the wrong tree here. 

Here's the reproducible test case:

1. Create `my-secret` - (I derived it from the secret that the operator generates):
```yaml
splunk:
    hec_disabled: 0
    hec_enableSSL: 0
    hec_token: "XXXXXXXXX"
    password: "XXXXXXX"
    pass4SymmKey: "XXXXXXXX"
    idxc:
        secret: "XXXXXXXXXXX"
    shc:
        secret: "XXXXXXXXXXX"
```

2. Create a second secret `splunk-config-secret` (I guess we run into this issue without it but didn’t verify this):

```yaml
splunk:
  conf:
    - key: authentication
      value:
        directory: /opt/splunk/etc/system/local
        content:
          “AD”:
            bindDNpassword: XXXX
```

3. Build a Splunk app that is configuring `[clustering]` in `server.conf`, e.g. use https://github.com/marcusschiesser/splunk-root-config/tree/splunk/idx_secret_issue and set the URL of your cluster master in `/splunk_root_config/default/server.conf`. This repo contains a Github Action to bundle the app and upload it a public endpoint so it can be used by `SPLUNK_APPS_URL`.

4. Deploy the StatefulSet (similar to the one the operator is creating). Set the URL of the app created in step 3 in the `SPLUNK_APPS_URL` variable:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ump
  name: staging-ump
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ump
  serviceName: ump
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ump
    spec:
      containers:
        - name: ump
          image: splunk/splunk:8.2.7
          imagePullPolicy: Always
          env:
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_DEFAULTS_URL
              value: /mnt/default/default.yml,/mnt/splunk-secrets/default.yml
            - name: SPLUNK_APPS_URL
              value: https://github.com/marcusschiesser/splunk-root-config/releases/download/v_splunk_idx_secret_issue/splunk_root_config.tgz
          volumeMounts:
            - name: default
              mountPath: "/mnt/default"
              readOnly: true
            - name: splunk-secrets
              mountPath: "/mnt/splunk-secrets"
              readOnly: true
      volumes:
        - name: default
          secret:
            secretName: splunk-config-secret
        - name: splunk-secrets
          secret:
            secretName: my-secret
```

Result:
The `password` configuration from `my-secret` is used, but `idxc.secret` is not used.

Expected Result:
All configurations from `my-secret` are used.
