### ISSUE TITLE
Please could you clarify the options to install apps when using Azure?

### ISSUE THREAD

**Issue by adamrushuk** [splunk/splunk-operator#837]
https://github.com/splunk/splunk-operator/blob/master/docs/AppFramework.md?plain=1#L274-L277 mentions only `aws` support is there right now, and `minio` supported soon?

This line shows `minio` _is_ supported? https://github.com/splunk/splunk-operator/blob/master/docs/AppFramework.md?plain=1#L300

Please could you clarify the options to install apps when using `azure` at the present time, and when `azure` support might come to the App Framework?

**Comment by pogdin** [comment]
Hi @adamrushuk. The MinIO client is currently our generic method for using non-AWS S3 and is supported.  We're currently working on adding the native Azure client for blob.  It may be several more months before we have this fully integrated into the Operator App Framework.

**Comment by adamrushuk** [comment]
Excellent, thanks for clarifying @pogdin 
I had some issues using MinIO as I think the aws-cli init containers were trying to get aws region information from the instance metadata endpoint (eg: http://169.254.169.254).
I'm back at work tomorrow so I'll test adding extra env vars to get around that.

**Comment by akondur** [comment]
Hi @adamrushuk , were you able to add the environment variables and test it?

**Comment by adamrushuk** [comment]
> Hi @adamrushuk , were you able to add the environment variables and test it?

Not yet @akondur - I've been super busy on other work tasks :(

**Comment by adamrushuk** [comment]
> Hi @adamrushuk , were you able to add the environment variables and test it?

Sorry for the delay. I'm happy to report that these issue weren't present in the latest `v2.0.0` release. I was able to install Splunk apps via MinIO using:

```
  # https://splunk.github.io/splunk-operator/AppFramework.html#apprepo
  appRepo:
    appsRepoPollIntervalSeconds: 60
    defaults:
      volumeName: volume_app_repo
      scope: local
    appSources:
      - name: admin-apps
        location: admin-apps/
      - name: search-apps
        location: search-apps/
    # https://splunk.github.io/splunk-operator/AppFramework.html#volumes
    volumes:
      - name: volume_app_repo
        storageType: s3
        provider: minio
        path: splunk-apps/standalone
        endpoint: https://minio.url
        secretRef: minio-secret
```

Thanks for the help :)
