### ISSUE TITLE
Indexer Cluster peers don't join

### ISSUE THREAD

**Issue by justinrush** [splunk/splunk-operator#86]
Seeing similar issues to when I tried to create these deployments without the operator: https://github.com/splunk/docker-splunk/issues/368

Using this yaml:
```yaml
---
apiVersion: enterprise.splunk.com/v1alpha2
kind: IndexerCluster
metadata:
  name: spk01-idx-internal
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  replicas: 3
  storageClassName: "longhorn"
  etcStorage: "25Gi"
  varStorage: "100Gi"
---
apiVersion: enterprise.splunk.com/v1alpha2
kind: SearchHeadCluster
metadata:
  name: spk01-sh-internal
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  indexerClusterRef:
    name: spk01-idx-internal
  replicas: 3
  storageClassName: "longhorn"
  etcStorage: "25Gi"
  varStorage: "25Gi"
```

The SH cluster spins up fine - it looks like the hostnames that are specified as peers all resolve to a pod ip (in my case, that's 192.168.0.0/16), which Calico can route without NAT inside the k8s cluster.  The Indexer cluster master spins up as a StatefulSet and creates a Service with a ClusterIP (in my case, that's 10.43.0.0/16).  I'm not a Kubernetes networking expert, but I suspect that Calico NATs the Pod IPs into the Cluster IP space, thus the Index Master sees the source IP of the joining peer as the Node's IP rather than the Pod IP.  This causes the peer to be unable to join the cluster because either the Indexer Cluster Master or the Indexer peer is observing the source IP incorrectly and trying to use that rather than the hostnames it is given.

I tried creating a headless service for the Index Cluster Master StatefulSet, but couldn't get that to work - probably a fat finger somewhere.  To test my theory that the NAT is causing the issue, I temporarily put the Index Cluster Master Pod 0's Pod IP into the server.conf on the peers and bounced the pods and they came up and joined the cluster.

A few questions:
1. If someone has a clue how to make Splunk stop guessing the IP from the source so we can use NAT, that would be awesome.  The only way I can see a way around this is to create an IPPool in Calico that has natOutgoing set to false and configure BGP to peer the pod subnet with upstream switches so the Pod IP subnet is fully routable.  Which I would prefer not to do.
2. Has anyone else hit this and just worked around it by creating a headless service?  if so, can you share deets?
3. Why is the Indexer Cluster Master a StatefulSet?  You'd only ever want one of them and if this were a deployment instead of a StatefulSet it wouldn't be an issue. (or would it?)

Background on my environment:
* Kubernetes 1.17.2
* Docker 18.6.3
* Calico 3.10.2
* CoreDNS 1.6.5
* Baremetal worker nodes on Prem
* Deployed with RKE
* Have been trying to use Splunk 8.0.4
