### ISSUE TITLE
Secret Management: idxc_secret from Global K8S Secret object isn't used

### ISSUE THREAD

**Issue by marcusschiesser** [splunk/splunk-operator#863]
### Please select the type of request

Bug

### Tell us more

**Describe the request** 
The `password` configuration from the Global K8S Secret object is used, but `idxc.secret` is not used.

**Expected behavior**
All configurations from the Global K8S Secret are used. 

**Splunk setup on K8S**
Splunk operator 1.1.0

**Reproduction/Testing steps**
1. Create `my-secret` - (I derived it from the secret that the operator generates):
```yaml
splunk:
    hec_disabled: 0
    hec_enableSSL: 0
    hec_token: "XXXXXXXXX"
    password: "XXXXXXX"
    pass4SymmKey: "XXXXXXXX"
    idxc:
        secret: "XXXXXXXXXXX"
    shc:
        secret: "XXXXXXXXXXX"
```

2. Create a second secret `splunk-config-secret` (I guess we run into this issue without it but didn’t verify this):

```yaml
splunk:
  conf:
    - key: authentication
      value:
        directory: /opt/splunk/etc/system/local
        content:
          “AD”:
            bindDNpassword: XXXX
```

3. Build a Splunk app that is configuring `[clustering]` in `server.conf`, e.g. use https://github.com/marcusschiesser/splunk-root-config/tree/splunk/idx_secret_issue and set the URL of your cluster master in `/splunk_root_config/default/server.conf`. This repo contains a Github Action to bundle the app and upload it a public endpoint so it can be used by `SPLUNK_APPS_URL`.

4. Deploy the StatefulSet (similar to the one the operator is creating). Set the URL of the app created in step 3 in the `SPLUNK_APPS_URL` variable:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ump
  name: staging-ump
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ump
  serviceName: ump
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ump
    spec:
      containers:
        - name: ump
          image: splunk/splunk:8.2.7
          imagePullPolicy: Always
          env:
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_DEFAULTS_URL
              value: /mnt/default/default.yml,/mnt/splunk-secrets/default.yml
            - name: SPLUNK_APPS_URL
              value: https://github.com/marcusschiesser/splunk-root-config/releases/download/v_splunk_idx_secret_issue/splunk_root_config.tgz
          volumeMounts:
            - name: default
              mountPath: "/mnt/default"
              readOnly: true
            - name: splunk-secrets
              mountPath: "/mnt/splunk-secrets"
              readOnly: true
      volumes:
        - name: default
          secret:
            secretName: splunk-config-secret
        - name: splunk-secrets
          secret:
            secretName: my-secret
```

**K8s environment**
- K8S 1.21 on EKS

**Comment by marcusschiesser** [comment]
Currently, I am deploying a second pod as a workaround that is configuring the standalone above to connect to the cluster:

E.g. to connect to a `my-manager-node`, I am deploying:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ump
  name: splunk-configurator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: splunk-configurator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: splunk-configurator
    spec:
      containers:
        - name: splunk-configurator
          # Note: would be nicer to use here curl instead and calling the Splunk API. Unfortunately 
          # calling https://docs.splunk.com/Documentation/Splunk/8.2.8/RESTREF/RESTcluster#cluster.2Fconfig.2Fconfig
          # with the same parameters is not working, hence we're using the Splunk CLI
          image: splunk/splunk:8.2.8
          command: ["sudo", "/bin/sh", "-c"]
          args:
            - touch /opt/splunk/etc/splunk-launch.conf;
              while true;
              do URI=https://splunk-staging-ump-standalone-service:8089;
              CRED=admin:$(cat /mnt/splunk-secrets/password);
              echo 'set secret to connect to index cluster - does not require restart';
              /opt/splunk/bin/splunk edit cluster-config -auth ${CRED} -mode searchhead -manager_uri https://my-manager-node:8089 -secret $(cat /mnt/splunk-secrets/idxc_secret) -uri ${URI};
              sleep 30;
              done;
          volumeMounts:
            - mountPath: /mnt/splunk-secrets
              name: mnt-splunk-secrets
      volumes:
        - name: mnt-splunk-secrets
          secret:
            secretName: splunk-ump-secret
```

**Comment by akondur** [comment]
Hey @marcusschiesser , are you still seeing this issue?

**Comment by marcusschiesser** [comment]
Yes it's still reproducible with the test case above

**Comment by akondur** [comment]
Hey @marcusschiesser ,

**Repro:**
I tried to reproduce the issue using the method you mentioned. Here is the yaml I used:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: staging-ump
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ump
  serviceName: ump
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ump
    spec:
      containers:
        - name: ump
          image: splunk/splunk:8.2.7
          imagePullPolicy: Always
          env:
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_DEFAULTS_URL
              value: /mnt/default/default.yml,/mnt/splunk-secrets/default.yml
            - name: SPLUNK_APPS_URL
              value: https://github.com/marcusschiesser/splunk-root-config/releases/download/v_splunk_idx_secret_issue/splunk_root_config.tgz
            - name: DEBUG
              value: "true"
            - name: ANSIBLE_EXTRA_FLAGS
              value: "-vvv"
          volumeMounts:
            - name: default
              mountPath: "/mnt/default"
              readOnly: true
            - name: splunk-secrets
              mountPath: "/mnt/splunk-secrets"
              readOnly: true
      volumes:
        - name: default
          secret:
            secretName: splunk-config-secret
        - name: splunk-secrets
          secret:
            secretName: my-secret
```

On sshing into the container, as expected we both secrets mounted onto the pod:

```
[splunk@staging-ump-0 splunk]$ ls -ltr /mnt/default/
total 0
lrwxrwxrwx 1 root root 18 Feb  9 18:35 default.yml -> ..data/default.yml
[splunk@staging-ump-0 splunk]$ ls -ltr /mnt/splunk-secrets/
total 0
lrwxrwxrwx 1 root root 18 Feb  9 18:35 default.yml -> ..data/default.yml
```

Defaults setup properly:
```
[splunk@staging-ump-0 splunk]$ env | grep -i defaults
SPLUNK_DEFAULTS_URL=/mnt/default/default.yml,/mnt/splunk-secrets/default.yml
```

We also see that the app you provided is on the pod:
```
[splunk@staging-ump-0 splunk]$ cat /opt/splunk/etc/apps/splunk_root_config/default/server.conf
[clustering]
master_uri = https://zbm-splunk-mnode.zeppelin.corp:8089
mode = searchhead
```

On checking ansible inventory, I see that the right idxc.secret is being picked up by the inventory
```
[splunk@staging-ump-0 splunk]$ /opt/ansible/inventory/environ.py | python -m json.tool | grep -i idxc -A 2
                    "idxc": {
                        "secret": "xxx",
                        "pass4SymmKey": "xxx",
```
Upto this point the operator has done its job providing the right secrets and pointing ansible in the right direction in terms of secrets only(not clustering, this is important). 

**Root cause:**
The problem here is that ansible does not have the right trigger to setup the connection from this standalone to the cluster maanger. Typically the operator recommends you to use `clusterManagerRef` onto a standalone which importantly adds the env variable `SPLUNK_CLUSTER_MASTER_URL` which is picked up by ansible [here](https://github.com/splunk/splunk-ansible/blob/develop/inventory/environ.py#L288). This setting triggers the `peer_cluster_master.yml` task [here](https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_standalone/tasks/main.yml#L18) which is responsible for setting up `server.conf` via the splunk cli command:

`command: "{{ splunk.exec }} edit cluster-config -mode searchhead -master_uri {{ cert_prefix }}://{{ splunk.cluster_master_url }}:{{ splunk.svc_port }} -replication_port {{ splunk.idxc.replication_port }} -secret '{{ splunk.idxc.pass4SymmKey }}' -auth '{{ splunk.admin_user }}:{{ splunk.password }}'"` 

Basically, there was no way for ansible to pick up the `idxc.secret` from its inventory(which correctly set it up from the global K8s secret) and setup server.conf.

**Solution**
I edited the statefulSet yaml by adding an extra environment variable to point to a clusterManager named `example` which I had already deployed(pasted only environment variable section, rest remains the same):

```
          env:
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_DEFAULTS_URL
              value: /mnt/default/default.yml,/mnt/splunk-secrets/default.yml
            - name: SPLUNK_APPS_URL
              value: https://github.com/marcusschiesser/splunk-root-config/releases/download/v_splunk_idx_secret_issue/splunk_root_config.tgz
            - name: DEBUG
              value: "true"
            - name: ANSIBLE_EXTRA_FLAGS
              value: "-vvv"
            - name: SPLUNK_CLUSTER_MASTER_URL.  ---->> Added this
              value: "splunk-example-cluster-manager-service"
```

With this the server.conf has been edited properly(I double checked the decrypted value and it matches the global K8s secret):

```[splunk@staging-ump-new-0 splunk]$ cat etc/system/local/server.conf
[splunk@staging-ump-new-0 splunk]$ cat etc/system/local/server.conf | grep -i clustering -A 3
[clustering]
master_uri = https://splunk-example-cluster-manager-service:8089
mode = searchhead
pass4SymmKey = $7$K2Mwoyh2tFfVoq+qiZDe+flig8s+9OP8sL7bYkh2/ugx0pJGb6+1b1txDxaHlGNEPor0S6hB5mk=
```

**Analysis:**
If using the operator please make sure you use the `clusterManagerRef` to point to the right clusterManager to setup clustering. If deploying without operator, please make sure you are using the right environment variable `SPLUNK_CLUSTER_MASTER_URL` to trigger ansible to setup clustering properly.

Given this solution, please let us know if we can close out this issue as well as the other linked [issue](https://github.com/splunk/splunk-operator/issues/657) for injecting passwords via `defaultsUrl`.
