### ISSUE TITLE
Splunk Operator: Support calling commands after pod is ready

### ISSUE THREAD

**Issue by marcusschiesser** [splunk/splunk-operator#875]
### Please select the type of request

Feature Request

### Tell us more

**Describe the request**
Adding [configuration apps](https://github.com/splunk/splunk-operator/blob/master/docs/Examples.md#using-apps-for-splunk-configuration), it's possible to configure the Splunk instance created by the operator.

Sometimes, that's not sufficient, e.g. for adding users, the Splunk CLI would be needed which can't be called at the moment.

One way to fix this would be to support calling commands after the pod is ready. The commands could be added as an array in a `postInitCommands` tag, e.g.:

```yaml
apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  name: test
spec:
  postInitCommands: 
  - name: add-user-rest
    command: ["/opt/splunk/bin/splunk add user ${REST_USER_NAME} -password ${REST_USER_PASSWORD} -role rest"]
```

To be able to pass parameters to the commands they should resolve ENV variables (as in the example above).

More flexible would be to support `postInitContainers`, to allow running arbitrary containers after the pod is ready. To support calling CLI commands there could be a `splunk-cli` container providing just the splunk CLI tool:

```yaml
---
apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  name: test
spec:
  postInitContainer: 
  - name: add-user-rest
    image: splunk:splunk-cli:9.0.1
    command: ["/opt/splunk/bin/splunk add user ${REST_USER_NAME} -password ${REST_USER_PASSWORD} -role rest"]
```

**Comment by marcusschiesser** [comment]
That's my current workaround:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-configurator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: splunk-configurator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: splunk-configurator
    spec:
      containers:
        - name: splunk-configurator
          image: splunk/splunk:8.2.8
          command: ["sudo", "-E", "/bin/sh", "-c"]
          env:
            - name: URI
              value: "https://splunk-my-server-standalone-service:8089"
          args:
            - SPLUNK_START_ARGS=--accept-license SPLUNK_PASSWORD=changeme /sbin/entrypoint.sh start-and-exit;
              while true;
              do CRED=admin:$(cat /mnt/splunk-secrets/password);
              /opt/splunk/bin/splunk add user rest -password test -role rest -auth ${CRED} -uri ${URI};
              sleep 60;
              done;
          volumeMounts:
            - mountPath: /mnt/splunk-secrets
              name: mnt-splunk-secrets
      volumes:
        - name: mnt-splunk-secrets
          secret:
            secretName: splunk-default-secret
```

as described in: https://marcusschiesser.de/2022/10/27/configuring-splunk-instances-running-k8s/
