### ISSUE TITLE
Splunk Operator: BUG - KVstore tries to revert to 3.6.17

### ISSUE THREAD

**Issue by satellite-no** [splunk/splunk-operator#909]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
- Splunk reverts to version 3.6 of mongodb (kvstore) when the standalone splunk pod is recreated after a failure or scaling procedure (ie scale to 0 then back to 1). 

**Expected behavior**
- Splunk should only use version 4.2.17 of mongodb.

**Splunk setup on K8S**
- Details of the Splunk setup on the K8s cluster.

```yaml
---
apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  name: boris-aio
  namespace: boris
spec:
  image: splunk/splunk:9.0.1
  replicas: 1
  defaults: |-
    splunk:
      http_enableSSL: 1
```

**Reproduction/Testing steps**
- Create new Splunk instance
- Scale down to 0. 
- Scale back up to 1. 

**K8s environment**
- AWS EKS, 1.23.0

**K8s collector data(optional)**
- Please provide data collected from the [K8s collectors](https://github.com/splunk/splunk-operator/blob/develop/docs/K8SCollectors.md), if any.

**Additional context(optional)**
- Add any other context about the problem here.
