### ISSUE TITLE
selector does not match template labels errors

### ISSUE THREAD

**Issue by mikedickey** [splunk/splunk-operator#93]
Creating a custom resource that includes certain labels will causing provisioning to fail. For example, the following resource:

```
apiVersion: enterprise.splunk.com/v1alpha2
kind: Standalone
metadata:
  name: test
  labels:
    app.kubernetes.io/managed-by: anyone
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec: {}
```

Will yield the following errors in the splunk operator logs:

```
{"level":"error","ts":1592936956.9408255,"logger":"splunk.reconcile.UpdateResource","msg":"Failed to update resource","name":"splunk-test-standalone","namespace":"user-mdickey","error":"StatefulSet.apps \"splunk-test-standalone\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"app.kubernetes.io/component\":\"standalone\", \"app.kubernetes.io/instance\":\"splunk-test-standalone\", \"app.kubernetes.io/managed-by\":\"anyone\", \"app.kubernetes.io/name\":\"standalone\", \"app.kubernetes.io/part-of\":\"splunk-test-standalone\"}: `selector` does not match template `labels`"...
```

This is because operator attempts to copy labels from custom resources into any service, deployment or statefulset objects it creates that are associated with them. The `app.kubernetes.io/managed-by` is one of the labels that operator applies itself (along with a few others) to statefulsets, and the `selector` field of the spec has to match the pod template labels. The copy from the custom resource spec clobbers the labels being set by operator, causing a mismatch and resulting in these errors from Kubernetes.

The labels that will cause this error include:

* app.kubernetes.io/managed-by
* app.kubernetes.io/component
* app.kubernetes.io/name
* app.kubernetes.io/part-of
* app.kubernetes.io/instance
