### ISSUE TITLE
Smartstore does not work with K8s ServiceAccount

### ISSUE THREAD

**Issue by satellite-no** [splunk/splunk-operator#955]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
- Access denied when using Kubernetes service account to access smartstore buckets.

**Expected behavior**
- Smart store should work as as normaly using kubernetes service account. 

**Splunk setup on K8S**
- Default Standalone setup using below smart store config.

```yaml
  smartstore:
    defaults:
      volumeName: s3volume
    volumes:
      - name: s3volume
        path: deepwatch-boris-smartstore/
        endpoint: https://s3.amazonaws.com
```

**Reproduction/Testing steps**
- Configure smartstore per docs but set `serviceAccount: boris-sa` on the spec definiation of the standalone instance. 
- I am able to install aws cli on splunk container and list, get, and put objects to the s3 bucket but Splunk still logs access denied.  My assumption is the CLI and Python SDK are using different env variables. 

**K8s environment**
- AWS EKS setup with configured OIDC provider etc.
