### ISSUE TITLE
Indexer cluster labels should use the cluster name + name space + cluster name

### ISSUE THREAD

**Issue by ryanfaircloth** [splunk/splunk-operator#98]
currently, all indexer clusters are getting a label of idxc_label. To allow the use of monitoring console a unique name is required. For example, concatenate k8s cluster ID +  name space + cluster name

**Comment by akondur** [comment]
Hey @ryanfaircloth , we can set the `cluster_label` for an indexer cluster by passing an environment variable `SPLUNK_IDXC_LABEL` to the clusterManager CR spec:

```
apiVersion: enterprise.splunk.com/v4
kind: ClusterManager
metadata:
  name: example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  extraEnv:
  - name: SPLUNK_IDXC_LABEL
    value: indexer_cluster_example
---
apiVersion: enterprise.splunk.com/v4
kind: IndexerCluster
metadata:
  name: example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  replicas: 3
  clusterManagerRef:
     name: example
```

The cluster manager on coming up has the right `cluster_label` setup which can then be used by the monitoring console.

```
[splunk@splunk-example-cluster-manager-0 splunk]$ cat etc/system/local/server.conf | grep -i cluster_label -B 1 -A 1
[clustering]
cluster_label = indexer_cluster_example
mode = manager
```

Please let me know if this solution works for you.
